/* Generated by Yosys 0.46 (git sha1 e97731b9dda91fa5fa53ed87df7c34163ba59a41, clang++ 17.0.6 -fPIC -O3) */

module rng_top(clk_i, rst_i, req_num_i, wr_i, num_to_send_o);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  input clk_i;
  wire clk_i;
  wire \num_i_bar[0] ;
  wire \num_i_bar[1] ;
  wire \num_i_bar[2] ;
  output [2:0] num_to_send_o;
  wire [2:0] num_to_send_o;
  wire req_num_again;
  input req_num_i;
  wire req_num_i;
  wire \rng_rd.cache[0] ;
  wire \rng_rd.cache[1] ;
  wire \rng_rd.cache[2] ;
  wire \rng_rd.ram_1[0] ;
  wire \rng_rd.ram_1[1] ;
  wire \rng_rd.ram_1[2] ;
  wire \rng_rd.ram_2[0] ;
  wire \rng_rd.ram_2[1] ;
  wire \rng_rd.ram_2[2] ;
  wire \rng_rd.ram_3[0] ;
  wire \rng_rd.ram_3[1] ;
  wire \rng_rd.ram_3[2] ;
  wire \rng_rd.ram_4[0] ;
  wire \rng_rd.ram_4[1] ;
  wire \rng_rd.ram_4[2] ;
  wire \rng_rd.ram_5[0] ;
  wire \rng_rd.ram_5[1] ;
  wire \rng_rd.ram_5[2] ;
  wire \rng_rd.ram_6[0] ;
  wire \rng_rd.ram_6[1] ;
  wire \rng_rd.ram_6[2] ;
  wire \rng_rd.ram_7[0] ;
  wire \rng_rd.ram_7[1] ;
  wire \rng_rd.ram_7[2] ;
  wire \rng_rd.wr_ff1 ;
  wire \rng_rd.wr_ff2 ;
  wire \rng_rd.wr_ff2_d ;
  wire \rng_rd.wr_pulse ;
  input rst_i;
  wire rst_i;
  input wr_i;
  wire wr_i;
  sky130_fd_sc_hd__inv_2 _081_ (
    .A(\rng_rd.cache[1] ),
    .Y(_050_)
  );
  sky130_fd_sc_hd__inv_2 _082_ (
    .A(\rng_rd.cache[2] ),
    .Y(_051_)
  );
  sky130_fd_sc_hd__xor2_2 _083_ (
    .A(\rng_rd.cache[0] ),
    .B(\rng_rd.ram_6[0] ),
    .X(_052_)
  );
  sky130_fd_sc_hd__xor2_2 _084_ (
    .A(\rng_rd.cache[2] ),
    .B(\rng_rd.ram_6[2] ),
    .X(_053_)
  );
  sky130_fd_sc_hd__xor2_2 _085_ (
    .A(\rng_rd.cache[1] ),
    .B(\rng_rd.ram_6[1] ),
    .X(_054_)
  );
  sky130_fd_sc_hd__or2_2 _086_ (
    .A(\rng_rd.cache[1] ),
    .B(\rng_rd.ram_7[1] ),
    .X(_055_)
  );
  sky130_fd_sc_hd__nand2_2 _087_ (
    .A(\rng_rd.cache[1] ),
    .B(\rng_rd.ram_7[1] ),
    .Y(_056_)
  );
  sky130_fd_sc_hd__xor2_2 _088_ (
    .A(\rng_rd.cache[0] ),
    .B(\rng_rd.ram_7[0] ),
    .X(_057_)
  );
  sky130_fd_sc_hd__nand2_2 _089_ (
    .A(\rng_rd.cache[2] ),
    .B(\rng_rd.ram_7[2] ),
    .Y(_058_)
  );
  sky130_fd_sc_hd__or2_2 _090_ (
    .A(\rng_rd.cache[2] ),
    .B(\rng_rd.ram_7[2] ),
    .X(_059_)
  );
  sky130_fd_sc_hd__a22o_2 _091_ (
    .A1(_055_),
    .A2(_056_),
    .B1(_058_),
    .B2(_059_),
    .X(_060_)
  );
  sky130_fd_sc_hd__xor2_2 _092_ (
    .A(\rng_rd.cache[2] ),
    .B(\rng_rd.ram_5[2] ),
    .X(_061_)
  );
  sky130_fd_sc_hd__xor2_2 _093_ (
    .A(\rng_rd.cache[0] ),
    .B(\rng_rd.ram_5[0] ),
    .X(_062_)
  );
  sky130_fd_sc_hd__nand2_2 _094_ (
    .A(\rng_rd.cache[1] ),
    .B(\rng_rd.ram_5[1] ),
    .Y(_063_)
  );
  sky130_fd_sc_hd__or2_2 _095_ (
    .A(\rng_rd.cache[1] ),
    .B(\rng_rd.ram_5[1] ),
    .X(_064_)
  );
  sky130_fd_sc_hd__a211o_2 _096_ (
    .A1(_063_),
    .A2(_064_),
    .B1(_061_),
    .C1(_062_),
    .X(_065_)
  );
  sky130_fd_sc_hd__or2_2 _097_ (
    .A(\rng_rd.cache[1] ),
    .B(\rng_rd.ram_4[1] ),
    .X(_066_)
  );
  sky130_fd_sc_hd__nand2_2 _098_ (
    .A(\rng_rd.cache[1] ),
    .B(\rng_rd.ram_4[1] ),
    .Y(_067_)
  );
  sky130_fd_sc_hd__xor2_2 _099_ (
    .A(\rng_rd.cache[0] ),
    .B(\rng_rd.ram_4[0] ),
    .X(_068_)
  );
  sky130_fd_sc_hd__or2_2 _100_ (
    .A(\rng_rd.cache[2] ),
    .B(\rng_rd.ram_4[2] ),
    .X(_069_)
  );
  sky130_fd_sc_hd__nand2_2 _101_ (
    .A(\rng_rd.cache[2] ),
    .B(\rng_rd.ram_4[2] ),
    .Y(_070_)
  );
  sky130_fd_sc_hd__a221o_2 _102_ (
    .A1(_066_),
    .A2(_067_),
    .B1(_069_),
    .B2(_070_),
    .C1(_068_),
    .X(_071_)
  );
  sky130_fd_sc_hd__xor2_2 _103_ (
    .A(\rng_rd.cache[1] ),
    .B(\rng_rd.ram_1[1] ),
    .X(_072_)
  );
  sky130_fd_sc_hd__or2_2 _104_ (
    .A(\rng_rd.cache[0] ),
    .B(\rng_rd.ram_1[0] ),
    .X(_073_)
  );
  sky130_fd_sc_hd__nand2_2 _105_ (
    .A(\rng_rd.cache[0] ),
    .B(\rng_rd.ram_1[0] ),
    .Y(_074_)
  );
  sky130_fd_sc_hd__or2_2 _106_ (
    .A(\rng_rd.cache[2] ),
    .B(\rng_rd.ram_1[2] ),
    .X(_075_)
  );
  sky130_fd_sc_hd__nand2_2 _107_ (
    .A(\rng_rd.cache[2] ),
    .B(\rng_rd.ram_1[2] ),
    .Y(_076_)
  );
  sky130_fd_sc_hd__a221o_2 _108_ (
    .A1(_073_),
    .A2(_074_),
    .B1(_075_),
    .B2(_076_),
    .C1(_072_),
    .X(_077_)
  );
  sky130_fd_sc_hd__or2_2 _109_ (
    .A(\rng_rd.cache[2] ),
    .B(\rng_rd.ram_2[2] ),
    .X(_078_)
  );
  sky130_fd_sc_hd__nand2_2 _110_ (
    .A(\rng_rd.cache[2] ),
    .B(\rng_rd.ram_2[2] ),
    .Y(_079_)
  );
  sky130_fd_sc_hd__xor2_2 _111_ (
    .A(\rng_rd.cache[1] ),
    .B(\rng_rd.ram_2[1] ),
    .X(_080_)
  );
  sky130_fd_sc_hd__nand2_2 _112_ (
    .A(\rng_rd.cache[0] ),
    .B(\rng_rd.ram_2[0] ),
    .Y(_032_)
  );
  sky130_fd_sc_hd__or2_2 _113_ (
    .A(\rng_rd.cache[0] ),
    .B(\rng_rd.ram_2[0] ),
    .X(_033_)
  );
  sky130_fd_sc_hd__a221o_2 _114_ (
    .A1(_078_),
    .A2(_079_),
    .B1(_032_),
    .B2(_033_),
    .C1(_080_),
    .X(_034_)
  );
  sky130_fd_sc_hd__xor2_2 _115_ (
    .A(num_to_send_o[0]),
    .B(\rng_rd.cache[0] ),
    .X(_035_)
  );
  sky130_fd_sc_hd__a221oi_2 _116_ (
    .A1(num_to_send_o[1]),
    .A2(_050_),
    .B1(num_to_send_o[2]),
    .B2(_051_),
    .C1(_035_),
    .Y(_036_)
  );
  sky130_fd_sc_hd__o221a_2 _117_ (
    .A1(num_to_send_o[1]),
    .A2(_050_),
    .B1(num_to_send_o[2]),
    .B2(_051_),
    .C1(_036_),
    .X(_037_)
  );
  sky130_fd_sc_hd__xor2_2 _118_ (
    .A(\rng_rd.cache[0] ),
    .B(\rng_rd.ram_3[0] ),
    .X(_038_)
  );
  sky130_fd_sc_hd__nand2_2 _119_ (
    .A(\rng_rd.cache[1] ),
    .B(\rng_rd.ram_3[1] ),
    .Y(_039_)
  );
  sky130_fd_sc_hd__or2_2 _120_ (
    .A(\rng_rd.cache[1] ),
    .B(\rng_rd.ram_3[1] ),
    .X(_040_)
  );
  sky130_fd_sc_hd__xor2_2 _121_ (
    .A(\rng_rd.cache[2] ),
    .B(\rng_rd.ram_3[2] ),
    .X(_041_)
  );
  sky130_fd_sc_hd__a211o_2 _122_ (
    .A1(_039_),
    .A2(_040_),
    .B1(_041_),
    .C1(_038_),
    .X(_042_)
  );
  sky130_fd_sc_hd__o311a_2 _123_ (
    .A1(_052_),
    .A2(_053_),
    .A3(_054_),
    .B1(_071_),
    .C1(_077_),
    .X(_043_)
  );
  sky130_fd_sc_hd__o2111a_2 _124_ (
    .A1(_057_),
    .A2(_060_),
    .B1(_065_),
    .C1(_034_),
    .D1(_042_),
    .X(_044_)
  );
  sky130_fd_sc_hd__and4b_2 _125_ (
    .A_N(_037_),
    .B(_043_),
    .C(_044_),
    .D(\rng_rd.wr_pulse ),
    .X(_045_)
  );
  sky130_fd_sc_hd__inv_2 _126_ (
    .A(_045_),
    .Y(_000_)
  );
  sky130_fd_sc_hd__and2b_2 _127_ (
    .A_N(\rng_rd.wr_ff2_d ),
    .B(\rng_rd.wr_ff2 ),
    .X(_001_)
  );
  sky130_fd_sc_hd__mux2_1 _128_ (
    .A0(\rng_rd.cache[0] ),
    .A1(\num_i_bar[0] ),
    .S(wr_i),
    .X(_002_)
  );
  sky130_fd_sc_hd__mux2_1 _129_ (
    .A0(\rng_rd.cache[1] ),
    .A1(\num_i_bar[1] ),
    .S(wr_i),
    .X(_003_)
  );
  sky130_fd_sc_hd__mux2_1 _130_ (
    .A0(\rng_rd.cache[2] ),
    .A1(\num_i_bar[2] ),
    .S(wr_i),
    .X(_004_)
  );
  sky130_fd_sc_hd__mux2_1 _131_ (
    .A0(\rng_rd.ram_7[0] ),
    .A1(\rng_rd.ram_6[0] ),
    .S(_045_),
    .X(_005_)
  );
  sky130_fd_sc_hd__mux2_1 _132_ (
    .A0(\rng_rd.ram_7[1] ),
    .A1(\rng_rd.ram_6[1] ),
    .S(_045_),
    .X(_006_)
  );
  sky130_fd_sc_hd__mux2_1 _133_ (
    .A0(\rng_rd.ram_7[2] ),
    .A1(\rng_rd.ram_6[2] ),
    .S(_045_),
    .X(_007_)
  );
  sky130_fd_sc_hd__mux2_1 _134_ (
    .A0(\rng_rd.ram_5[0] ),
    .A1(\rng_rd.ram_4[0] ),
    .S(_045_),
    .X(_008_)
  );
  sky130_fd_sc_hd__mux2_1 _135_ (
    .A0(\rng_rd.ram_5[1] ),
    .A1(\rng_rd.ram_4[1] ),
    .S(_045_),
    .X(_009_)
  );
  sky130_fd_sc_hd__mux2_1 _136_ (
    .A0(\rng_rd.ram_5[2] ),
    .A1(\rng_rd.ram_4[2] ),
    .S(_045_),
    .X(_010_)
  );
  sky130_fd_sc_hd__mux2_1 _137_ (
    .A0(\rng_rd.ram_4[0] ),
    .A1(\rng_rd.ram_3[0] ),
    .S(_045_),
    .X(_011_)
  );
  sky130_fd_sc_hd__mux2_1 _138_ (
    .A0(\rng_rd.ram_4[1] ),
    .A1(\rng_rd.ram_3[1] ),
    .S(_045_),
    .X(_012_)
  );
  sky130_fd_sc_hd__mux2_1 _139_ (
    .A0(\rng_rd.ram_4[2] ),
    .A1(\rng_rd.ram_3[2] ),
    .S(_045_),
    .X(_013_)
  );
  sky130_fd_sc_hd__mux2_1 _140_ (
    .A0(\rng_rd.ram_3[0] ),
    .A1(\rng_rd.ram_2[0] ),
    .S(_045_),
    .X(_014_)
  );
  sky130_fd_sc_hd__mux2_1 _141_ (
    .A0(\rng_rd.ram_3[1] ),
    .A1(\rng_rd.ram_2[1] ),
    .S(_045_),
    .X(_015_)
  );
  sky130_fd_sc_hd__mux2_1 _142_ (
    .A0(\rng_rd.ram_3[2] ),
    .A1(\rng_rd.ram_2[2] ),
    .S(_045_),
    .X(_016_)
  );
  sky130_fd_sc_hd__mux2_1 _143_ (
    .A0(\rng_rd.ram_2[0] ),
    .A1(\rng_rd.ram_1[0] ),
    .S(_045_),
    .X(_017_)
  );
  sky130_fd_sc_hd__mux2_1 _144_ (
    .A0(\rng_rd.ram_2[1] ),
    .A1(\rng_rd.ram_1[1] ),
    .S(_045_),
    .X(_018_)
  );
  sky130_fd_sc_hd__mux2_1 _145_ (
    .A0(\rng_rd.ram_2[2] ),
    .A1(\rng_rd.ram_1[2] ),
    .S(_045_),
    .X(_019_)
  );
  sky130_fd_sc_hd__mux2_1 _146_ (
    .A0(\rng_rd.ram_1[0] ),
    .A1(num_to_send_o[0]),
    .S(_045_),
    .X(_020_)
  );
  sky130_fd_sc_hd__mux2_1 _147_ (
    .A0(\rng_rd.ram_1[1] ),
    .A1(num_to_send_o[1]),
    .S(_045_),
    .X(_021_)
  );
  sky130_fd_sc_hd__mux2_1 _148_ (
    .A0(\rng_rd.ram_1[2] ),
    .A1(num_to_send_o[2]),
    .S(_045_),
    .X(_022_)
  );
  sky130_fd_sc_hd__mux2_1 _149_ (
    .A0(num_to_send_o[0]),
    .A1(\rng_rd.cache[0] ),
    .S(_045_),
    .X(_023_)
  );
  sky130_fd_sc_hd__mux2_1 _150_ (
    .A0(num_to_send_o[1]),
    .A1(\rng_rd.cache[1] ),
    .S(_045_),
    .X(_024_)
  );
  sky130_fd_sc_hd__mux2_1 _151_ (
    .A0(num_to_send_o[2]),
    .A1(\rng_rd.cache[2] ),
    .S(_045_),
    .X(_025_)
  );
  sky130_fd_sc_hd__o21ai_2 _152_ (
    .A1(req_num_again),
    .A2(req_num_i),
    .B1(\num_i_bar[0] ),
    .Y(_046_)
  );
  sky130_fd_sc_hd__or3_2 _153_ (
    .A(\num_i_bar[0] ),
    .B(req_num_again),
    .C(req_num_i),
    .X(_047_)
  );
  sky130_fd_sc_hd__and2_2 _154_ (
    .A(_046_),
    .B(_047_),
    .X(_026_)
  );
  sky130_fd_sc_hd__o211a_2 _155_ (
    .A1(req_num_again),
    .A2(req_num_i),
    .B1(\num_i_bar[1] ),
    .C1(\num_i_bar[0] ),
    .X(_048_)
  );
  sky130_fd_sc_hd__and2b_2 _156_ (
    .A_N(\num_i_bar[1] ),
    .B(_046_),
    .X(_049_)
  );
  sky130_fd_sc_hd__nor2_2 _157_ (
    .A(_048_),
    .B(_049_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__xor2_2 _158_ (
    .A(\num_i_bar[2] ),
    .B(_048_),
    .X(_028_)
  );
  sky130_fd_sc_hd__mux2_1 _159_ (
    .A0(\rng_rd.ram_6[0] ),
    .A1(\rng_rd.ram_5[0] ),
    .S(_045_),
    .X(_029_)
  );
  sky130_fd_sc_hd__mux2_1 _160_ (
    .A0(\rng_rd.ram_6[1] ),
    .A1(\rng_rd.ram_5[1] ),
    .S(_045_),
    .X(_030_)
  );
  sky130_fd_sc_hd__mux2_1 _161_ (
    .A0(\rng_rd.ram_6[2] ),
    .A1(\rng_rd.ram_5[2] ),
    .S(_045_),
    .X(_031_)
  );
  sky130_fd_sc_hd__dfrtp_2 _162_ (
    .CLK(clk_i),
    .D(_002_),
    .Q(\rng_rd.cache[0] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _163_ (
    .CLK(clk_i),
    .D(_003_),
    .Q(\rng_rd.cache[1] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _164_ (
    .CLK(clk_i),
    .D(_004_),
    .Q(\rng_rd.cache[2] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _165_ (
    .CLK(clk_i),
    .D(_005_),
    .Q(\rng_rd.ram_7[0] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _166_ (
    .CLK(clk_i),
    .D(_006_),
    .Q(\rng_rd.ram_7[1] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _167_ (
    .CLK(clk_i),
    .D(_007_),
    .Q(\rng_rd.ram_7[2] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _168_ (
    .CLK(clk_i),
    .D(_008_),
    .Q(\rng_rd.ram_5[0] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _169_ (
    .CLK(clk_i),
    .D(_009_),
    .Q(\rng_rd.ram_5[1] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _170_ (
    .CLK(clk_i),
    .D(_010_),
    .Q(\rng_rd.ram_5[2] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _171_ (
    .CLK(clk_i),
    .D(wr_i),
    .Q(\rng_rd.wr_ff1 ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _172_ (
    .CLK(clk_i),
    .D(_011_),
    .Q(\rng_rd.ram_4[0] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _173_ (
    .CLK(clk_i),
    .D(_012_),
    .Q(\rng_rd.ram_4[1] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _174_ (
    .CLK(clk_i),
    .D(_013_),
    .Q(\rng_rd.ram_4[2] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _175_ (
    .CLK(clk_i),
    .D(_014_),
    .Q(\rng_rd.ram_3[0] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _176_ (
    .CLK(clk_i),
    .D(_015_),
    .Q(\rng_rd.ram_3[1] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _177_ (
    .CLK(clk_i),
    .D(_016_),
    .Q(\rng_rd.ram_3[2] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _178_ (
    .CLK(clk_i),
    .D(_017_),
    .Q(\rng_rd.ram_2[0] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _179_ (
    .CLK(clk_i),
    .D(_018_),
    .Q(\rng_rd.ram_2[1] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _180_ (
    .CLK(clk_i),
    .D(_019_),
    .Q(\rng_rd.ram_2[2] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _181_ (
    .CLK(clk_i),
    .D(\rng_rd.wr_ff1 ),
    .Q(\rng_rd.wr_ff2 ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _182_ (
    .CLK(clk_i),
    .D(_020_),
    .Q(\rng_rd.ram_1[0] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _183_ (
    .CLK(clk_i),
    .D(_021_),
    .Q(\rng_rd.ram_1[1] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _184_ (
    .CLK(clk_i),
    .D(_022_),
    .Q(\rng_rd.ram_1[2] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _185_ (
    .CLK(clk_i),
    .D(_023_),
    .Q(num_to_send_o[0]),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _186_ (
    .CLK(clk_i),
    .D(_024_),
    .Q(num_to_send_o[1]),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _187_ (
    .CLK(clk_i),
    .D(_025_),
    .Q(num_to_send_o[2]),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _188_ (
    .CLK(clk_i),
    .D(\rng_rd.wr_ff2 ),
    .Q(\rng_rd.wr_ff2_d ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _189_ (
    .CLK(clk_i),
    .D(_026_),
    .Q(\num_i_bar[0] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _190_ (
    .CLK(clk_i),
    .D(_027_),
    .Q(\num_i_bar[1] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _191_ (
    .CLK(clk_i),
    .D(_028_),
    .Q(\num_i_bar[2] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _192_ (
    .CLK(clk_i),
    .D(_000_),
    .Q(req_num_again),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _193_ (
    .CLK(clk_i),
    .D(_029_),
    .Q(\rng_rd.ram_6[0] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _194_ (
    .CLK(clk_i),
    .D(_030_),
    .Q(\rng_rd.ram_6[1] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _195_ (
    .CLK(clk_i),
    .D(_031_),
    .Q(\rng_rd.ram_6[2] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _196_ (
    .CLK(clk_i),
    .D(_001_),
    .Q(\rng_rd.wr_pulse ),
    .RESET_B(rst_i)
  );
endmodule
