// Auto-generated by LibreLane
module rng_top(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk_i,
  input rst_i,
  input req_num_i,
  input wr_i,
  output[2:0] num_to_send_o
);
endmodule
