/* Generated by Yosys 0.59+0 (git sha1 26b51148a, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

module \$paramod$54156aeb88216e1ed0a79a36b33881dba9f19205\rng_control_path (clk_i, rst_i, req_num_i, state_o);
  input clk_i;
  wire clk_i;
  input rst_i;
  wire rst_i;
  input req_num_i;
  wire req_num_i;
  output state_o;
  wire state_o;
  wire _0_;
  wire next_state;
  \$adff  #(
    .ARST_POLARITY(32'd0),
    .ARST_VALUE(1'h0),
    .CLK_POLARITY(1'h1),
    .WIDTH(32'd1)
  ) next_state_reg /* _1_ */ (
    .ARST(rst_i),
    .CLK(clk_i),
    .D(_0_),
    .Q(next_state)
  );
  \$mux  #(
    .WIDTH(32'd1)
  ) _2_ (
    .A(1'h0),
    .B(1'h1),
    .S(req_num_i),
    .Y(_0_)
  );
  assign state_o = next_state;
endmodule

module \$paramod$54156aeb88216e1ed0a79a36b33881dba9f19205\rng_data_path (clk_i, rst_i, req_num_i, seed_sel_i, num_to_send_o);
  input clk_i;
  wire clk_i;
  input rst_i;
  wire rst_i;
  input req_num_i;
  wire req_num_i;
  input [1:0] seed_sel_i;
  wire [1:0] seed_sel_i;
  output [2:0] num_to_send_o;
  wire [2:0] num_to_send_o;
  wire [2:0] _00_;
  wire [2:0] _01_;
  wire [2:0] _02_;
  wire [2:0] _03_;
  wire [2:0] _04_;
  wire [2:0] _05_;
  wire [2:0] _06_;
  wire [2:0] _07_;
  wire [2:0] _08_;
  wire [2:0] _09_;
  wire [2:0] _10_;
  wire [2:0] _11_;
  wire [2:0] _12_;
  wire [2:0] _13_;
  wire [2:0] _14_;
  wire [2:0] _15_;
  wire [2:0] _16_;
  wire [2:0] _17_;
  wire [2:0] _18_;
  wire [2:0] _19_;
  wire [2:0] _20_;
  wire [2:0] _21_;
  wire [2:0] _22_;
  wire [2:0] _23_;
  wire [2:0] _24_;
  wire [2:0] _25_;
  wire [2:0] _26_;
  wire [2:0] _27_;
  wire [2:0] _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire [2:0] next_num;
  wire [2:0] \num_selector$func$../src/rng_data_path.v:153$123.num ;
  wire [2:0] num_to_send;
  \$adffe  #(
    .ARST_POLARITY(32'd0),
    .ARST_VALUE(3'h0),
    .CLK_POLARITY(32'd1),
    .EN_POLARITY(32'd1),
    .WIDTH(32'd3)
  ) _32_ (
    .ARST(rst_i),
    .CLK(clk_i),
    .D(_00_),
    .EN(req_num_i),
    .Q(next_num)
  );
  \$mux  #(
    .WIDTH(32'd3)
  ) _33_ (
    .A(_05_),
    .B(_06_),
    .S(num_to_send[2]),
    .Y(_01_)
  );
  \$mux  #(
    .WIDTH(32'd3)
  ) _34_ (
    .A(_07_),
    .B(_08_),
    .S(num_to_send[1]),
    .Y(_05_)
  );
  \$mux  #(
    .WIDTH(32'd3)
  ) _35_ (
    .A(_09_),
    .B(_10_),
    .S(num_to_send[1]),
    .Y(_06_)
  );
  \$mux  #(
    .WIDTH(32'd3)
  ) _36_ (
    .A(3'h7),
    .B(3'h6),
    .S(num_to_send[0]),
    .Y(_07_)
  );
  \$mux  #(
    .WIDTH(32'd3)
  ) _37_ (
    .A(3'h1),
    .B(3'h5),
    .S(num_to_send[0]),
    .Y(_08_)
  );
  \$mux  #(
    .WIDTH(32'd3)
  ) _38_ (
    .A(3'h0),
    .B(3'h2),
    .S(num_to_send[0]),
    .Y(_09_)
  );
  \$mux  #(
    .WIDTH(32'd3)
  ) _39_ (
    .A(3'h4),
    .B(3'h3),
    .S(num_to_send[0]),
    .Y(_10_)
  );
  \$mux  #(
    .WIDTH(32'd3)
  ) _40_ (
    .A(_11_),
    .B(_12_),
    .S(num_to_send[2]),
    .Y(_02_)
  );
  \$mux  #(
    .WIDTH(32'd3)
  ) _41_ (
    .A(_13_),
    .B(_14_),
    .S(num_to_send[1]),
    .Y(_11_)
  );
  \$mux  #(
    .WIDTH(32'd3)
  ) _42_ (
    .A(_15_),
    .B(_16_),
    .S(num_to_send[1]),
    .Y(_12_)
  );
  \$mux  #(
    .WIDTH(32'd3)
  ) _43_ (
    .A(3'h5),
    .B(3'h0),
    .S(num_to_send[0]),
    .Y(_13_)
  );
  \$mux  #(
    .WIDTH(32'd3)
  ) _44_ (
    .A(3'h7),
    .B(3'h1),
    .S(num_to_send[0]),
    .Y(_14_)
  );
  \$mux  #(
    .WIDTH(32'd3)
  ) _45_ (
    .A(3'h3),
    .B(3'h4),
    .S(num_to_send[0]),
    .Y(_15_)
  );
  \$mux  #(
    .WIDTH(32'd3)
  ) _46_ (
    .A(3'h2),
    .B(3'h6),
    .S(num_to_send[0]),
    .Y(_16_)
  );
  \$mux  #(
    .WIDTH(32'd3)
  ) _47_ (
    .A(_17_),
    .B(_18_),
    .S(num_to_send[2]),
    .Y(_03_)
  );
  \$mux  #(
    .WIDTH(32'd3)
  ) _48_ (
    .A(_19_),
    .B(_20_),
    .S(num_to_send[1]),
    .Y(_17_)
  );
  \$mux  #(
    .WIDTH(32'd3)
  ) _49_ (
    .A(_21_),
    .B(_22_),
    .S(num_to_send[1]),
    .Y(_18_)
  );
  \$mux  #(
    .WIDTH(32'd3)
  ) _50_ (
    .A(3'h2),
    .B(3'h3),
    .S(num_to_send[0]),
    .Y(_19_)
  );
  \$mux  #(
    .WIDTH(32'd3)
  ) _51_ (
    .A(3'h0),
    .B(3'h1),
    .S(num_to_send[0]),
    .Y(_20_)
  );
  \$mux  #(
    .WIDTH(32'd3)
  ) _52_ (
    .A(3'h5),
    .B(3'h4),
    .S(num_to_send[0]),
    .Y(_21_)
  );
  \$mux  #(
    .WIDTH(32'd3)
  ) _53_ (
    .A(3'h6),
    .B(3'h7),
    .S(num_to_send[0]),
    .Y(_22_)
  );
  \$mux  #(
    .WIDTH(32'd3)
  ) _54_ (
    .A(_23_),
    .B(_24_),
    .S(num_to_send[2]),
    .Y(_04_)
  );
  \$mux  #(
    .WIDTH(32'd3)
  ) _55_ (
    .A(_25_),
    .B(_26_),
    .S(num_to_send[1]),
    .Y(_23_)
  );
  \$mux  #(
    .WIDTH(32'd3)
  ) _56_ (
    .A(_27_),
    .B(_28_),
    .S(num_to_send[1]),
    .Y(_24_)
  );
  \$mux  #(
    .WIDTH(32'd3)
  ) _57_ (
    .A(3'h3),
    .B(3'h2),
    .S(num_to_send[0]),
    .Y(_25_)
  );
  \$mux  #(
    .WIDTH(32'd3)
  ) _58_ (
    .A(3'h1),
    .B(3'h6),
    .S(num_to_send[0]),
    .Y(_26_)
  );
  \$mux  #(
    .WIDTH(32'd3)
  ) _59_ (
    .A(3'h0),
    .B(3'h5),
    .S(num_to_send[0]),
    .Y(_27_)
  );
  \$mux  #(
    .WIDTH(32'd3)
  ) _60_ (
    .A(3'h4),
    .B(3'h7),
    .S(num_to_send[0]),
    .Y(_28_)
  );
  \$pmux  #(
    .S_WIDTH(32'd3),
    .WIDTH(32'd3)
  ) _61_ (
    .A(_04_),
    .B({ _01_, _02_, _03_ }),
    .S({ _31_, _30_, _29_ }),
    .Y(_00_)
  );
  \$eq  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd2),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd2),
    .Y_WIDTH(32'd1)
  ) _62_ (
    .A(seed_sel_i),
    .B(2'h2),
    .Y(_29_)
  );
  \$eq  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd2),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd2),
    .Y_WIDTH(32'd1)
  ) _63_ (
    .A(seed_sel_i),
    .B(2'h1),
    .Y(_30_)
  );
  \$logic_not  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd2),
    .Y_WIDTH(32'd1)
  ) _64_ (
    .A(seed_sel_i),
    .Y(_31_)
  );
  rng_data_path_counter inst (
    .clk_i(clk_i),
    .next_num_o(num_to_send),
    .req_num_i(req_num_i),
    .rst_i(rst_i)
  );
  assign \num_selector$func$../src/rng_data_path.v:153$123.num  = 3'hx;
  assign num_to_send_o = next_num;
endmodule

module \$paramod$54156aeb88216e1ed0a79a36b33881dba9f19205\rng_hs_dup_detector (clk_i, rst_i, req_num_i, data_i, wr_i, data_o, req_new_num_o);
  input clk_i;
  wire clk_i;
  input rst_i;
  wire rst_i;
  input req_num_i;
  wire req_num_i;
  input [2:0] data_i;
  wire [2:0] data_i;
  input wr_i;
  wire wr_i;
  output [2:0] data_o;
  wire [2:0] data_o;
  output req_new_num_o;
  wire req_new_num_o;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire approve;
  wire hit;
  wire [31:0] i;
  wire [2:0] \mem[0] ;
  wire [2:0] \mem[10] ;
  wire [2:0] \mem[11] ;
  wire [2:0] \mem[1] ;
  wire [2:0] \mem[2] ;
  wire [2:0] \mem[3] ;
  wire [2:0] \mem[4] ;
  wire [2:0] \mem[5] ;
  wire [2:0] \mem[6] ;
  wire [2:0] \mem[7] ;
  wire [2:0] \mem[8] ;
  wire [2:0] \mem[9] ;
  wire [11:0] vld;
  wire wr_ff1;
  wire wr_ff2;
  wire wr_ff2_d;
  wire wr_pulse;
  \$and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _037_ (
    .A(req_num_i),
    .B(hit),
    .Y(req_new_num_o)
  );
  \$and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _038_ (
    .A(wr_ff2),
    .B(_036_),
    .Y(_000_)
  );
  \$adffe  #(
    .ARST_POLARITY(32'd0),
    .ARST_VALUE(3'h0),
    .CLK_POLARITY(32'd1),
    .EN_POLARITY(32'd1),
    .WIDTH(32'd3)
  ) _039_ (
    .ARST(rst_i),
    .CLK(clk_i),
    .D(\mem[6] ),
    .EN(_025_),
    .Q(\mem[7] )
  );
  \$adffe  #(
    .ARST_POLARITY(32'd0),
    .ARST_VALUE(3'h0),
    .CLK_POLARITY(32'd1),
    .EN_POLARITY(32'd1),
    .WIDTH(32'd3)
  ) _040_ (
    .ARST(rst_i),
    .CLK(clk_i),
    .D(\mem[9] ),
    .EN(_025_),
    .Q(\mem[10] )
  );
  \$adffe  #(
    .ARST_POLARITY(32'd0),
    .ARST_VALUE(3'h0),
    .CLK_POLARITY(32'd1),
    .EN_POLARITY(32'd1),
    .WIDTH(32'd3)
  ) _041_ (
    .ARST(rst_i),
    .CLK(clk_i),
    .D(\mem[2] ),
    .EN(_025_),
    .Q(\mem[3] )
  );
  \$adffe  #(
    .ARST_POLARITY(32'd0),
    .ARST_VALUE(3'h0),
    .CLK_POLARITY(32'd1),
    .EN_POLARITY(32'd1),
    .WIDTH(32'd3)
  ) _042_ (
    .ARST(rst_i),
    .CLK(clk_i),
    .D(\mem[5] ),
    .EN(_025_),
    .Q(\mem[6] )
  );
  \$adffe  #(
    .ARST_POLARITY(32'd0),
    .ARST_VALUE(3'h0),
    .CLK_POLARITY(32'd1),
    .EN_POLARITY(32'd1),
    .WIDTH(32'd3)
  ) _043_ (
    .ARST(rst_i),
    .CLK(clk_i),
    .D(data_i),
    .EN(_025_),
    .Q(data_o)
  );
  \$adffe  #(
    .ARST_POLARITY(32'd0),
    .ARST_VALUE(3'h0),
    .CLK_POLARITY(32'd1),
    .EN_POLARITY(32'd1),
    .WIDTH(32'd3)
  ) _044_ (
    .ARST(rst_i),
    .CLK(clk_i),
    .D(\mem[10] ),
    .EN(_025_),
    .Q(\mem[11] )
  );
  \$adffe  #(
    .ARST_POLARITY(32'd0),
    .ARST_VALUE(1'h0),
    .CLK_POLARITY(32'd1),
    .EN_POLARITY(32'd1),
    .WIDTH(32'd1)
  ) \vld_reg[11]  /* _045_ */ (
    .ARST(rst_i),
    .CLK(clk_i),
    .D(vld[10]),
    .EN(_025_),
    .Q(vld[11])
  );
  \$adffe  #(
    .ARST_POLARITY(32'd0),
    .ARST_VALUE(1'h0),
    .CLK_POLARITY(32'd1),
    .EN_POLARITY(32'd1),
    .WIDTH(32'd1)
  ) \vld_reg[10]  /* _046_ */ (
    .ARST(rst_i),
    .CLK(clk_i),
    .D(vld[9]),
    .EN(_025_),
    .Q(vld[10])
  );
  \$adffe  #(
    .ARST_POLARITY(32'd0),
    .ARST_VALUE(1'h0),
    .CLK_POLARITY(32'd1),
    .EN_POLARITY(32'd1),
    .WIDTH(32'd1)
  ) \vld_reg[9]  /* _047_ */ (
    .ARST(rst_i),
    .CLK(clk_i),
    .D(vld[8]),
    .EN(_025_),
    .Q(vld[9])
  );
  \$adffe  #(
    .ARST_POLARITY(32'd0),
    .ARST_VALUE(1'h0),
    .CLK_POLARITY(32'd1),
    .EN_POLARITY(32'd1),
    .WIDTH(32'd1)
  ) \vld_reg[8]  /* _048_ */ (
    .ARST(rst_i),
    .CLK(clk_i),
    .D(vld[7]),
    .EN(_025_),
    .Q(vld[8])
  );
  \$adffe  #(
    .ARST_POLARITY(32'd0),
    .ARST_VALUE(1'h0),
    .CLK_POLARITY(32'd1),
    .EN_POLARITY(32'd1),
    .WIDTH(32'd1)
  ) \vld_reg[7]  /* _049_ */ (
    .ARST(rst_i),
    .CLK(clk_i),
    .D(vld[6]),
    .EN(_025_),
    .Q(vld[7])
  );
  \$adffe  #(
    .ARST_POLARITY(32'd0),
    .ARST_VALUE(1'h0),
    .CLK_POLARITY(32'd1),
    .EN_POLARITY(32'd1),
    .WIDTH(32'd1)
  ) \vld_reg[6]  /* _050_ */ (
    .ARST(rst_i),
    .CLK(clk_i),
    .D(vld[5]),
    .EN(_025_),
    .Q(vld[6])
  );
  \$adffe  #(
    .ARST_POLARITY(32'd0),
    .ARST_VALUE(1'h0),
    .CLK_POLARITY(32'd1),
    .EN_POLARITY(32'd1),
    .WIDTH(32'd1)
  ) \vld_reg[5]  /* _051_ */ (
    .ARST(rst_i),
    .CLK(clk_i),
    .D(vld[4]),
    .EN(_025_),
    .Q(vld[5])
  );
  \$adffe  #(
    .ARST_POLARITY(32'd0),
    .ARST_VALUE(1'h0),
    .CLK_POLARITY(32'd1),
    .EN_POLARITY(32'd1),
    .WIDTH(32'd1)
  ) \vld_reg[4]  /* _052_ */ (
    .ARST(rst_i),
    .CLK(clk_i),
    .D(vld[3]),
    .EN(_025_),
    .Q(vld[4])
  );
  \$adffe  #(
    .ARST_POLARITY(32'd0),
    .ARST_VALUE(1'h0),
    .CLK_POLARITY(32'd1),
    .EN_POLARITY(32'd1),
    .WIDTH(32'd1)
  ) \vld_reg[3]  /* _053_ */ (
    .ARST(rst_i),
    .CLK(clk_i),
    .D(vld[2]),
    .EN(_025_),
    .Q(vld[3])
  );
  \$adffe  #(
    .ARST_POLARITY(32'd0),
    .ARST_VALUE(1'h0),
    .CLK_POLARITY(32'd1),
    .EN_POLARITY(32'd1),
    .WIDTH(32'd1)
  ) \vld_reg[2]  /* _054_ */ (
    .ARST(rst_i),
    .CLK(clk_i),
    .D(vld[1]),
    .EN(_025_),
    .Q(vld[2])
  );
  \$adffe  #(
    .ARST_POLARITY(32'd0),
    .ARST_VALUE(1'h0),
    .CLK_POLARITY(32'd1),
    .EN_POLARITY(32'd1),
    .WIDTH(32'd1)
  ) \vld_reg[0]  /* _055_ */ (
    .ARST(rst_i),
    .CLK(clk_i),
    .D(1'h1),
    .EN(_025_),
    .Q(vld[0])
  );
  \$adffe  #(
    .ARST_POLARITY(32'd0),
    .ARST_VALUE(1'h0),
    .CLK_POLARITY(32'd1),
    .EN_POLARITY(32'd1),
    .WIDTH(32'd1)
  ) \vld_reg[1]  /* _056_ */ (
    .ARST(rst_i),
    .CLK(clk_i),
    .D(vld[0]),
    .EN(_025_),
    .Q(vld[1])
  );
  \$adffe  #(
    .ARST_POLARITY(32'd0),
    .ARST_VALUE(3'h0),
    .CLK_POLARITY(32'd1),
    .EN_POLARITY(32'd1),
    .WIDTH(32'd3)
  ) _057_ (
    .ARST(rst_i),
    .CLK(clk_i),
    .D(\mem[3] ),
    .EN(_025_),
    .Q(\mem[4] )
  );
  \$adffe  #(
    .ARST_POLARITY(32'd0),
    .ARST_VALUE(3'h0),
    .CLK_POLARITY(32'd1),
    .EN_POLARITY(32'd1),
    .WIDTH(32'd3)
  ) _058_ (
    .ARST(rst_i),
    .CLK(clk_i),
    .D(\mem[8] ),
    .EN(_025_),
    .Q(\mem[9] )
  );
  \$adffe  #(
    .ARST_POLARITY(32'd0),
    .ARST_VALUE(3'h0),
    .CLK_POLARITY(32'd1),
    .EN_POLARITY(32'd1),
    .WIDTH(32'd3)
  ) _059_ (
    .ARST(rst_i),
    .CLK(clk_i),
    .D(\mem[7] ),
    .EN(_025_),
    .Q(\mem[8] )
  );
  \$adffe  #(
    .ARST_POLARITY(32'd0),
    .ARST_VALUE(3'h0),
    .CLK_POLARITY(32'd1),
    .EN_POLARITY(32'd1),
    .WIDTH(32'd3)
  ) _060_ (
    .ARST(rst_i),
    .CLK(clk_i),
    .D(data_o),
    .EN(_025_),
    .Q(\mem[1] )
  );
  \$adffe  #(
    .ARST_POLARITY(32'd0),
    .ARST_VALUE(3'h0),
    .CLK_POLARITY(32'd1),
    .EN_POLARITY(32'd1),
    .WIDTH(32'd3)
  ) _061_ (
    .ARST(rst_i),
    .CLK(clk_i),
    .D(\mem[4] ),
    .EN(_025_),
    .Q(\mem[5] )
  );
  \$adffe  #(
    .ARST_POLARITY(32'd0),
    .ARST_VALUE(3'h0),
    .CLK_POLARITY(32'd1),
    .EN_POLARITY(32'd1),
    .WIDTH(32'd3)
  ) _062_ (
    .ARST(rst_i),
    .CLK(clk_i),
    .D(\mem[1] ),
    .EN(_025_),
    .Q(\mem[2] )
  );
  \$eq  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd3),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd3),
    .Y_WIDTH(32'd1)
  ) _063_ (
    .A(data_i),
    .B(data_o),
    .Y(_001_)
  );
  \$eq  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd3),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd3),
    .Y_WIDTH(32'd1)
  ) _064_ (
    .A(data_i),
    .B(\mem[1] ),
    .Y(_002_)
  );
  \$eq  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd3),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd3),
    .Y_WIDTH(32'd1)
  ) _065_ (
    .A(data_i),
    .B(\mem[2] ),
    .Y(_003_)
  );
  \$eq  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd3),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd3),
    .Y_WIDTH(32'd1)
  ) _066_ (
    .A(data_i),
    .B(\mem[3] ),
    .Y(_004_)
  );
  \$eq  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd3),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd3),
    .Y_WIDTH(32'd1)
  ) _067_ (
    .A(data_i),
    .B(\mem[4] ),
    .Y(_005_)
  );
  \$eq  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd3),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd3),
    .Y_WIDTH(32'd1)
  ) _068_ (
    .A(data_i),
    .B(\mem[5] ),
    .Y(_006_)
  );
  \$eq  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd3),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd3),
    .Y_WIDTH(32'd1)
  ) _069_ (
    .A(data_i),
    .B(\mem[6] ),
    .Y(_007_)
  );
  \$eq  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd3),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd3),
    .Y_WIDTH(32'd1)
  ) _070_ (
    .A(data_i),
    .B(\mem[7] ),
    .Y(_008_)
  );
  \$eq  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd3),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd3),
    .Y_WIDTH(32'd1)
  ) _071_ (
    .A(data_i),
    .B(\mem[8] ),
    .Y(_009_)
  );
  \$eq  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd3),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd3),
    .Y_WIDTH(32'd1)
  ) _072_ (
    .A(data_i),
    .B(\mem[9] ),
    .Y(_010_)
  );
  \$eq  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd3),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd3),
    .Y_WIDTH(32'd1)
  ) _073_ (
    .A(data_i),
    .B(\mem[10] ),
    .Y(_011_)
  );
  \$eq  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd3),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd3),
    .Y_WIDTH(32'd1)
  ) _074_ (
    .A(data_i),
    .B(\mem[11] ),
    .Y(_012_)
  );
  \$logic_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _075_ (
    .A(vld[0]),
    .B(_001_),
    .Y(_013_)
  );
  \$logic_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _076_ (
    .A(vld[1]),
    .B(_002_),
    .Y(_014_)
  );
  \$logic_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _077_ (
    .A(vld[2]),
    .B(_003_),
    .Y(_015_)
  );
  \$logic_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _078_ (
    .A(vld[3]),
    .B(_004_),
    .Y(_016_)
  );
  \$logic_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _079_ (
    .A(vld[4]),
    .B(_005_),
    .Y(_017_)
  );
  \$logic_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _080_ (
    .A(vld[5]),
    .B(_006_),
    .Y(_018_)
  );
  \$logic_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _081_ (
    .A(vld[6]),
    .B(_007_),
    .Y(_019_)
  );
  \$logic_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _082_ (
    .A(vld[7]),
    .B(_008_),
    .Y(_020_)
  );
  \$logic_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _083_ (
    .A(vld[8]),
    .B(_009_),
    .Y(_021_)
  );
  \$logic_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _084_ (
    .A(vld[9]),
    .B(_010_),
    .Y(_022_)
  );
  \$logic_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _085_ (
    .A(vld[10]),
    .B(_011_),
    .Y(_023_)
  );
  \$logic_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _086_ (
    .A(vld[11]),
    .B(_012_),
    .Y(_024_)
  );
  \$logic_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _087_ (
    .A(approve),
    .B(wr_pulse),
    .Y(_025_)
  );
  \$logic_or  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _088_ (
    .A(_035_),
    .B(_022_),
    .Y(_026_)
  );
  \$logic_or  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _089_ (
    .A(_026_),
    .B(_023_),
    .Y(_027_)
  );
  \$logic_or  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _090_ (
    .A(_027_),
    .B(_024_),
    .Y(hit)
  );
  \$logic_or  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _091_ (
    .A(_013_),
    .B(_014_),
    .Y(_028_)
  );
  \$logic_or  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _092_ (
    .A(_028_),
    .B(_015_),
    .Y(_029_)
  );
  \$logic_or  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _093_ (
    .A(_029_),
    .B(_016_),
    .Y(_030_)
  );
  \$logic_or  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _094_ (
    .A(_030_),
    .B(_017_),
    .Y(_031_)
  );
  \$logic_or  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _095_ (
    .A(_031_),
    .B(_018_),
    .Y(_032_)
  );
  \$logic_or  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _096_ (
    .A(_032_),
    .B(_019_),
    .Y(_033_)
  );
  \$logic_or  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _097_ (
    .A(_033_),
    .B(_020_),
    .Y(_034_)
  );
  \$logic_or  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _098_ (
    .A(_034_),
    .B(_021_),
    .Y(_035_)
  );
  \$not  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _099_ (
    .A(hit),
    .Y(approve)
  );
  \$not  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _100_ (
    .A(wr_ff2_d),
    .Y(_036_)
  );
  \$adff  #(
    .ARST_POLARITY(32'd0),
    .ARST_VALUE(1'h0),
    .CLK_POLARITY(1'h1),
    .WIDTH(32'd1)
  ) wr_ff1_reg /* _101_ */ (
    .ARST(rst_i),
    .CLK(clk_i),
    .D(wr_i),
    .Q(wr_ff1)
  );
  \$adff  #(
    .ARST_POLARITY(32'd0),
    .ARST_VALUE(1'h0),
    .CLK_POLARITY(1'h1),
    .WIDTH(32'd1)
  ) wr_ff2_reg /* _102_ */ (
    .ARST(rst_i),
    .CLK(clk_i),
    .D(wr_ff1),
    .Q(wr_ff2)
  );
  \$adff  #(
    .ARST_POLARITY(32'd0),
    .ARST_VALUE(1'h0),
    .CLK_POLARITY(1'h1),
    .WIDTH(32'd1)
  ) wr_ff2_d_reg /* _103_ */ (
    .ARST(rst_i),
    .CLK(clk_i),
    .D(wr_ff2),
    .Q(wr_ff2_d)
  );
  \$adff  #(
    .ARST_POLARITY(32'd0),
    .ARST_VALUE(1'h0),
    .CLK_POLARITY(1'h1),
    .WIDTH(32'd1)
  ) wr_pulse_reg /* _104_ */ (
    .ARST(rst_i),
    .CLK(clk_i),
    .D(_000_),
    .Q(wr_pulse)
  );
  assign i = 32'd12;
  assign \mem[0]  = data_o;
endmodule

module \$paramod$54156aeb88216e1ed0a79a36b33881dba9f19205\rng_selector (clk_i, start_i, rst_i, seed_sel_o);
  input clk_i;
  wire clk_i;
  input start_i;
  wire start_i;
  input rst_i;
  wire rst_i;
  output [1:0] seed_sel_o;
  wire [1:0] seed_sel_o;
  wire [1:0] _0_;
  wire [1:0] seed_s;
  \$add  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd2),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd2)
  ) _1_ (
    .A(seed_s),
    .B(1'h1),
    .Y(_0_)
  );
  \$adff  #(
    .ARST_POLARITY(32'd0),
    .ARST_VALUE(2'h0),
    .CLK_POLARITY(1'h1),
    .WIDTH(32'd2)
  ) _2_ (
    .ARST(rst_i),
    .CLK(clk_i),
    .D(_0_),
    .Q(seed_s)
  );
  assign seed_sel_o = seed_s;
endmodule

module rng_data_path_counter(clk_i, rst_i, req_num_i, next_num_o);
  input clk_i;
  wire clk_i;
  input rst_i;
  wire rst_i;
  input req_num_i;
  wire req_num_i;
  output [2:0] next_num_o;
  wire [2:0] next_num_o;
  wire [31:0] _0_;
  wire _1_;
  wire [2:0] _2_;
  wire [2:0] num_counter;
  \$add  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd3),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd32),
    .Y_WIDTH(32'd32)
  ) _3_ (
    .A(num_counter),
    .B(32'd1),
    .Y(_0_)
  );
  \$adffe  #(
    .ARST_POLARITY(32'd0),
    .ARST_VALUE(3'h0),
    .CLK_POLARITY(32'd1),
    .EN_POLARITY(32'd1),
    .WIDTH(32'd3)
  ) _4_ (
    .ARST(rst_i),
    .CLK(clk_i),
    .D(_2_),
    .EN(req_num_i),
    .Q(num_counter)
  );
  \$eq  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd3),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd3),
    .Y_WIDTH(32'd1)
  ) _5_ (
    .A(num_counter),
    .B(3'h7),
    .Y(_1_)
  );
  \$mux  #(
    .WIDTH(32'd3)
  ) _6_ (
    .A(_0_[2:0]),
    .B(3'h0),
    .S(_1_),
    .Y(_2_)
  );
  assign next_num_o = num_counter;
endmodule

module rng_top(clk_i, start_i, rst_i, req_num_i, wr_i, num_to_send_o);
  input clk_i;
  wire clk_i;
  input start_i;
  wire start_i;
  input rst_i;
  wire rst_i;
  input req_num_i;
  wire req_num_i;
  input wr_i;
  wire wr_i;
  output [2:0] num_to_send_o;
  wire [2:0] num_to_send_o;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire [2:0] _139_;
  wire [1:0] _140_;
  wire [1:0] _141_;
  wire [2:0] num_i_bar;
  wire req_num;
  wire [2:0] \rng_dp.inst.next_num_o ;
  wire [1:0] \rng_dp.seed_sel_i ;
  wire [2:0] \rng_rd.mem[10] ;
  wire [2:0] \rng_rd.mem[11] ;
  wire [2:0] \rng_rd.mem[1] ;
  wire [2:0] \rng_rd.mem[2] ;
  wire [2:0] \rng_rd.mem[3] ;
  wire [2:0] \rng_rd.mem[4] ;
  wire [2:0] \rng_rd.mem[5] ;
  wire [2:0] \rng_rd.mem[6] ;
  wire [2:0] \rng_rd.mem[7] ;
  wire [2:0] \rng_rd.mem[8] ;
  wire [2:0] \rng_rd.mem[9] ;
  wire [11:0] \rng_rd.vld ;
  wire \rng_rd.wr_ff1 ;
  wire \rng_rd.wr_ff2 ;
  wire \rng_rd.wr_ff2_d ;
  wire \rng_rd.wr_pulse ;
  \$_NOT_  _142_ (
    .A(\rng_dp.inst.next_num_o [2]),
    .Y(_115_)
  );
  \$_NOT_  _143_ (
    .A(\rng_dp.seed_sel_i [0]),
    .Y(_140_[0])
  );
  \$_NOT_  _144_ (
    .A(\rng_dp.inst.next_num_o [1]),
    .Y(_116_)
  );
  \$_NOT_  _145_ (
    .A(\rng_dp.inst.next_num_o [0]),
    .Y(_000_)
  );
  \$_NOT_  _146_ (
    .A(num_i_bar[0]),
    .Y(_117_)
  );
  \$_NOT_  _147_ (
    .A(\rng_rd.mem[11] [2]),
    .Y(_118_)
  );
  \$_NOT_  _148_ (
    .A(\rng_rd.wr_pulse ),
    .Y(_119_)
  );
  \$_NOT_  _149_ (
    .A(\rng_rd.wr_ff2_d ),
    .Y(_120_)
  );
  \$_NOR_  _150_ (
    .A(_140_[0]),
    .B(\rng_dp.seed_sel_i [1]),
    .Y(_121_)
  );
  \$_AND_  _151_ (
    .A(_140_[0]),
    .B(\rng_dp.seed_sel_i [1]),
    .Y(_122_)
  );
  \$_OR_  _152_ (
    .A(_121_),
    .B(_122_),
    .Y(_141_[1])
  );
  \$_XNOR_  _153_ (
    .A(num_i_bar[2]),
    .B(num_to_send_o[2]),
    .Y(_123_)
  );
  \$_XNOR_  _154_ (
    .A(num_i_bar[0]),
    .B(num_to_send_o[0]),
    .Y(_124_)
  );
  \$_AND_  _155_ (
    .A(_123_),
    .B(_124_),
    .Y(_125_)
  );
  \$_XNOR_  _156_ (
    .A(num_i_bar[1]),
    .B(num_to_send_o[1]),
    .Y(_126_)
  );
  \$_AND_  _157_ (
    .A(\rng_rd.vld [0]),
    .B(_126_),
    .Y(_127_)
  );
  \$_NAND_  _158_ (
    .A(_125_),
    .B(_127_),
    .Y(_128_)
  );
  \$_XNOR_  _159_ (
    .A(num_i_bar[1]),
    .B(\rng_rd.mem[10] [1]),
    .Y(_129_)
  );
  \$_XNOR_  _160_ (
    .A(num_i_bar[0]),
    .B(\rng_rd.mem[10] [0]),
    .Y(_130_)
  );
  \$_AND_  _161_ (
    .A(_129_),
    .B(_130_),
    .Y(_131_)
  );
  \$_XNOR_  _162_ (
    .A(num_i_bar[2]),
    .B(\rng_rd.mem[10] [2]),
    .Y(_132_)
  );
  \$_AND_  _163_ (
    .A(\rng_rd.vld [10]),
    .B(_132_),
    .Y(_133_)
  );
  \$_NAND_  _164_ (
    .A(_131_),
    .B(_133_),
    .Y(_134_)
  );
  \$_AND_  _165_ (
    .A(_128_),
    .B(_134_),
    .Y(_135_)
  );
  \$_NAND_  _166_ (
    .A(_117_),
    .B(\rng_rd.mem[11] [0]),
    .Y(_136_)
  );
  \$_OR_  _167_ (
    .A(_117_),
    .B(\rng_rd.mem[11] [0]),
    .Y(_137_)
  );
  \$_NAND_  _168_ (
    .A(num_i_bar[2]),
    .B(_118_),
    .Y(_138_)
  );
  \$_OR_  _169_ (
    .A(num_i_bar[2]),
    .B(_118_),
    .Y(_005_)
  );
  \$_XNOR_  _170_ (
    .A(num_i_bar[1]),
    .B(\rng_rd.mem[11] [1]),
    .Y(_006_)
  );
  \$_AND_  _171_ (
    .A(_005_),
    .B(_006_),
    .Y(_007_)
  );
  \$_AND_  _172_ (
    .A(_137_),
    .B(_138_),
    .Y(_008_)
  );
  \$_AND_  _173_ (
    .A(\rng_rd.vld [11]),
    .B(_136_),
    .Y(_009_)
  );
  \$_AND_  _174_ (
    .A(_008_),
    .B(_009_),
    .Y(_010_)
  );
  \$_NAND_  _175_ (
    .A(_007_),
    .B(_010_),
    .Y(_011_)
  );
  \$_XNOR_  _176_ (
    .A(num_i_bar[2]),
    .B(\rng_rd.mem[7] [2]),
    .Y(_012_)
  );
  \$_XNOR_  _177_ (
    .A(num_i_bar[1]),
    .B(\rng_rd.mem[7] [1]),
    .Y(_013_)
  );
  \$_AND_  _178_ (
    .A(_012_),
    .B(_013_),
    .Y(_014_)
  );
  \$_XNOR_  _179_ (
    .A(num_i_bar[0]),
    .B(\rng_rd.mem[7] [0]),
    .Y(_015_)
  );
  \$_AND_  _180_ (
    .A(\rng_rd.vld [7]),
    .B(_015_),
    .Y(_016_)
  );
  \$_NAND_  _181_ (
    .A(_014_),
    .B(_016_),
    .Y(_017_)
  );
  \$_AND_  _182_ (
    .A(_011_),
    .B(_017_),
    .Y(_018_)
  );
  \$_AND_  _183_ (
    .A(_135_),
    .B(_018_),
    .Y(_019_)
  );
  \$_XNOR_  _184_ (
    .A(num_i_bar[2]),
    .B(\rng_rd.mem[9] [2]),
    .Y(_020_)
  );
  \$_XNOR_  _185_ (
    .A(num_i_bar[1]),
    .B(\rng_rd.mem[9] [1]),
    .Y(_021_)
  );
  \$_XNOR_  _186_ (
    .A(num_i_bar[0]),
    .B(\rng_rd.mem[9] [0]),
    .Y(_022_)
  );
  \$_AND_  _187_ (
    .A(_020_),
    .B(_022_),
    .Y(_023_)
  );
  \$_AND_  _188_ (
    .A(\rng_rd.vld [9]),
    .B(_023_),
    .Y(_024_)
  );
  \$_NAND_  _189_ (
    .A(_021_),
    .B(_024_),
    .Y(_025_)
  );
  \$_XNOR_  _190_ (
    .A(num_i_bar[2]),
    .B(\rng_rd.mem[5] [2]),
    .Y(_026_)
  );
  \$_XNOR_  _191_ (
    .A(num_i_bar[1]),
    .B(\rng_rd.mem[5] [1]),
    .Y(_027_)
  );
  \$_XNOR_  _192_ (
    .A(num_i_bar[0]),
    .B(\rng_rd.mem[5] [0]),
    .Y(_028_)
  );
  \$_AND_  _193_ (
    .A(_026_),
    .B(_028_),
    .Y(_029_)
  );
  \$_AND_  _194_ (
    .A(\rng_rd.vld [5]),
    .B(_029_),
    .Y(_030_)
  );
  \$_NAND_  _195_ (
    .A(_027_),
    .B(_030_),
    .Y(_031_)
  );
  \$_AND_  _196_ (
    .A(_025_),
    .B(_031_),
    .Y(_032_)
  );
  \$_XNOR_  _197_ (
    .A(num_i_bar[2]),
    .B(\rng_rd.mem[4] [2]),
    .Y(_033_)
  );
  \$_XNOR_  _198_ (
    .A(num_i_bar[1]),
    .B(\rng_rd.mem[4] [1]),
    .Y(_034_)
  );
  \$_XNOR_  _199_ (
    .A(num_i_bar[0]),
    .B(\rng_rd.mem[4] [0]),
    .Y(_035_)
  );
  \$_AND_  _200_ (
    .A(_034_),
    .B(_035_),
    .Y(_036_)
  );
  \$_AND_  _201_ (
    .A(\rng_rd.vld [4]),
    .B(_033_),
    .Y(_037_)
  );
  \$_NAND_  _202_ (
    .A(_036_),
    .B(_037_),
    .Y(_038_)
  );
  \$_XNOR_  _203_ (
    .A(num_i_bar[1]),
    .B(\rng_rd.mem[8] [1]),
    .Y(_039_)
  );
  \$_XNOR_  _204_ (
    .A(num_i_bar[2]),
    .B(\rng_rd.mem[8] [2]),
    .Y(_040_)
  );
  \$_AND_  _205_ (
    .A(_039_),
    .B(_040_),
    .Y(_041_)
  );
  \$_XNOR_  _206_ (
    .A(num_i_bar[0]),
    .B(\rng_rd.mem[8] [0]),
    .Y(_042_)
  );
  \$_AND_  _207_ (
    .A(\rng_rd.vld [8]),
    .B(_042_),
    .Y(_043_)
  );
  \$_NAND_  _208_ (
    .A(_041_),
    .B(_043_),
    .Y(_044_)
  );
  \$_AND_  _209_ (
    .A(_038_),
    .B(_044_),
    .Y(_045_)
  );
  \$_AND_  _210_ (
    .A(_032_),
    .B(_045_),
    .Y(_046_)
  );
  \$_XNOR_  _211_ (
    .A(num_i_bar[2]),
    .B(\rng_rd.mem[6] [2]),
    .Y(_047_)
  );
  \$_XNOR_  _212_ (
    .A(num_i_bar[0]),
    .B(\rng_rd.mem[6] [0]),
    .Y(_048_)
  );
  \$_XNOR_  _213_ (
    .A(num_i_bar[1]),
    .B(\rng_rd.mem[6] [1]),
    .Y(_049_)
  );
  \$_AND_  _214_ (
    .A(_048_),
    .B(_049_),
    .Y(_050_)
  );
  \$_AND_  _215_ (
    .A(\rng_rd.vld [6]),
    .B(_047_),
    .Y(_051_)
  );
  \$_NAND_  _216_ (
    .A(_050_),
    .B(_051_),
    .Y(_052_)
  );
  \$_XNOR_  _217_ (
    .A(num_i_bar[2]),
    .B(\rng_rd.mem[1] [2]),
    .Y(_053_)
  );
  \$_XNOR_  _218_ (
    .A(num_i_bar[0]),
    .B(\rng_rd.mem[1] [0]),
    .Y(_054_)
  );
  \$_XNOR_  _219_ (
    .A(num_i_bar[1]),
    .B(\rng_rd.mem[1] [1]),
    .Y(_055_)
  );
  \$_AND_  _220_ (
    .A(\rng_rd.vld [1]),
    .B(_053_),
    .Y(_056_)
  );
  \$_AND_  _221_ (
    .A(_055_),
    .B(_056_),
    .Y(_057_)
  );
  \$_NAND_  _222_ (
    .A(_054_),
    .B(_057_),
    .Y(_058_)
  );
  \$_AND_  _223_ (
    .A(_052_),
    .B(_058_),
    .Y(_059_)
  );
  \$_XNOR_  _224_ (
    .A(num_i_bar[2]),
    .B(\rng_rd.mem[2] [2]),
    .Y(_060_)
  );
  \$_XNOR_  _225_ (
    .A(num_i_bar[0]),
    .B(\rng_rd.mem[2] [0]),
    .Y(_061_)
  );
  \$_XNOR_  _226_ (
    .A(num_i_bar[1]),
    .B(\rng_rd.mem[2] [1]),
    .Y(_062_)
  );
  \$_AND_  _227_ (
    .A(_061_),
    .B(_062_),
    .Y(_063_)
  );
  \$_AND_  _228_ (
    .A(\rng_rd.vld [2]),
    .B(_060_),
    .Y(_064_)
  );
  \$_NAND_  _229_ (
    .A(_063_),
    .B(_064_),
    .Y(_065_)
  );
  \$_XNOR_  _230_ (
    .A(num_i_bar[2]),
    .B(\rng_rd.mem[3] [2]),
    .Y(_066_)
  );
  \$_XNOR_  _231_ (
    .A(num_i_bar[0]),
    .B(\rng_rd.mem[3] [0]),
    .Y(_067_)
  );
  \$_XNOR_  _232_ (
    .A(num_i_bar[1]),
    .B(\rng_rd.mem[3] [1]),
    .Y(_068_)
  );
  \$_AND_  _233_ (
    .A(_067_),
    .B(_068_),
    .Y(_069_)
  );
  \$_AND_  _234_ (
    .A(\rng_rd.vld [3]),
    .B(_066_),
    .Y(_070_)
  );
  \$_NAND_  _235_ (
    .A(_069_),
    .B(_070_),
    .Y(_071_)
  );
  \$_AND_  _236_ (
    .A(_065_),
    .B(_071_),
    .Y(_072_)
  );
  \$_AND_  _237_ (
    .A(_059_),
    .B(_072_),
    .Y(_073_)
  );
  \$_AND_  _238_ (
    .A(_046_),
    .B(_073_),
    .Y(_074_)
  );
  \$_NAND_  _239_ (
    .A(_019_),
    .B(_074_),
    .Y(_075_)
  );
  \$_AND_  _240_ (
    .A(req_num),
    .B(_075_),
    .Y(_076_)
  );
  \$_OR_  _241_ (
    .A(req_num_i),
    .B(_076_),
    .Y(req_num)
  );
  \$_AND_  _242_ (
    .A(\rng_rd.wr_ff2 ),
    .B(_120_),
    .Y(_003_)
  );
  \$_NOR_  _243_ (
    .A(_119_),
    .B(_075_),
    .Y(_004_)
  );
  \$_NAND_  _244_ (
    .A(_116_),
    .B(\rng_dp.inst.next_num_o [0]),
    .Y(_077_)
  );
  \$_AND_  _245_ (
    .A(\rng_dp.inst.next_num_o [1]),
    .B(_000_),
    .Y(_078_)
  );
  \$_XOR_  _246_ (
    .A(\rng_dp.inst.next_num_o [1]),
    .B(\rng_dp.inst.next_num_o [0]),
    .Y(_001_)
  );
  \$_NAND_  _247_ (
    .A(\rng_dp.inst.next_num_o [2]),
    .B(\rng_dp.inst.next_num_o [0]),
    .Y(_079_)
  );
  \$_NAND_  _248_ (
    .A(\rng_dp.inst.next_num_o [2]),
    .B(\rng_dp.inst.next_num_o [1]),
    .Y(_080_)
  );
  \$_OR_  _249_ (
    .A(\rng_dp.inst.next_num_o [2]),
    .B(\rng_dp.inst.next_num_o [0]),
    .Y(_081_)
  );
  \$_MUX_  _250_ (
    .A(\rng_dp.inst.next_num_o [2]),
    .B(_079_),
    .S(\rng_dp.inst.next_num_o [1]),
    .Y(_082_)
  );
  \$_AND_  _251_ (
    .A(_081_),
    .B(_082_),
    .Y(_002_)
  );
  \$_NAND_  _252_ (
    .A(_079_),
    .B(_081_),
    .Y(_083_)
  );
  \$_NOR_  _253_ (
    .A(\rng_dp.seed_sel_i [0]),
    .B(\rng_dp.seed_sel_i [1]),
    .Y(_084_)
  );
  \$_AND_  _254_ (
    .A(\rng_dp.seed_sel_i [0]),
    .B(\rng_dp.seed_sel_i [1]),
    .Y(_085_)
  );
  \$_NAND_  _255_ (
    .A(_083_),
    .B(_085_),
    .Y(_086_)
  );
  \$_NAND_  _256_ (
    .A(\rng_dp.inst.next_num_o [2]),
    .B(_001_),
    .Y(_087_)
  );
  \$_AND_  _257_ (
    .A(_122_),
    .B(_087_),
    .Y(_088_)
  );
  \$_NAND_  _258_ (
    .A(_081_),
    .B(_088_),
    .Y(_089_)
  );
  \$_MUX_  _259_ (
    .A(_115_),
    .B(\rng_dp.inst.next_num_o [1]),
    .S(\rng_dp.inst.next_num_o [0]),
    .Y(_090_)
  );
  \$_NAND_  _260_ (
    .A(_084_),
    .B(_090_),
    .Y(_091_)
  );
  \$_AND_  _261_ (
    .A(_121_),
    .B(_077_),
    .Y(_092_)
  );
  \$_NAND_  _262_ (
    .A(_080_),
    .B(_092_),
    .Y(_093_)
  );
  \$_AND_  _263_ (
    .A(_091_),
    .B(_093_),
    .Y(_094_)
  );
  \$_AND_  _264_ (
    .A(_089_),
    .B(_094_),
    .Y(_095_)
  );
  \$_NAND_  _265_ (
    .A(_086_),
    .B(_095_),
    .Y(_139_[0])
  );
  \$_MUX_  _266_ (
    .A(_115_),
    .B(\rng_dp.inst.next_num_o [0]),
    .S(\rng_dp.inst.next_num_o [1]),
    .Y(_096_)
  );
  \$_NAND_  _267_ (
    .A(_085_),
    .B(_096_),
    .Y(_097_)
  );
  \$_MUX_  _268_ (
    .A(_116_),
    .B(\rng_dp.inst.next_num_o [0]),
    .S(\rng_dp.inst.next_num_o [2]),
    .Y(_098_)
  );
  \$_NAND_  _269_ (
    .A(_084_),
    .B(_098_),
    .Y(_099_)
  );
  \$_OR_  _270_ (
    .A(\rng_dp.inst.next_num_o [2]),
    .B(_078_),
    .Y(_100_)
  );
  \$_NAND_  _271_ (
    .A(_092_),
    .B(_100_),
    .Y(_101_)
  );
  \$_XNOR_  _272_ (
    .A(\rng_dp.inst.next_num_o [2]),
    .B(\rng_dp.inst.next_num_o [1]),
    .Y(_102_)
  );
  \$_NAND_  _273_ (
    .A(_122_),
    .B(_102_),
    .Y(_103_)
  );
  \$_AND_  _274_ (
    .A(_097_),
    .B(_101_),
    .Y(_104_)
  );
  \$_AND_  _275_ (
    .A(_099_),
    .B(_103_),
    .Y(_105_)
  );
  \$_NAND_  _276_ (
    .A(_104_),
    .B(_105_),
    .Y(_139_[1])
  );
  \$_NAND_  _277_ (
    .A(\rng_dp.inst.next_num_o [1]),
    .B(_081_),
    .Y(_106_)
  );
  \$_NAND_  _278_ (
    .A(_079_),
    .B(_106_),
    .Y(_107_)
  );
  \$_NAND_  _279_ (
    .A(_085_),
    .B(_107_),
    .Y(_108_)
  );
  \$_XNOR_  _280_ (
    .A(\rng_dp.inst.next_num_o [2]),
    .B(_078_),
    .Y(_109_)
  );
  \$_NAND_  _281_ (
    .A(_084_),
    .B(_109_),
    .Y(_110_)
  );
  \$_NAND_  _282_ (
    .A(\rng_dp.inst.next_num_o [2]),
    .B(_122_),
    .Y(_111_)
  );
  \$_NAND_  _283_ (
    .A(_121_),
    .B(_083_),
    .Y(_112_)
  );
  \$_AND_  _284_ (
    .A(_111_),
    .B(_112_),
    .Y(_113_)
  );
  \$_AND_  _285_ (
    .A(_110_),
    .B(_113_),
    .Y(_114_)
  );
  \$_NAND_  _286_ (
    .A(_108_),
    .B(_114_),
    .Y(_139_[2])
  );
  \$_DFFE_PN0P_  \rng_rd.mem_reg[1][0]  /* _287_ */ (
    .C(clk_i),
    .D(num_to_send_o[0]),
    .E(_004_),
    .Q(\rng_rd.mem[1] [0]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \rng_rd.mem_reg[1][1]  /* _288_ */ (
    .C(clk_i),
    .D(num_to_send_o[1]),
    .E(_004_),
    .Q(\rng_rd.mem[1] [1]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \rng_rd.mem_reg[1][2]  /* _289_ */ (
    .C(clk_i),
    .D(num_to_send_o[2]),
    .E(_004_),
    .Q(\rng_rd.mem[1] [2]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \rng_rd.mem_reg[8][0]  /* _290_ */ (
    .C(clk_i),
    .D(\rng_rd.mem[7] [0]),
    .E(_004_),
    .Q(\rng_rd.mem[8] [0]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \rng_rd.mem_reg[8][1]  /* _291_ */ (
    .C(clk_i),
    .D(\rng_rd.mem[7] [1]),
    .E(_004_),
    .Q(\rng_rd.mem[8] [1]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \rng_rd.mem_reg[8][2]  /* _292_ */ (
    .C(clk_i),
    .D(\rng_rd.mem[7] [2]),
    .E(_004_),
    .Q(\rng_rd.mem[8] [2]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \rng_rd.mem_reg[9][0]  /* _293_ */ (
    .C(clk_i),
    .D(\rng_rd.mem[8] [0]),
    .E(_004_),
    .Q(\rng_rd.mem[9] [0]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \rng_rd.mem_reg[9][1]  /* _294_ */ (
    .C(clk_i),
    .D(\rng_rd.mem[8] [1]),
    .E(_004_),
    .Q(\rng_rd.mem[9] [1]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \rng_rd.mem_reg[9][2]  /* _295_ */ (
    .C(clk_i),
    .D(\rng_rd.mem[8] [2]),
    .E(_004_),
    .Q(\rng_rd.mem[9] [2]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \rng_rd.mem_reg[4][0]  /* _296_ */ (
    .C(clk_i),
    .D(\rng_rd.mem[3] [0]),
    .E(_004_),
    .Q(\rng_rd.mem[4] [0]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \rng_rd.mem_reg[4][1]  /* _297_ */ (
    .C(clk_i),
    .D(\rng_rd.mem[3] [1]),
    .E(_004_),
    .Q(\rng_rd.mem[4] [1]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \rng_rd.mem_reg[4][2]  /* _298_ */ (
    .C(clk_i),
    .D(\rng_rd.mem[3] [2]),
    .E(_004_),
    .Q(\rng_rd.mem[4] [2]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \rng_rd.vld_reg[1]  /* _299_ */ (
    .C(clk_i),
    .D(\rng_rd.vld [0]),
    .E(_004_),
    .Q(\rng_rd.vld [1]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \rng_rd.vld_reg[0]  /* _300_ */ (
    .C(clk_i),
    .D(1'h1),
    .E(_004_),
    .Q(\rng_rd.vld [0]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \rng_rd.vld_reg[2]  /* _301_ */ (
    .C(clk_i),
    .D(\rng_rd.vld [1]),
    .E(_004_),
    .Q(\rng_rd.vld [2]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \rng_rd.vld_reg[3]  /* _302_ */ (
    .C(clk_i),
    .D(\rng_rd.vld [2]),
    .E(_004_),
    .Q(\rng_rd.vld [3]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \rng_rd.vld_reg[4]  /* _303_ */ (
    .C(clk_i),
    .D(\rng_rd.vld [3]),
    .E(_004_),
    .Q(\rng_rd.vld [4]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \rng_rd.vld_reg[5]  /* _304_ */ (
    .C(clk_i),
    .D(\rng_rd.vld [4]),
    .E(_004_),
    .Q(\rng_rd.vld [5]),
    .R(rst_i)
  );
  \$_DFF_PN0_  \rng_rd.wr_ff1_reg  /* _305_ */ (
    .C(clk_i),
    .D(wr_i),
    .Q(\rng_rd.wr_ff1 ),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \rng_rd.vld_reg[6]  /* _306_ */ (
    .C(clk_i),
    .D(\rng_rd.vld [5]),
    .E(_004_),
    .Q(\rng_rd.vld [6]),
    .R(rst_i)
  );
  \$_DFF_PN0_  \rng_rd.wr_ff2_reg  /* _307_ */ (
    .C(clk_i),
    .D(\rng_rd.wr_ff1 ),
    .Q(\rng_rd.wr_ff2 ),
    .R(rst_i)
  );
  \$_DFF_PN0_  \rng_rd.wr_ff2_d_reg  /* _308_ */ (
    .C(clk_i),
    .D(\rng_rd.wr_ff2 ),
    .Q(\rng_rd.wr_ff2_d ),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \rng_rd.vld_reg[7]  /* _309_ */ (
    .C(clk_i),
    .D(\rng_rd.vld [6]),
    .E(_004_),
    .Q(\rng_rd.vld [7]),
    .R(rst_i)
  );
  \$_DFF_PN0_  \rng_rd.wr_pulse_reg  /* _310_ */ (
    .C(clk_i),
    .D(_003_),
    .Q(\rng_rd.wr_pulse ),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \rng_rd.vld_reg[8]  /* _311_ */ (
    .C(clk_i),
    .D(\rng_rd.vld [7]),
    .E(_004_),
    .Q(\rng_rd.vld [8]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \rng_rd.vld_reg[9]  /* _312_ */ (
    .C(clk_i),
    .D(\rng_rd.vld [8]),
    .E(_004_),
    .Q(\rng_rd.vld [9]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \rng_rd.vld_reg[10]  /* _313_ */ (
    .C(clk_i),
    .D(\rng_rd.vld [9]),
    .E(_004_),
    .Q(\rng_rd.vld [10]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \rng_rd.vld_reg[11]  /* _314_ */ (
    .C(clk_i),
    .D(\rng_rd.vld [10]),
    .E(_004_),
    .Q(\rng_rd.vld [11]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \rng_rd.mem_reg[11][0]  /* _315_ */ (
    .C(clk_i),
    .D(\rng_rd.mem[10] [0]),
    .E(_004_),
    .Q(\rng_rd.mem[11] [0]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \rng_rd.mem_reg[11][1]  /* _316_ */ (
    .C(clk_i),
    .D(\rng_rd.mem[10] [1]),
    .E(_004_),
    .Q(\rng_rd.mem[11] [1]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \rng_rd.mem_reg[11][2]  /* _317_ */ (
    .C(clk_i),
    .D(\rng_rd.mem[10] [2]),
    .E(_004_),
    .Q(\rng_rd.mem[11] [2]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \num_to_send_o_reg[0]  /* _318_ */ (
    .C(clk_i),
    .D(num_i_bar[0]),
    .E(_004_),
    .Q(num_to_send_o[0]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \num_to_send_o_reg[1]  /* _319_ */ (
    .C(clk_i),
    .D(num_i_bar[1]),
    .E(_004_),
    .Q(num_to_send_o[1]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \num_to_send_o_reg[2]  /* _320_ */ (
    .C(clk_i),
    .D(num_i_bar[2]),
    .E(_004_),
    .Q(num_to_send_o[2]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \rng_rd.mem_reg[6][0]  /* _321_ */ (
    .C(clk_i),
    .D(\rng_rd.mem[5] [0]),
    .E(_004_),
    .Q(\rng_rd.mem[6] [0]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \rng_rd.mem_reg[6][1]  /* _322_ */ (
    .C(clk_i),
    .D(\rng_rd.mem[5] [1]),
    .E(_004_),
    .Q(\rng_rd.mem[6] [1]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \rng_rd.mem_reg[6][2]  /* _323_ */ (
    .C(clk_i),
    .D(\rng_rd.mem[5] [2]),
    .E(_004_),
    .Q(\rng_rd.mem[6] [2]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \rng_rd.mem_reg[3][0]  /* _324_ */ (
    .C(clk_i),
    .D(\rng_rd.mem[2] [0]),
    .E(_004_),
    .Q(\rng_rd.mem[3] [0]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \rng_rd.mem_reg[3][1]  /* _325_ */ (
    .C(clk_i),
    .D(\rng_rd.mem[2] [1]),
    .E(_004_),
    .Q(\rng_rd.mem[3] [1]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \rng_rd.mem_reg[3][2]  /* _326_ */ (
    .C(clk_i),
    .D(\rng_rd.mem[2] [2]),
    .E(_004_),
    .Q(\rng_rd.mem[3] [2]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \rng_rd.mem_reg[10][0]  /* _327_ */ (
    .C(clk_i),
    .D(\rng_rd.mem[9] [0]),
    .E(_004_),
    .Q(\rng_rd.mem[10] [0]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \rng_rd.mem_reg[10][1]  /* _328_ */ (
    .C(clk_i),
    .D(\rng_rd.mem[9] [1]),
    .E(_004_),
    .Q(\rng_rd.mem[10] [1]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \rng_rd.mem_reg[10][2]  /* _329_ */ (
    .C(clk_i),
    .D(\rng_rd.mem[9] [2]),
    .E(_004_),
    .Q(\rng_rd.mem[10] [2]),
    .R(rst_i)
  );
  \$_DFF_PN0_  \rng_dp.seed_sel_i_reg[0]  /* _330_ */ (
    .C(clk_i),
    .D(_140_[0]),
    .Q(\rng_dp.seed_sel_i [0]),
    .R(rst_i)
  );
  \$_DFF_PN0_  \rng_dp.seed_sel_i_reg[1]  /* _331_ */ (
    .C(clk_i),
    .D(_141_[1]),
    .Q(\rng_dp.seed_sel_i [1]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \rng_rd.mem_reg[7][0]  /* _332_ */ (
    .C(clk_i),
    .D(\rng_rd.mem[6] [0]),
    .E(_004_),
    .Q(\rng_rd.mem[7] [0]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \rng_rd.mem_reg[7][1]  /* _333_ */ (
    .C(clk_i),
    .D(\rng_rd.mem[6] [1]),
    .E(_004_),
    .Q(\rng_rd.mem[7] [1]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \rng_rd.mem_reg[7][2]  /* _334_ */ (
    .C(clk_i),
    .D(\rng_rd.mem[6] [2]),
    .E(_004_),
    .Q(\rng_rd.mem[7] [2]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \rng_dp.inst.next_num_o_reg[0]  /* _335_ */ (
    .C(clk_i),
    .D(_000_),
    .E(req_num),
    .Q(\rng_dp.inst.next_num_o [0]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \rng_dp.inst.next_num_o_reg[1]  /* _336_ */ (
    .C(clk_i),
    .D(_001_),
    .E(req_num),
    .Q(\rng_dp.inst.next_num_o [1]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \rng_dp.inst.next_num_o_reg[2]  /* _337_ */ (
    .C(clk_i),
    .D(_002_),
    .E(req_num),
    .Q(\rng_dp.inst.next_num_o [2]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \rng_rd.mem_reg[2][0]  /* _338_ */ (
    .C(clk_i),
    .D(\rng_rd.mem[1] [0]),
    .E(_004_),
    .Q(\rng_rd.mem[2] [0]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \rng_rd.mem_reg[2][1]  /* _339_ */ (
    .C(clk_i),
    .D(\rng_rd.mem[1] [1]),
    .E(_004_),
    .Q(\rng_rd.mem[2] [1]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \rng_rd.mem_reg[2][2]  /* _340_ */ (
    .C(clk_i),
    .D(\rng_rd.mem[1] [2]),
    .E(_004_),
    .Q(\rng_rd.mem[2] [2]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \rng_rd.mem_reg[5][0]  /* _341_ */ (
    .C(clk_i),
    .D(\rng_rd.mem[4] [0]),
    .E(_004_),
    .Q(\rng_rd.mem[5] [0]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \rng_rd.mem_reg[5][1]  /* _342_ */ (
    .C(clk_i),
    .D(\rng_rd.mem[4] [1]),
    .E(_004_),
    .Q(\rng_rd.mem[5] [1]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \rng_rd.mem_reg[5][2]  /* _343_ */ (
    .C(clk_i),
    .D(\rng_rd.mem[4] [2]),
    .E(_004_),
    .Q(\rng_rd.mem[5] [2]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \num_i_bar_reg[0]  /* _344_ */ (
    .C(clk_i),
    .D(_139_[0]),
    .E(req_num),
    .Q(num_i_bar[0]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \num_i_bar_reg[1]  /* _345_ */ (
    .C(clk_i),
    .D(_139_[1]),
    .E(req_num),
    .Q(num_i_bar[1]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \num_i_bar_reg[2]  /* _346_ */ (
    .C(clk_i),
    .D(_139_[2]),
    .E(req_num),
    .Q(num_i_bar[2]),
    .R(rst_i)
  );
  assign _140_[1] = \rng_dp.seed_sel_i [1];
  assign _141_[0] = _140_[0];
endmodule
