/* Generated by Yosys 0.59+0 (git sha1 26b51148a, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

module \$paramod$54156aeb88216e1ed0a79a36b33881dba9f19205\rng_data_path (clk_i, rst_i, req_num_i, seed_sel_i, num_to_send_o);
  input clk_i;
  wire clk_i;
  input rst_i;
  wire rst_i;
  input req_num_i;
  wire req_num_i;
  input [1:0] seed_sel_i;
  wire [1:0] seed_sel_i;
  output [2:0] num_to_send_o;
  wire [2:0] num_to_send_o;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire [2:0] _09_;
  wire [2:0] _10_;
  wire [2:0] _11_;
  wire [2:0] _12_;
  wire [2:0] _13_;
  wire [2:0] _14_;
  wire [2:0] _15_;
  wire [8:0] _16_;
  wire [8:0] _17_;
  wire [2:0] _18_;
  wire [2:0] _19_;
  wire [2:0] _20_;
  wire _21_;
  wire [2:0] next_num;
  wire [2:0] num_to_send;
  \$_DFFE_PN0P_  \next_num_reg[0]  /* _22_ */ (
    .C(clk_i),
    .D(_19_[0]),
    .E(req_num_i),
    .Q(next_num[0]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \next_num_reg[1]  /* _23_ */ (
    .C(clk_i),
    .D(_19_[1]),
    .E(req_num_i),
    .Q(next_num[1]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \next_num_reg[2]  /* _24_ */ (
    .C(clk_i),
    .D(_19_[2]),
    .E(req_num_i),
    .Q(next_num[2]),
    .R(rst_i)
  );
  \$_NOT_  _25_ (
    .A(seed_sel_i[1]),
    .Y(_00_)
  );
  \$_NOT_  _26_ (
    .A(seed_sel_i[0]),
    .Y(_01_)
  );
  \$_AND_  _27_ (
    .A(_16_[6]),
    .B(_18_[2]),
    .Y(_17_[6])
  );
  \$_AND_  _28_ (
    .A(_16_[7]),
    .B(_18_[2]),
    .Y(_17_[7])
  );
  \$_AND_  _29_ (
    .A(_16_[8]),
    .B(_18_[2]),
    .Y(_17_[8])
  );
  \$_AND_  _30_ (
    .A(_16_[3]),
    .B(_18_[1]),
    .Y(_17_[3])
  );
  \$_AND_  _31_ (
    .A(_16_[4]),
    .B(_18_[1]),
    .Y(_17_[4])
  );
  \$_AND_  _32_ (
    .A(_15_[0]),
    .B(_18_[1]),
    .Y(_17_[5])
  );
  \$_AND_  _33_ (
    .A(_16_[0]),
    .B(_18_[0]),
    .Y(_17_[0])
  );
  \$_AND_  _34_ (
    .A(_16_[1]),
    .B(_18_[0]),
    .Y(_17_[1])
  );
  \$_AND_  _35_ (
    .A(num_to_send[2]),
    .B(_18_[0]),
    .Y(_17_[2])
  );
  \$_OR_  _36_ (
    .A(_05_),
    .B(_17_[6]),
    .Y(_20_[0])
  );
  \$_OR_  _37_ (
    .A(_18_[0]),
    .B(_18_[1]),
    .Y(_02_)
  );
  \$_OR_  _38_ (
    .A(_02_),
    .B(_18_[2]),
    .Y(_21_)
  );
  \$_OR_  _39_ (
    .A(seed_sel_i[0]),
    .B(_00_),
    .Y(_07_)
  );
  \$_OR_  _40_ (
    .A(_01_),
    .B(seed_sel_i[1]),
    .Y(_08_)
  );
  \$_OR_  _41_ (
    .A(_17_[2]),
    .B(_17_[5]),
    .Y(_03_)
  );
  \$_OR_  _42_ (
    .A(_03_),
    .B(_17_[8]),
    .Y(_20_[2])
  );
  \$_OR_  _43_ (
    .A(_17_[1]),
    .B(_17_[4]),
    .Y(_04_)
  );
  \$_OR_  _44_ (
    .A(_04_),
    .B(_17_[7]),
    .Y(_20_[1])
  );
  \$_OR_  _45_ (
    .A(_17_[0]),
    .B(_17_[3]),
    .Y(_05_)
  );
  \$_OR_  _46_ (
    .A(seed_sel_i[0]),
    .B(seed_sel_i[1]),
    .Y(_06_)
  );
  \$_NOT_  _47_ (
    .A(_07_),
    .Y(_18_[0])
  );
  \$_NOT_  _48_ (
    .A(_08_),
    .Y(_18_[1])
  );
  \$_NOT_  _49_ (
    .A(_06_),
    .Y(_18_[2])
  );
  \$_MUX_  _50_ (
    .A(_15_[0]),
    .B(_20_[0]),
    .S(_21_),
    .Y(_19_[0])
  );
  \$_MUX_  _51_ (
    .A(_15_[1]),
    .B(_20_[1]),
    .S(_21_),
    .Y(_19_[1])
  );
  \$_MUX_  _52_ (
    .A(_15_[2]),
    .B(_20_[2]),
    .S(_21_),
    .Y(_19_[2])
  );
  \$_MUX_  _53_ (
    .A(_09_[0]),
    .B(_10_[0]),
    .S(num_to_send[2]),
    .Y(_16_[6])
  );
  \$_MUX_  _54_ (
    .A(_09_[1]),
    .B(num_to_send[0]),
    .S(num_to_send[2]),
    .Y(_16_[7])
  );
  \$_MUX_  _55_ (
    .A(_09_[2]),
    .B(_10_[2]),
    .S(num_to_send[2]),
    .Y(_16_[8])
  );
  \$_MUX_  _56_ (
    .A(_11_[0]),
    .B(num_to_send[0]),
    .S(num_to_send[1]),
    .Y(_13_[0])
  );
  \$_NOT_  _57_ (
    .A(num_to_send[1]),
    .Y(_09_[1])
  );
  \$_MUX_  _58_ (
    .A(1'h0),
    .B(_11_[0]),
    .S(num_to_send[1]),
    .Y(_10_[2])
  );
  \$_NOT_  _59_ (
    .A(num_to_send[0]),
    .Y(_11_[0])
  );
  \$_MUX_  _60_ (
    .A(_11_[0]),
    .B(num_to_send[0]),
    .S(num_to_send[2]),
    .Y(_15_[0])
  );
  \$_MUX_  _61_ (
    .A(_09_[2]),
    .B(_10_[0]),
    .S(num_to_send[2]),
    .Y(_15_[1])
  );
  \$_MUX_  _62_ (
    .A(_10_[0]),
    .B(_14_[2]),
    .S(num_to_send[2]),
    .Y(_15_[2])
  );
  \$_MUX_  _63_ (
    .A(num_to_send[0]),
    .B(_13_[0]),
    .S(num_to_send[2]),
    .Y(_16_[0])
  );
  \$_MUX_  _64_ (
    .A(_09_[1]),
    .B(num_to_send[1]),
    .S(num_to_send[2]),
    .Y(_16_[1])
  );
  \$_MUX_  _65_ (
    .A(1'h1),
    .B(num_to_send[0]),
    .S(num_to_send[1]),
    .Y(_09_[2])
  );
  \$_MUX_  _66_ (
    .A(1'h0),
    .B(num_to_send[0]),
    .S(num_to_send[1]),
    .Y(_10_[0])
  );
  \$_MUX_  _67_ (
    .A(num_to_send[0]),
    .B(1'h1),
    .S(num_to_send[1]),
    .Y(_14_[2])
  );
  \$_MUX_  _68_ (
    .A(_09_[0]),
    .B(_12_[0]),
    .S(num_to_send[2]),
    .Y(_16_[3])
  );
  \$_MUX_  _69_ (
    .A(_10_[2]),
    .B(_09_[0]),
    .S(num_to_send[2]),
    .Y(_16_[4])
  );
  \$_MUX_  _70_ (
    .A(_11_[0]),
    .B(1'h0),
    .S(num_to_send[1]),
    .Y(_12_[0])
  );
  \$_MUX_  _71_ (
    .A(_11_[0]),
    .B(1'h1),
    .S(num_to_send[1]),
    .Y(_09_[0])
  );
  rng_data_path_counter inst (
    .clk_i(clk_i),
    .next_num_o(num_to_send),
    .req_num_i(req_num_i),
    .rst_i(rst_i)
  );
  assign _10_[1] = num_to_send[0];
  assign _11_[2:1] = 2'h3;
  assign _12_[2:1] = { num_to_send[0], _09_[0] };
  assign _13_[2:1] = { 1'h1, num_to_send[1] };
  assign _14_[1:0] = { _10_[0], num_to_send[0] };
  assign { _16_[5], _16_[2] } = { _15_[0], num_to_send[2] };
  assign num_to_send_o = next_num;
endmodule

module \$paramod$54156aeb88216e1ed0a79a36b33881dba9f19205\rng_hs_dup_detector (clk_i, rst_i, req_num_i, data_i, wr_i, data_o, req_new_num_o);
  input clk_i;
  wire clk_i;
  input rst_i;
  wire rst_i;
  input req_num_i;
  wire req_num_i;
  input [2:0] data_i;
  wire [2:0] data_i;
  input wr_i;
  wire wr_i;
  output [2:0] data_o;
  wire [2:0] data_o;
  output req_new_num_o;
  wire req_new_num_o;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire [2:0] _013_;
  wire [2:0] _014_;
  wire [2:0] _015_;
  wire [2:0] _016_;
  wire [2:0] _017_;
  wire [2:0] _018_;
  wire [2:0] _019_;
  wire [2:0] _020_;
  wire [2:0] _021_;
  wire [2:0] _022_;
  wire [2:0] _023_;
  wire [2:0] _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire approve;
  wire hit;
  wire [2:0] \mem[0] ;
  wire [2:0] \mem[10] ;
  wire [2:0] \mem[11] ;
  wire [2:0] \mem[1] ;
  wire [2:0] \mem[2] ;
  wire [2:0] \mem[3] ;
  wire [2:0] \mem[4] ;
  wire [2:0] \mem[5] ;
  wire [2:0] \mem[6] ;
  wire [2:0] \mem[7] ;
  wire [2:0] \mem[8] ;
  wire [2:0] \mem[9] ;
  wire [11:0] vld;
  wire wr_ff1;
  wire wr_ff2;
  wire wr_ff2_d;
  wire wr_pulse;
  \$_DFFE_PN0P_  \mem_reg[11][0]  /* _073_ */ (
    .C(clk_i),
    .D(\mem[10] [0]),
    .E(_061_),
    .Q(\mem[11] [0]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \mem_reg[11][1]  /* _074_ */ (
    .C(clk_i),
    .D(\mem[10] [1]),
    .E(_061_),
    .Q(\mem[11] [1]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \mem_reg[11][2]  /* _075_ */ (
    .C(clk_i),
    .D(\mem[10] [2]),
    .E(_061_),
    .Q(\mem[11] [2]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \vld_reg[0]  /* _076_ */ (
    .C(clk_i),
    .D(1'h1),
    .E(_061_),
    .Q(vld[0]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \vld_reg[1]  /* _077_ */ (
    .C(clk_i),
    .D(vld[0]),
    .E(_061_),
    .Q(vld[1]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \vld_reg[2]  /* _078_ */ (
    .C(clk_i),
    .D(vld[1]),
    .E(_061_),
    .Q(vld[2]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \vld_reg[3]  /* _079_ */ (
    .C(clk_i),
    .D(vld[2]),
    .E(_061_),
    .Q(vld[3]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \vld_reg[4]  /* _080_ */ (
    .C(clk_i),
    .D(vld[3]),
    .E(_061_),
    .Q(vld[4]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \vld_reg[5]  /* _081_ */ (
    .C(clk_i),
    .D(vld[4]),
    .E(_061_),
    .Q(vld[5]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \vld_reg[6]  /* _082_ */ (
    .C(clk_i),
    .D(vld[5]),
    .E(_061_),
    .Q(vld[6]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \vld_reg[7]  /* _083_ */ (
    .C(clk_i),
    .D(vld[6]),
    .E(_061_),
    .Q(vld[7]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \vld_reg[8]  /* _084_ */ (
    .C(clk_i),
    .D(vld[7]),
    .E(_061_),
    .Q(vld[8]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \vld_reg[9]  /* _085_ */ (
    .C(clk_i),
    .D(vld[8]),
    .E(_061_),
    .Q(vld[9]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \vld_reg[10]  /* _086_ */ (
    .C(clk_i),
    .D(vld[9]),
    .E(_061_),
    .Q(vld[10]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \vld_reg[11]  /* _087_ */ (
    .C(clk_i),
    .D(vld[10]),
    .E(_061_),
    .Q(vld[11]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \mem_reg[0][0]  /* _088_ */ (
    .C(clk_i),
    .D(data_i[0]),
    .E(_061_),
    .Q(\mem[0] [0]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \mem_reg[0][1]  /* _089_ */ (
    .C(clk_i),
    .D(data_i[1]),
    .E(_061_),
    .Q(\mem[0] [1]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \mem_reg[0][2]  /* _090_ */ (
    .C(clk_i),
    .D(data_i[2]),
    .E(_061_),
    .Q(\mem[0] [2]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \mem_reg[1][0]  /* _091_ */ (
    .C(clk_i),
    .D(\mem[0] [0]),
    .E(_061_),
    .Q(\mem[1] [0]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \mem_reg[1][1]  /* _092_ */ (
    .C(clk_i),
    .D(\mem[0] [1]),
    .E(_061_),
    .Q(\mem[1] [1]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \mem_reg[1][2]  /* _093_ */ (
    .C(clk_i),
    .D(\mem[0] [2]),
    .E(_061_),
    .Q(\mem[1] [2]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \mem_reg[2][0]  /* _094_ */ (
    .C(clk_i),
    .D(\mem[1] [0]),
    .E(_061_),
    .Q(\mem[2] [0]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \mem_reg[2][1]  /* _095_ */ (
    .C(clk_i),
    .D(\mem[1] [1]),
    .E(_061_),
    .Q(\mem[2] [1]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \mem_reg[2][2]  /* _096_ */ (
    .C(clk_i),
    .D(\mem[1] [2]),
    .E(_061_),
    .Q(\mem[2] [2]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \mem_reg[3][0]  /* _097_ */ (
    .C(clk_i),
    .D(\mem[2] [0]),
    .E(_061_),
    .Q(\mem[3] [0]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \mem_reg[3][1]  /* _098_ */ (
    .C(clk_i),
    .D(\mem[2] [1]),
    .E(_061_),
    .Q(\mem[3] [1]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \mem_reg[3][2]  /* _099_ */ (
    .C(clk_i),
    .D(\mem[2] [2]),
    .E(_061_),
    .Q(\mem[3] [2]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \mem_reg[4][0]  /* _100_ */ (
    .C(clk_i),
    .D(\mem[3] [0]),
    .E(_061_),
    .Q(\mem[4] [0]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \mem_reg[4][1]  /* _101_ */ (
    .C(clk_i),
    .D(\mem[3] [1]),
    .E(_061_),
    .Q(\mem[4] [1]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \mem_reg[4][2]  /* _102_ */ (
    .C(clk_i),
    .D(\mem[3] [2]),
    .E(_061_),
    .Q(\mem[4] [2]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \mem_reg[5][0]  /* _103_ */ (
    .C(clk_i),
    .D(\mem[4] [0]),
    .E(_061_),
    .Q(\mem[5] [0]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \mem_reg[5][1]  /* _104_ */ (
    .C(clk_i),
    .D(\mem[4] [1]),
    .E(_061_),
    .Q(\mem[5] [1]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \mem_reg[5][2]  /* _105_ */ (
    .C(clk_i),
    .D(\mem[4] [2]),
    .E(_061_),
    .Q(\mem[5] [2]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \mem_reg[6][0]  /* _106_ */ (
    .C(clk_i),
    .D(\mem[5] [0]),
    .E(_061_),
    .Q(\mem[6] [0]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \mem_reg[6][1]  /* _107_ */ (
    .C(clk_i),
    .D(\mem[5] [1]),
    .E(_061_),
    .Q(\mem[6] [1]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \mem_reg[6][2]  /* _108_ */ (
    .C(clk_i),
    .D(\mem[5] [2]),
    .E(_061_),
    .Q(\mem[6] [2]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \mem_reg[7][0]  /* _109_ */ (
    .C(clk_i),
    .D(\mem[6] [0]),
    .E(_061_),
    .Q(\mem[7] [0]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \mem_reg[7][1]  /* _110_ */ (
    .C(clk_i),
    .D(\mem[6] [1]),
    .E(_061_),
    .Q(\mem[7] [1]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \mem_reg[7][2]  /* _111_ */ (
    .C(clk_i),
    .D(\mem[6] [2]),
    .E(_061_),
    .Q(\mem[7] [2]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \mem_reg[8][0]  /* _112_ */ (
    .C(clk_i),
    .D(\mem[7] [0]),
    .E(_061_),
    .Q(\mem[8] [0]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \mem_reg[8][1]  /* _113_ */ (
    .C(clk_i),
    .D(\mem[7] [1]),
    .E(_061_),
    .Q(\mem[8] [1]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \mem_reg[8][2]  /* _114_ */ (
    .C(clk_i),
    .D(\mem[7] [2]),
    .E(_061_),
    .Q(\mem[8] [2]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \mem_reg[9][0]  /* _115_ */ (
    .C(clk_i),
    .D(\mem[8] [0]),
    .E(_061_),
    .Q(\mem[9] [0]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \mem_reg[9][1]  /* _116_ */ (
    .C(clk_i),
    .D(\mem[8] [1]),
    .E(_061_),
    .Q(\mem[9] [1]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \mem_reg[9][2]  /* _117_ */ (
    .C(clk_i),
    .D(\mem[8] [2]),
    .E(_061_),
    .Q(\mem[9] [2]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \mem_reg[10][0]  /* _118_ */ (
    .C(clk_i),
    .D(\mem[9] [0]),
    .E(_061_),
    .Q(\mem[10] [0]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \mem_reg[10][1]  /* _119_ */ (
    .C(clk_i),
    .D(\mem[9] [1]),
    .E(_061_),
    .Q(\mem[10] [1]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \mem_reg[10][2]  /* _120_ */ (
    .C(clk_i),
    .D(\mem[9] [2]),
    .E(_061_),
    .Q(\mem[10] [2]),
    .R(rst_i)
  );
  \$_DFF_PN0_  wr_ff1_reg /* _121_ */ (
    .C(clk_i),
    .D(wr_i),
    .Q(wr_ff1),
    .R(rst_i)
  );
  \$_DFF_PN0_  wr_ff2_reg /* _122_ */ (
    .C(clk_i),
    .D(wr_ff1),
    .Q(wr_ff2),
    .R(rst_i)
  );
  \$_DFF_PN0_  wr_ff2_d_reg /* _123_ */ (
    .C(clk_i),
    .D(wr_ff2),
    .Q(wr_ff2_d),
    .R(rst_i)
  );
  \$_DFF_PN0_  wr_pulse_reg /* _124_ */ (
    .C(clk_i),
    .D(_000_),
    .Q(wr_pulse),
    .R(rst_i)
  );
  \$_XOR_  _125_ (
    .A(data_i[0]),
    .B(\mem[0] [0]),
    .Y(_013_[0])
  );
  \$_XOR_  _126_ (
    .A(data_i[1]),
    .B(\mem[0] [1]),
    .Y(_013_[1])
  );
  \$_XOR_  _127_ (
    .A(data_i[2]),
    .B(\mem[0] [2]),
    .Y(_013_[2])
  );
  \$_XOR_  _128_ (
    .A(data_i[0]),
    .B(\mem[1] [0]),
    .Y(_014_[0])
  );
  \$_XOR_  _129_ (
    .A(data_i[1]),
    .B(\mem[1] [1]),
    .Y(_014_[1])
  );
  \$_XOR_  _130_ (
    .A(data_i[2]),
    .B(\mem[1] [2]),
    .Y(_014_[2])
  );
  \$_XOR_  _131_ (
    .A(data_i[0]),
    .B(\mem[2] [0]),
    .Y(_015_[0])
  );
  \$_XOR_  _132_ (
    .A(data_i[1]),
    .B(\mem[2] [1]),
    .Y(_015_[1])
  );
  \$_XOR_  _133_ (
    .A(data_i[2]),
    .B(\mem[2] [2]),
    .Y(_015_[2])
  );
  \$_XOR_  _134_ (
    .A(data_i[0]),
    .B(\mem[3] [0]),
    .Y(_016_[0])
  );
  \$_XOR_  _135_ (
    .A(data_i[1]),
    .B(\mem[3] [1]),
    .Y(_016_[1])
  );
  \$_XOR_  _136_ (
    .A(data_i[2]),
    .B(\mem[3] [2]),
    .Y(_016_[2])
  );
  \$_XOR_  _137_ (
    .A(data_i[0]),
    .B(\mem[4] [0]),
    .Y(_017_[0])
  );
  \$_XOR_  _138_ (
    .A(data_i[1]),
    .B(\mem[4] [1]),
    .Y(_017_[1])
  );
  \$_XOR_  _139_ (
    .A(data_i[2]),
    .B(\mem[4] [2]),
    .Y(_017_[2])
  );
  \$_XOR_  _140_ (
    .A(data_i[0]),
    .B(\mem[5] [0]),
    .Y(_018_[0])
  );
  \$_XOR_  _141_ (
    .A(data_i[1]),
    .B(\mem[5] [1]),
    .Y(_018_[1])
  );
  \$_XOR_  _142_ (
    .A(data_i[2]),
    .B(\mem[5] [2]),
    .Y(_018_[2])
  );
  \$_XOR_  _143_ (
    .A(data_i[0]),
    .B(\mem[6] [0]),
    .Y(_019_[0])
  );
  \$_XOR_  _144_ (
    .A(data_i[1]),
    .B(\mem[6] [1]),
    .Y(_019_[1])
  );
  \$_XOR_  _145_ (
    .A(data_i[2]),
    .B(\mem[6] [2]),
    .Y(_019_[2])
  );
  \$_XOR_  _146_ (
    .A(data_i[0]),
    .B(\mem[7] [0]),
    .Y(_020_[0])
  );
  \$_XOR_  _147_ (
    .A(data_i[1]),
    .B(\mem[7] [1]),
    .Y(_020_[1])
  );
  \$_XOR_  _148_ (
    .A(data_i[2]),
    .B(\mem[7] [2]),
    .Y(_020_[2])
  );
  \$_XOR_  _149_ (
    .A(data_i[0]),
    .B(\mem[8] [0]),
    .Y(_021_[0])
  );
  \$_XOR_  _150_ (
    .A(data_i[1]),
    .B(\mem[8] [1]),
    .Y(_021_[1])
  );
  \$_XOR_  _151_ (
    .A(data_i[2]),
    .B(\mem[8] [2]),
    .Y(_021_[2])
  );
  \$_XOR_  _152_ (
    .A(data_i[0]),
    .B(\mem[9] [0]),
    .Y(_022_[0])
  );
  \$_XOR_  _153_ (
    .A(data_i[1]),
    .B(\mem[9] [1]),
    .Y(_022_[1])
  );
  \$_XOR_  _154_ (
    .A(data_i[2]),
    .B(\mem[9] [2]),
    .Y(_022_[2])
  );
  \$_XOR_  _155_ (
    .A(data_i[0]),
    .B(\mem[10] [0]),
    .Y(_023_[0])
  );
  \$_XOR_  _156_ (
    .A(data_i[1]),
    .B(\mem[10] [1]),
    .Y(_023_[1])
  );
  \$_XOR_  _157_ (
    .A(data_i[2]),
    .B(\mem[10] [2]),
    .Y(_023_[2])
  );
  \$_XOR_  _158_ (
    .A(data_i[0]),
    .B(\mem[11] [0]),
    .Y(_024_[0])
  );
  \$_XOR_  _159_ (
    .A(data_i[1]),
    .B(\mem[11] [1]),
    .Y(_024_[1])
  );
  \$_XOR_  _160_ (
    .A(data_i[2]),
    .B(\mem[11] [2]),
    .Y(_024_[2])
  );
  \$_AND_  _161_ (
    .A(req_num_i),
    .B(hit),
    .Y(req_new_num_o)
  );
  \$_AND_  _162_ (
    .A(wr_ff2),
    .B(_072_),
    .Y(_000_)
  );
  \$_OR_  _163_ (
    .A(_013_[0]),
    .B(_013_[1]),
    .Y(_001_)
  );
  \$_OR_  _164_ (
    .A(_001_),
    .B(_013_[2]),
    .Y(_025_)
  );
  \$_OR_  _165_ (
    .A(_014_[0]),
    .B(_014_[1]),
    .Y(_002_)
  );
  \$_OR_  _166_ (
    .A(_002_),
    .B(_014_[2]),
    .Y(_026_)
  );
  \$_OR_  _167_ (
    .A(_015_[0]),
    .B(_015_[1]),
    .Y(_003_)
  );
  \$_OR_  _168_ (
    .A(_003_),
    .B(_015_[2]),
    .Y(_027_)
  );
  \$_OR_  _169_ (
    .A(_016_[0]),
    .B(_016_[1]),
    .Y(_004_)
  );
  \$_OR_  _170_ (
    .A(_004_),
    .B(_016_[2]),
    .Y(_028_)
  );
  \$_OR_  _171_ (
    .A(_017_[0]),
    .B(_017_[1]),
    .Y(_005_)
  );
  \$_OR_  _172_ (
    .A(_005_),
    .B(_017_[2]),
    .Y(_029_)
  );
  \$_OR_  _173_ (
    .A(_018_[0]),
    .B(_018_[1]),
    .Y(_006_)
  );
  \$_OR_  _174_ (
    .A(_006_),
    .B(_018_[2]),
    .Y(_030_)
  );
  \$_OR_  _175_ (
    .A(_019_[0]),
    .B(_019_[1]),
    .Y(_007_)
  );
  \$_OR_  _176_ (
    .A(_007_),
    .B(_019_[2]),
    .Y(_031_)
  );
  \$_OR_  _177_ (
    .A(_020_[0]),
    .B(_020_[1]),
    .Y(_008_)
  );
  \$_OR_  _178_ (
    .A(_008_),
    .B(_020_[2]),
    .Y(_032_)
  );
  \$_OR_  _179_ (
    .A(_021_[0]),
    .B(_021_[1]),
    .Y(_009_)
  );
  \$_OR_  _180_ (
    .A(_009_),
    .B(_021_[2]),
    .Y(_033_)
  );
  \$_OR_  _181_ (
    .A(_022_[0]),
    .B(_022_[1]),
    .Y(_010_)
  );
  \$_OR_  _182_ (
    .A(_010_),
    .B(_022_[2]),
    .Y(_034_)
  );
  \$_OR_  _183_ (
    .A(_023_[0]),
    .B(_023_[1]),
    .Y(_011_)
  );
  \$_OR_  _184_ (
    .A(_011_),
    .B(_023_[2]),
    .Y(_035_)
  );
  \$_OR_  _185_ (
    .A(_024_[0]),
    .B(_024_[1]),
    .Y(_012_)
  );
  \$_OR_  _186_ (
    .A(_012_),
    .B(_024_[2]),
    .Y(_036_)
  );
  \$_NOT_  _187_ (
    .A(_025_),
    .Y(_037_)
  );
  \$_NOT_  _188_ (
    .A(_026_),
    .Y(_038_)
  );
  \$_NOT_  _189_ (
    .A(_027_),
    .Y(_039_)
  );
  \$_NOT_  _190_ (
    .A(_028_),
    .Y(_040_)
  );
  \$_NOT_  _191_ (
    .A(_029_),
    .Y(_041_)
  );
  \$_NOT_  _192_ (
    .A(_030_),
    .Y(_042_)
  );
  \$_NOT_  _193_ (
    .A(_031_),
    .Y(_043_)
  );
  \$_NOT_  _194_ (
    .A(_032_),
    .Y(_044_)
  );
  \$_NOT_  _195_ (
    .A(_033_),
    .Y(_045_)
  );
  \$_NOT_  _196_ (
    .A(_034_),
    .Y(_046_)
  );
  \$_NOT_  _197_ (
    .A(_035_),
    .Y(_047_)
  );
  \$_NOT_  _198_ (
    .A(_036_),
    .Y(_048_)
  );
  \$_AND_  _199_ (
    .A(vld[0]),
    .B(_037_),
    .Y(_049_)
  );
  \$_AND_  _200_ (
    .A(vld[1]),
    .B(_038_),
    .Y(_050_)
  );
  \$_OR_  _201_ (
    .A(_049_),
    .B(_050_),
    .Y(_064_)
  );
  \$_AND_  _202_ (
    .A(vld[2]),
    .B(_039_),
    .Y(_051_)
  );
  \$_OR_  _203_ (
    .A(_064_),
    .B(_051_),
    .Y(_065_)
  );
  \$_AND_  _204_ (
    .A(vld[3]),
    .B(_040_),
    .Y(_052_)
  );
  \$_OR_  _205_ (
    .A(_065_),
    .B(_052_),
    .Y(_066_)
  );
  \$_AND_  _206_ (
    .A(vld[4]),
    .B(_041_),
    .Y(_053_)
  );
  \$_OR_  _207_ (
    .A(_066_),
    .B(_053_),
    .Y(_067_)
  );
  \$_AND_  _208_ (
    .A(vld[5]),
    .B(_042_),
    .Y(_054_)
  );
  \$_OR_  _209_ (
    .A(_067_),
    .B(_054_),
    .Y(_068_)
  );
  \$_AND_  _210_ (
    .A(vld[6]),
    .B(_043_),
    .Y(_055_)
  );
  \$_OR_  _211_ (
    .A(_068_),
    .B(_055_),
    .Y(_069_)
  );
  \$_AND_  _212_ (
    .A(vld[7]),
    .B(_044_),
    .Y(_056_)
  );
  \$_OR_  _213_ (
    .A(_069_),
    .B(_056_),
    .Y(_070_)
  );
  \$_AND_  _214_ (
    .A(vld[8]),
    .B(_045_),
    .Y(_057_)
  );
  \$_OR_  _215_ (
    .A(_070_),
    .B(_057_),
    .Y(_071_)
  );
  \$_AND_  _216_ (
    .A(vld[9]),
    .B(_046_),
    .Y(_058_)
  );
  \$_OR_  _217_ (
    .A(_071_),
    .B(_058_),
    .Y(_062_)
  );
  \$_AND_  _218_ (
    .A(vld[10]),
    .B(_047_),
    .Y(_059_)
  );
  \$_OR_  _219_ (
    .A(_062_),
    .B(_059_),
    .Y(_063_)
  );
  \$_AND_  _220_ (
    .A(vld[11]),
    .B(_048_),
    .Y(_060_)
  );
  \$_OR_  _221_ (
    .A(_063_),
    .B(_060_),
    .Y(hit)
  );
  \$_AND_  _222_ (
    .A(approve),
    .B(wr_pulse),
    .Y(_061_)
  );
  \$_NOT_  _223_ (
    .A(hit),
    .Y(approve)
  );
  \$_NOT_  _224_ (
    .A(wr_ff2_d),
    .Y(_072_)
  );
  assign data_o = \mem[0] ;
endmodule

module \$paramod$54156aeb88216e1ed0a79a36b33881dba9f19205\rng_selector (clk_i, start_i, rst_i, seed_sel_o);
  input clk_i;
  wire clk_i;
  input start_i;
  wire start_i;
  input rst_i;
  wire rst_i;
  output [1:0] seed_sel_o;
  wire [1:0] seed_sel_o;
  wire [1:0] _0_;
  wire [1:0] _1_;
  wire [1:0] seed_s;
  \$_DFF_PN0_  \seed_s_reg[0]  /* _2_ */ (
    .C(clk_i),
    .D(_0_[0]),
    .Q(seed_s[0]),
    .R(rst_i)
  );
  \$_DFF_PN0_  \seed_s_reg[1]  /* _3_ */ (
    .C(clk_i),
    .D(_1_[1]),
    .Q(seed_s[1]),
    .R(rst_i)
  );
  \$_XOR_  _4_ (
    .A(seed_s[1]),
    .B(seed_s[0]),
    .Y(_1_[1])
  );
  \$_NOT_  _5_ (
    .A(seed_s[0]),
    .Y(_0_[0])
  );
  assign _0_[1] = seed_s[1];
  assign _1_[0] = _0_[0];
  assign seed_sel_o = seed_s;
endmodule

module rng_data_path_counter(clk_i, rst_i, req_num_i, next_num_o);
  input clk_i;
  wire clk_i;
  input rst_i;
  wire rst_i;
  input req_num_i;
  wire req_num_i;
  output [2:0] next_num_o;
  wire [2:0] next_num_o;
  wire [2:0] _00_;
  wire [2:0] _01_;
  wire [2:0] _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire [2:0] _07_;
  wire [2:0] num_counter;
  \$_DFFE_PN0P_  \num_counter_reg[0]  /* _08_ */ (
    .C(clk_i),
    .D(_07_[0]),
    .E(req_num_i),
    .Q(num_counter[0]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \num_counter_reg[1]  /* _09_ */ (
    .C(clk_i),
    .D(_07_[1]),
    .E(req_num_i),
    .Q(num_counter[1]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \num_counter_reg[2]  /* _10_ */ (
    .C(clk_i),
    .D(_07_[2]),
    .E(req_num_i),
    .Q(num_counter[2]),
    .R(rst_i)
  );
  \$_NOT_  _11_ (
    .A(num_counter[2]),
    .Y(_03_)
  );
  \$_XOR_  _12_ (
    .A(num_counter[1]),
    .B(num_counter[0]),
    .Y(_02_[1])
  );
  \$_XOR_  _13_ (
    .A(num_counter[2]),
    .B(_00_[1]),
    .Y(_02_[2])
  );
  \$_AND_  _14_ (
    .A(num_counter[1]),
    .B(num_counter[0]),
    .Y(_00_[1])
  );
  \$_OR_  _15_ (
    .A(_01_[0]),
    .B(_04_),
    .Y(_05_)
  );
  \$_OR_  _16_ (
    .A(_05_),
    .B(_03_),
    .Y(_06_)
  );
  \$_MUX_  _17_ (
    .A(1'h0),
    .B(_01_[0]),
    .S(_06_),
    .Y(_07_[0])
  );
  \$_MUX_  _18_ (
    .A(1'h0),
    .B(_02_[1]),
    .S(_06_),
    .Y(_07_[1])
  );
  \$_MUX_  _19_ (
    .A(1'h0),
    .B(_02_[2]),
    .S(_06_),
    .Y(_07_[2])
  );
  \$_NOT_  _20_ (
    .A(num_counter[0]),
    .Y(_01_[0])
  );
  \$_NOT_  _21_ (
    .A(num_counter[1]),
    .Y(_04_)
  );
  assign _00_[0] = num_counter[0];
  assign _01_[2:1] = num_counter[2:1];
  assign _02_[0] = _01_[0];
  assign next_num_o = num_counter;
endmodule

module rng_top(clk_i, start_i, rst_i, req_num_i, wr_i, num_to_send_o);
  input clk_i;
  wire clk_i;
  input start_i;
  wire start_i;
  input rst_i;
  wire rst_i;
  input req_num_i;
  wire req_num_i;
  input wr_i;
  wire wr_i;
  output [2:0] num_to_send_o;
  wire [2:0] num_to_send_o;
  wire [2:0] num_i_bar;
  wire req_num;
  wire req_num_again;
  wire [1:0] seed_bar;
  \$_OR_  _0_ (
    .A(req_num_i),
    .B(req_num_again),
    .Y(req_num)
  );
  \$paramod$54156aeb88216e1ed0a79a36b33881dba9f19205\rng_data_path  rng_dp (
    .clk_i(clk_i),
    .num_to_send_o(num_i_bar),
    .req_num_i(req_num),
    .rst_i(rst_i),
    .seed_sel_i(seed_bar)
  );
  \$paramod$54156aeb88216e1ed0a79a36b33881dba9f19205\rng_hs_dup_detector  rng_rd (
    .clk_i(clk_i),
    .data_i(num_i_bar),
    .data_o(num_to_send_o),
    .req_new_num_o(req_num_again),
    .req_num_i(req_num),
    .rst_i(rst_i),
    .wr_i(wr_i)
  );
  \$paramod$54156aeb88216e1ed0a79a36b33881dba9f19205\rng_selector  rng_sel (
    .clk_i(clk_i),
    .rst_i(rst_i),
    .seed_sel_o(seed_bar),
    .start_i(start_i)
  );
endmodule
