/* Generated by Yosys 0.59+0 (git sha1 26b51148a, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

module \$paramod$54156aeb88216e1ed0a79a36b33881dba9f19205\rng_data_path (clk_i, rst_i, req_num_i, seed_sel_i, num_to_send_o);
  input clk_i;
  wire clk_i;
  input rst_i;
  wire rst_i;
  input req_num_i;
  wire req_num_i;
  input [1:0] seed_sel_i;
  wire [1:0] seed_sel_i;
  output [2:0] num_to_send_o;
  wire [2:0] num_to_send_o;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire [2:0] _09_;
  wire [2:0] _10_;
  wire [2:0] _11_;
  wire [2:0] _12_;
  wire [2:0] _13_;
  wire [2:0] _14_;
  wire [2:0] _15_;
  wire [8:0] _16_;
  wire [8:0] _17_;
  wire [2:0] _18_;
  wire [2:0] _19_;
  wire [2:0] _20_;
  wire _21_;
  wire [2:0] next_num;
  wire [2:0] num_to_send;
  \$_DFFE_PN0P_  \next_num_reg[0]  /* _22_ */ (
    .C(clk_i),
    .D(_19_[0]),
    .E(req_num_i),
    .Q(next_num[0]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \next_num_reg[1]  /* _23_ */ (
    .C(clk_i),
    .D(_19_[1]),
    .E(req_num_i),
    .Q(next_num[1]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \next_num_reg[2]  /* _24_ */ (
    .C(clk_i),
    .D(_19_[2]),
    .E(req_num_i),
    .Q(next_num[2]),
    .R(rst_i)
  );
  \$_NOT_  _25_ (
    .A(seed_sel_i[1]),
    .Y(_00_)
  );
  \$_NOT_  _26_ (
    .A(seed_sel_i[0]),
    .Y(_01_)
  );
  \$_AND_  _27_ (
    .A(_16_[6]),
    .B(_18_[2]),
    .Y(_17_[6])
  );
  \$_AND_  _28_ (
    .A(_16_[7]),
    .B(_18_[2]),
    .Y(_17_[7])
  );
  \$_AND_  _29_ (
    .A(_16_[8]),
    .B(_18_[2]),
    .Y(_17_[8])
  );
  \$_AND_  _30_ (
    .A(_16_[3]),
    .B(_18_[1]),
    .Y(_17_[3])
  );
  \$_AND_  _31_ (
    .A(_16_[4]),
    .B(_18_[1]),
    .Y(_17_[4])
  );
  \$_AND_  _32_ (
    .A(_15_[0]),
    .B(_18_[1]),
    .Y(_17_[5])
  );
  \$_AND_  _33_ (
    .A(_16_[0]),
    .B(_18_[0]),
    .Y(_17_[0])
  );
  \$_AND_  _34_ (
    .A(_16_[1]),
    .B(_18_[0]),
    .Y(_17_[1])
  );
  \$_AND_  _35_ (
    .A(num_to_send[2]),
    .B(_18_[0]),
    .Y(_17_[2])
  );
  \$_OR_  _36_ (
    .A(seed_sel_i[0]),
    .B(_00_),
    .Y(_07_)
  );
  \$_OR_  _37_ (
    .A(_01_),
    .B(seed_sel_i[1]),
    .Y(_08_)
  );
  \$_OR_  _38_ (
    .A(_17_[2]),
    .B(_17_[5]),
    .Y(_02_)
  );
  \$_OR_  _39_ (
    .A(_02_),
    .B(_17_[8]),
    .Y(_20_[2])
  );
  \$_OR_  _40_ (
    .A(_17_[1]),
    .B(_17_[4]),
    .Y(_03_)
  );
  \$_OR_  _41_ (
    .A(_03_),
    .B(_17_[7]),
    .Y(_20_[1])
  );
  \$_OR_  _42_ (
    .A(_17_[0]),
    .B(_17_[3]),
    .Y(_04_)
  );
  \$_OR_  _43_ (
    .A(_04_),
    .B(_17_[6]),
    .Y(_20_[0])
  );
  \$_OR_  _44_ (
    .A(_18_[0]),
    .B(_18_[1]),
    .Y(_05_)
  );
  \$_OR_  _45_ (
    .A(_05_),
    .B(_18_[2]),
    .Y(_21_)
  );
  \$_OR_  _46_ (
    .A(seed_sel_i[0]),
    .B(seed_sel_i[1]),
    .Y(_06_)
  );
  \$_NOT_  _47_ (
    .A(_07_),
    .Y(_18_[0])
  );
  \$_NOT_  _48_ (
    .A(_08_),
    .Y(_18_[1])
  );
  \$_NOT_  _49_ (
    .A(_06_),
    .Y(_18_[2])
  );
  \$_NOT_  _50_ (
    .A(num_to_send[1]),
    .Y(_09_[1])
  );
  \$_MUX_  _51_ (
    .A(1'h0),
    .B(_11_[0]),
    .S(num_to_send[1]),
    .Y(_10_[2])
  );
  \$_MUX_  _52_ (
    .A(_11_[0]),
    .B(num_to_send[0]),
    .S(num_to_send[1]),
    .Y(_13_[0])
  );
  \$_MUX_  _53_ (
    .A(_11_[0]),
    .B(1'h1),
    .S(num_to_send[1]),
    .Y(_09_[0])
  );
  \$_MUX_  _54_ (
    .A(_09_[0]),
    .B(_12_[0]),
    .S(num_to_send[2]),
    .Y(_16_[3])
  );
  \$_MUX_  _55_ (
    .A(_10_[2]),
    .B(_09_[0]),
    .S(num_to_send[2]),
    .Y(_16_[4])
  );
  \$_MUX_  _56_ (
    .A(_11_[0]),
    .B(num_to_send[0]),
    .S(num_to_send[2]),
    .Y(_15_[0])
  );
  \$_NOT_  _57_ (
    .A(num_to_send[0]),
    .Y(_11_[0])
  );
  \$_MUX_  _58_ (
    .A(_09_[2]),
    .B(_10_[0]),
    .S(num_to_send[2]),
    .Y(_15_[1])
  );
  \$_MUX_  _59_ (
    .A(_10_[0]),
    .B(_14_[2]),
    .S(num_to_send[2]),
    .Y(_15_[2])
  );
  \$_MUX_  _60_ (
    .A(1'h1),
    .B(num_to_send[0]),
    .S(num_to_send[1]),
    .Y(_09_[2])
  );
  \$_MUX_  _61_ (
    .A(_09_[0]),
    .B(_10_[0]),
    .S(num_to_send[2]),
    .Y(_16_[6])
  );
  \$_MUX_  _62_ (
    .A(_09_[1]),
    .B(num_to_send[0]),
    .S(num_to_send[2]),
    .Y(_16_[7])
  );
  \$_MUX_  _63_ (
    .A(_09_[2]),
    .B(_10_[2]),
    .S(num_to_send[2]),
    .Y(_16_[8])
  );
  \$_MUX_  _64_ (
    .A(1'h0),
    .B(num_to_send[0]),
    .S(num_to_send[1]),
    .Y(_10_[0])
  );
  \$_MUX_  _65_ (
    .A(num_to_send[0]),
    .B(1'h1),
    .S(num_to_send[1]),
    .Y(_14_[2])
  );
  \$_MUX_  _66_ (
    .A(num_to_send[0]),
    .B(_13_[0]),
    .S(num_to_send[2]),
    .Y(_16_[0])
  );
  \$_MUX_  _67_ (
    .A(_09_[1]),
    .B(num_to_send[1]),
    .S(num_to_send[2]),
    .Y(_16_[1])
  );
  \$_MUX_  _68_ (
    .A(_11_[0]),
    .B(1'h0),
    .S(num_to_send[1]),
    .Y(_12_[0])
  );
  \$_MUX_  _69_ (
    .A(_15_[0]),
    .B(_20_[0]),
    .S(_21_),
    .Y(_19_[0])
  );
  \$_MUX_  _70_ (
    .A(_15_[1]),
    .B(_20_[1]),
    .S(_21_),
    .Y(_19_[1])
  );
  \$_MUX_  _71_ (
    .A(_15_[2]),
    .B(_20_[2]),
    .S(_21_),
    .Y(_19_[2])
  );
  rng_data_path_counter inst (
    .clk_i(clk_i),
    .next_num_o(num_to_send),
    .req_num_i(req_num_i),
    .rst_i(rst_i)
  );
  assign _10_[1] = num_to_send[0];
  assign _11_[2:1] = 2'h3;
  assign _12_[2:1] = { num_to_send[0], _09_[0] };
  assign _13_[2:1] = { 1'h1, num_to_send[1] };
  assign _14_[1:0] = { _10_[0], num_to_send[0] };
  assign { _16_[5], _16_[2] } = { _15_[0], num_to_send[2] };
  assign num_to_send_o = next_num;
endmodule

module \$paramod$54156aeb88216e1ed0a79a36b33881dba9f19205\rng_hs_dup_detector (clk_i, rst_i, req_num_i, data_i, wr_i, data_o, req_new_num_o);
  input clk_i;
  wire clk_i;
  input rst_i;
  wire rst_i;
  input req_num_i;
  wire req_num_i;
  input [2:0] data_i;
  wire [2:0] data_i;
  input wr_i;
  wire wr_i;
  output [2:0] data_o;
  wire [2:0] data_o;
  output req_new_num_o;
  wire req_new_num_o;
  wire _000_;
  wire [2:0] _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire [2:0] _021_;
  wire [2:0] _022_;
  wire [2:0] _023_;
  wire [2:0] _024_;
  wire [2:0] _025_;
  wire [2:0] _026_;
  wire [2:0] _027_;
  wire [2:0] _028_;
  wire [2:0] _029_;
  wire [2:0] _030_;
  wire [2:0] _031_;
  wire [2:0] _032_;
  wire [2:0] _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire [2:0] \mem[0] ;
  wire [2:0] \mem[10] ;
  wire [2:0] \mem[11] ;
  wire [2:0] \mem[1] ;
  wire [2:0] \mem[2] ;
  wire [2:0] \mem[3] ;
  wire [2:0] \mem[4] ;
  wire [2:0] \mem[5] ;
  wire [2:0] \mem[6] ;
  wire [2:0] \mem[7] ;
  wire [2:0] \mem[8] ;
  wire [2:0] \mem[9] ;
  wire [2:0] mem_0;
  wire [2:0] mem_1;
  wire [2:0] mem_10;
  wire [2:0] mem_11;
  wire [2:0] mem_2;
  wire [2:0] mem_3;
  wire [2:0] mem_4;
  wire [2:0] mem_5;
  wire [2:0] mem_6;
  wire [2:0] mem_7;
  wire [2:0] mem_8;
  wire [2:0] mem_9;
  wire rqn;
  wire [2:0] temp_mem;
  wire [11:0] vld;
  wire wr_dec;
  wire wr_ff1;
  wire wr_ff2;
  wire wr_ff2_d;
  wire x_state;
  \$_DFFE_PP_  \mem_reg[11][0]  /* _082_ */ (
    .C(clk_i),
    .D(\mem[10] [0]),
    .E(_002_),
    .Q(\mem[11] [0])
  );
  \$_DFFE_PP_  \mem_reg[11][1]  /* _083_ */ (
    .C(clk_i),
    .D(\mem[10] [1]),
    .E(_002_),
    .Q(\mem[11] [1])
  );
  \$_DFFE_PP_  \mem_reg[11][2]  /* _084_ */ (
    .C(clk_i),
    .D(\mem[10] [2]),
    .E(_002_),
    .Q(\mem[11] [2])
  );
  \$_SDFFCE_PP0P_  \data_o_reg[1]  /* _085_ */ (
    .C(clk_i),
    .D(temp_mem[1]),
    .E(rst_i),
    .Q(data_o[1]),
    .R(_004_)
  );
  \$_SDFFCE_PP0P_  \data_o_reg[2]  /* _086_ */ (
    .C(clk_i),
    .D(temp_mem[2]),
    .E(rst_i),
    .Q(data_o[2]),
    .R(_004_)
  );
  \$_DFFE_PN0P_  \vld_reg[0]  /* _087_ */ (
    .C(clk_i),
    .D(1'h1),
    .E(_003_),
    .Q(vld[0]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \vld_reg[1]  /* _088_ */ (
    .C(clk_i),
    .D(vld[0]),
    .E(_003_),
    .Q(vld[1]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \vld_reg[2]  /* _089_ */ (
    .C(clk_i),
    .D(vld[1]),
    .E(_003_),
    .Q(vld[2]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \vld_reg[3]  /* _090_ */ (
    .C(clk_i),
    .D(vld[2]),
    .E(_003_),
    .Q(vld[3]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \vld_reg[4]  /* _091_ */ (
    .C(clk_i),
    .D(vld[3]),
    .E(_003_),
    .Q(vld[4]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \vld_reg[5]  /* _092_ */ (
    .C(clk_i),
    .D(vld[4]),
    .E(_003_),
    .Q(vld[5]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \vld_reg[6]  /* _093_ */ (
    .C(clk_i),
    .D(vld[5]),
    .E(_003_),
    .Q(vld[6]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \vld_reg[7]  /* _094_ */ (
    .C(clk_i),
    .D(vld[6]),
    .E(_003_),
    .Q(vld[7]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \vld_reg[8]  /* _095_ */ (
    .C(clk_i),
    .D(vld[7]),
    .E(_003_),
    .Q(vld[8]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \vld_reg[9]  /* _096_ */ (
    .C(clk_i),
    .D(vld[8]),
    .E(_003_),
    .Q(vld[9]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \vld_reg[10]  /* _097_ */ (
    .C(clk_i),
    .D(vld[9]),
    .E(_003_),
    .Q(vld[10]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \vld_reg[11]  /* _098_ */ (
    .C(clk_i),
    .D(vld[10]),
    .E(_003_),
    .Q(vld[11]),
    .R(rst_i)
  );
  \$_DFFE_PP_  rqn_reg /* _099_ */ (
    .C(clk_i),
    .D(_000_),
    .E(rst_i),
    .Q(rqn)
  );
  \$_DFFE_PN0P_  \mem_reg[0][0]  /* _100_ */ (
    .C(clk_i),
    .D(temp_mem[0]),
    .E(_003_),
    .Q(\mem[0] [0]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \mem_reg[0][1]  /* _101_ */ (
    .C(clk_i),
    .D(temp_mem[1]),
    .E(_003_),
    .Q(\mem[0] [1]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \mem_reg[0][2]  /* _102_ */ (
    .C(clk_i),
    .D(temp_mem[2]),
    .E(_003_),
    .Q(\mem[0] [2]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \mem_reg[1][0]  /* _103_ */ (
    .C(clk_i),
    .D(\mem[0] [0]),
    .E(_003_),
    .Q(\mem[1] [0]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \mem_reg[1][1]  /* _104_ */ (
    .C(clk_i),
    .D(\mem[0] [1]),
    .E(_003_),
    .Q(\mem[1] [1]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \mem_reg[1][2]  /* _105_ */ (
    .C(clk_i),
    .D(\mem[0] [2]),
    .E(_003_),
    .Q(\mem[1] [2]),
    .R(rst_i)
  );
  \$_DFFE_PP_  \data_o_reg[0]  /* _106_ */ (
    .C(clk_i),
    .D(temp_mem[0]),
    .E(rst_i),
    .Q(data_o[0])
  );
  \$_DFFE_PN0P_  \mem_reg[2][0]  /* _107_ */ (
    .C(clk_i),
    .D(\mem[1] [0]),
    .E(_003_),
    .Q(\mem[2] [0]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \mem_reg[2][1]  /* _108_ */ (
    .C(clk_i),
    .D(\mem[1] [1]),
    .E(_003_),
    .Q(\mem[2] [1]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \mem_reg[2][2]  /* _109_ */ (
    .C(clk_i),
    .D(\mem[1] [2]),
    .E(_003_),
    .Q(\mem[2] [2]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \mem_reg[3][0]  /* _110_ */ (
    .C(clk_i),
    .D(\mem[2] [0]),
    .E(_003_),
    .Q(\mem[3] [0]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \mem_reg[3][1]  /* _111_ */ (
    .C(clk_i),
    .D(\mem[2] [1]),
    .E(_003_),
    .Q(\mem[3] [1]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \mem_reg[3][2]  /* _112_ */ (
    .C(clk_i),
    .D(\mem[2] [2]),
    .E(_003_),
    .Q(\mem[3] [2]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \mem_reg[4][0]  /* _113_ */ (
    .C(clk_i),
    .D(\mem[3] [0]),
    .E(_003_),
    .Q(\mem[4] [0]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \mem_reg[4][1]  /* _114_ */ (
    .C(clk_i),
    .D(\mem[3] [1]),
    .E(_003_),
    .Q(\mem[4] [1]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \mem_reg[4][2]  /* _115_ */ (
    .C(clk_i),
    .D(\mem[3] [2]),
    .E(_003_),
    .Q(\mem[4] [2]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \mem_reg[5][0]  /* _116_ */ (
    .C(clk_i),
    .D(\mem[4] [0]),
    .E(_003_),
    .Q(\mem[5] [0]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \mem_reg[5][1]  /* _117_ */ (
    .C(clk_i),
    .D(\mem[4] [1]),
    .E(_003_),
    .Q(\mem[5] [1]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \mem_reg[5][2]  /* _118_ */ (
    .C(clk_i),
    .D(\mem[4] [2]),
    .E(_003_),
    .Q(\mem[5] [2]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \mem_reg[6][0]  /* _119_ */ (
    .C(clk_i),
    .D(\mem[5] [0]),
    .E(_003_),
    .Q(\mem[6] [0]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \mem_reg[6][1]  /* _120_ */ (
    .C(clk_i),
    .D(\mem[5] [1]),
    .E(_003_),
    .Q(\mem[6] [1]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \mem_reg[6][2]  /* _121_ */ (
    .C(clk_i),
    .D(\mem[5] [2]),
    .E(_003_),
    .Q(\mem[6] [2]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \mem_reg[7][0]  /* _122_ */ (
    .C(clk_i),
    .D(\mem[6] [0]),
    .E(_003_),
    .Q(\mem[7] [0]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \mem_reg[7][1]  /* _123_ */ (
    .C(clk_i),
    .D(\mem[6] [1]),
    .E(_003_),
    .Q(\mem[7] [1]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \mem_reg[7][2]  /* _124_ */ (
    .C(clk_i),
    .D(\mem[6] [2]),
    .E(_003_),
    .Q(\mem[7] [2]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \mem_reg[8][0]  /* _125_ */ (
    .C(clk_i),
    .D(\mem[7] [0]),
    .E(_003_),
    .Q(\mem[8] [0]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \mem_reg[8][1]  /* _126_ */ (
    .C(clk_i),
    .D(\mem[7] [1]),
    .E(_003_),
    .Q(\mem[8] [1]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \mem_reg[8][2]  /* _127_ */ (
    .C(clk_i),
    .D(\mem[7] [2]),
    .E(_003_),
    .Q(\mem[8] [2]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \mem_reg[9][0]  /* _128_ */ (
    .C(clk_i),
    .D(\mem[8] [0]),
    .E(_003_),
    .Q(\mem[9] [0]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \mem_reg[9][1]  /* _129_ */ (
    .C(clk_i),
    .D(\mem[8] [1]),
    .E(_003_),
    .Q(\mem[9] [1]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \mem_reg[9][2]  /* _130_ */ (
    .C(clk_i),
    .D(\mem[8] [2]),
    .E(_003_),
    .Q(\mem[9] [2]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \mem_reg[10][0]  /* _131_ */ (
    .C(clk_i),
    .D(\mem[9] [0]),
    .E(_003_),
    .Q(\mem[10] [0]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \mem_reg[10][1]  /* _132_ */ (
    .C(clk_i),
    .D(\mem[9] [1]),
    .E(_003_),
    .Q(\mem[10] [1]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \mem_reg[10][2]  /* _133_ */ (
    .C(clk_i),
    .D(\mem[9] [2]),
    .E(_003_),
    .Q(\mem[10] [2]),
    .R(rst_i)
  );
  \$_DFF_PN0_  wr_ff1_reg /* _134_ */ (
    .C(clk_i),
    .D(wr_i),
    .Q(wr_ff1),
    .R(rst_i)
  );
  \$_DFF_PN0_  wr_ff2_reg /* _135_ */ (
    .C(clk_i),
    .D(wr_ff1),
    .Q(wr_ff2),
    .R(rst_i)
  );
  \$_DFF_PN0_  wr_ff2_d_reg /* _136_ */ (
    .C(clk_i),
    .D(wr_ff2),
    .Q(wr_ff2_d),
    .R(rst_i)
  );
  \$_XOR_  _137_ (
    .A(data_i[0]),
    .B(\mem[8] [0]),
    .Y(_021_[0])
  );
  \$_XOR_  _138_ (
    .A(data_i[1]),
    .B(\mem[8] [1]),
    .Y(_021_[1])
  );
  \$_XOR_  _139_ (
    .A(data_i[2]),
    .B(\mem[8] [2]),
    .Y(_021_[2])
  );
  \$_XOR_  _140_ (
    .A(data_i[0]),
    .B(\mem[9] [0]),
    .Y(_022_[0])
  );
  \$_XOR_  _141_ (
    .A(data_i[1]),
    .B(\mem[9] [1]),
    .Y(_022_[1])
  );
  \$_XOR_  _142_ (
    .A(data_i[2]),
    .B(\mem[9] [2]),
    .Y(_022_[2])
  );
  \$_XOR_  _143_ (
    .A(data_i[0]),
    .B(\mem[10] [0]),
    .Y(_023_[0])
  );
  \$_XOR_  _144_ (
    .A(data_i[1]),
    .B(\mem[10] [1]),
    .Y(_023_[1])
  );
  \$_XOR_  _145_ (
    .A(data_i[2]),
    .B(\mem[10] [2]),
    .Y(_023_[2])
  );
  \$_XOR_  _146_ (
    .A(data_i[0]),
    .B(\mem[11] [0]),
    .Y(_024_[0])
  );
  \$_XOR_  _147_ (
    .A(data_i[1]),
    .B(\mem[11] [1]),
    .Y(_024_[1])
  );
  \$_XOR_  _148_ (
    .A(data_i[2]),
    .B(\mem[11] [2]),
    .Y(_024_[2])
  );
  \$_XOR_  _149_ (
    .A(data_o[0]),
    .B(temp_mem[0]),
    .Y(_025_[0])
  );
  \$_XOR_  _150_ (
    .A(data_o[1]),
    .B(temp_mem[1]),
    .Y(_025_[1])
  );
  \$_XOR_  _151_ (
    .A(data_o[2]),
    .B(temp_mem[2]),
    .Y(_025_[2])
  );
  \$_AND_  _152_ (
    .A(wr_ff2),
    .B(_081_),
    .Y(wr_dec)
  );
  \$_AND_  _153_ (
    .A(rqn),
    .B(req_num_i),
    .Y(req_new_num_o)
  );
  \$_XOR_  _154_ (
    .A(data_i[0]),
    .B(\mem[0] [0]),
    .Y(_026_[0])
  );
  \$_XOR_  _155_ (
    .A(data_i[1]),
    .B(\mem[0] [1]),
    .Y(_026_[1])
  );
  \$_XOR_  _156_ (
    .A(data_i[2]),
    .B(\mem[0] [2]),
    .Y(_026_[2])
  );
  \$_XOR_  _157_ (
    .A(data_i[0]),
    .B(\mem[1] [0]),
    .Y(_027_[0])
  );
  \$_XOR_  _158_ (
    .A(data_i[1]),
    .B(\mem[1] [1]),
    .Y(_027_[1])
  );
  \$_XOR_  _159_ (
    .A(data_i[2]),
    .B(\mem[1] [2]),
    .Y(_027_[2])
  );
  \$_XOR_  _160_ (
    .A(data_i[0]),
    .B(\mem[2] [0]),
    .Y(_028_[0])
  );
  \$_XOR_  _161_ (
    .A(data_i[1]),
    .B(\mem[2] [1]),
    .Y(_028_[1])
  );
  \$_XOR_  _162_ (
    .A(data_i[2]),
    .B(\mem[2] [2]),
    .Y(_028_[2])
  );
  \$_XOR_  _163_ (
    .A(data_i[0]),
    .B(\mem[3] [0]),
    .Y(_029_[0])
  );
  \$_XOR_  _164_ (
    .A(data_i[1]),
    .B(\mem[3] [1]),
    .Y(_029_[1])
  );
  \$_XOR_  _165_ (
    .A(data_i[2]),
    .B(\mem[3] [2]),
    .Y(_029_[2])
  );
  \$_XOR_  _166_ (
    .A(data_i[0]),
    .B(\mem[4] [0]),
    .Y(_030_[0])
  );
  \$_XOR_  _167_ (
    .A(data_i[1]),
    .B(\mem[4] [1]),
    .Y(_030_[1])
  );
  \$_XOR_  _168_ (
    .A(data_i[2]),
    .B(\mem[4] [2]),
    .Y(_030_[2])
  );
  \$_XOR_  _169_ (
    .A(data_i[0]),
    .B(\mem[5] [0]),
    .Y(_031_[0])
  );
  \$_XOR_  _170_ (
    .A(data_i[1]),
    .B(\mem[5] [1]),
    .Y(_031_[1])
  );
  \$_XOR_  _171_ (
    .A(data_i[2]),
    .B(\mem[5] [2]),
    .Y(_031_[2])
  );
  \$_XOR_  _172_ (
    .A(data_i[0]),
    .B(\mem[6] [0]),
    .Y(_032_[0])
  );
  \$_XOR_  _173_ (
    .A(data_i[1]),
    .B(\mem[6] [1]),
    .Y(_032_[1])
  );
  \$_XOR_  _174_ (
    .A(data_i[2]),
    .B(\mem[6] [2]),
    .Y(_032_[2])
  );
  \$_XOR_  _175_ (
    .A(data_i[0]),
    .B(\mem[7] [0]),
    .Y(_033_[0])
  );
  \$_XOR_  _176_ (
    .A(data_i[1]),
    .B(\mem[7] [1]),
    .Y(_033_[1])
  );
  \$_XOR_  _177_ (
    .A(data_i[2]),
    .B(\mem[7] [2]),
    .Y(_033_[2])
  );
  \$_OR_  _178_ (
    .A(_033_[0]),
    .B(_033_[1]),
    .Y(_007_)
  );
  \$_OR_  _179_ (
    .A(_007_),
    .B(_033_[2]),
    .Y(_046_)
  );
  \$_OR_  _180_ (
    .A(_021_[0]),
    .B(_021_[1]),
    .Y(_008_)
  );
  \$_OR_  _181_ (
    .A(_008_),
    .B(_021_[2]),
    .Y(_034_)
  );
  \$_OR_  _182_ (
    .A(_022_[0]),
    .B(_022_[1]),
    .Y(_009_)
  );
  \$_OR_  _183_ (
    .A(_009_),
    .B(_022_[2]),
    .Y(_035_)
  );
  \$_OR_  _184_ (
    .A(_023_[0]),
    .B(_023_[1]),
    .Y(_010_)
  );
  \$_OR_  _185_ (
    .A(_010_),
    .B(_023_[2]),
    .Y(_036_)
  );
  \$_OR_  _186_ (
    .A(_024_[0]),
    .B(_024_[1]),
    .Y(_011_)
  );
  \$_OR_  _187_ (
    .A(_011_),
    .B(_024_[2]),
    .Y(_037_)
  );
  \$_OR_  _188_ (
    .A(_025_[0]),
    .B(_025_[1]),
    .Y(_012_)
  );
  \$_OR_  _189_ (
    .A(_012_),
    .B(_025_[2]),
    .Y(_038_)
  );
  \$_OR_  _190_ (
    .A(_000_),
    .B(_006_),
    .Y(_004_)
  );
  \$_AND_  _191_ (
    .A(rst_i),
    .B(_005_),
    .Y(_013_)
  );
  \$_AND_  _192_ (
    .A(_013_),
    .B(wr_dec),
    .Y(_002_)
  );
  \$_AND_  _193_ (
    .A(_005_),
    .B(wr_dec),
    .Y(_003_)
  );
  \$_OR_  _194_ (
    .A(_026_[0]),
    .B(_026_[1]),
    .Y(_014_)
  );
  \$_OR_  _195_ (
    .A(_014_),
    .B(_026_[2]),
    .Y(_039_)
  );
  \$_OR_  _196_ (
    .A(_027_[0]),
    .B(_027_[1]),
    .Y(_015_)
  );
  \$_OR_  _197_ (
    .A(_015_),
    .B(_027_[2]),
    .Y(_040_)
  );
  \$_OR_  _198_ (
    .A(_028_[0]),
    .B(_028_[1]),
    .Y(_016_)
  );
  \$_OR_  _199_ (
    .A(_016_),
    .B(_028_[2]),
    .Y(_041_)
  );
  \$_OR_  _200_ (
    .A(_029_[0]),
    .B(_029_[1]),
    .Y(_017_)
  );
  \$_OR_  _201_ (
    .A(_017_),
    .B(_029_[2]),
    .Y(_042_)
  );
  \$_OR_  _202_ (
    .A(_030_[0]),
    .B(_030_[1]),
    .Y(_018_)
  );
  \$_OR_  _203_ (
    .A(_018_),
    .B(_030_[2]),
    .Y(_043_)
  );
  \$_OR_  _204_ (
    .A(_031_[0]),
    .B(_031_[1]),
    .Y(_019_)
  );
  \$_OR_  _205_ (
    .A(_019_),
    .B(_031_[2]),
    .Y(_044_)
  );
  \$_OR_  _206_ (
    .A(_032_[0]),
    .B(_032_[1]),
    .Y(_020_)
  );
  \$_OR_  _207_ (
    .A(_020_),
    .B(_032_[2]),
    .Y(_045_)
  );
  \$_NOT_  _208_ (
    .A(_046_),
    .Y(_054_)
  );
  \$_NOT_  _209_ (
    .A(_034_),
    .Y(_055_)
  );
  \$_NOT_  _210_ (
    .A(_035_),
    .Y(_056_)
  );
  \$_NOT_  _211_ (
    .A(_036_),
    .Y(_057_)
  );
  \$_NOT_  _212_ (
    .A(_037_),
    .Y(_058_)
  );
  \$_NOT_  _213_ (
    .A(_039_),
    .Y(_047_)
  );
  \$_NOT_  _214_ (
    .A(_040_),
    .Y(_048_)
  );
  \$_NOT_  _215_ (
    .A(_041_),
    .Y(_049_)
  );
  \$_NOT_  _216_ (
    .A(_042_),
    .Y(_050_)
  );
  \$_NOT_  _217_ (
    .A(_043_),
    .Y(_051_)
  );
  \$_NOT_  _218_ (
    .A(_044_),
    .Y(_052_)
  );
  \$_NOT_  _219_ (
    .A(_045_),
    .Y(_053_)
  );
  \$_AND_  _220_ (
    .A(vld[7]),
    .B(_054_),
    .Y(_066_)
  );
  \$_OR_  _221_ (
    .A(_079_),
    .B(_066_),
    .Y(_080_)
  );
  \$_AND_  _222_ (
    .A(vld[8]),
    .B(_055_),
    .Y(_067_)
  );
  \$_OR_  _223_ (
    .A(_080_),
    .B(_067_),
    .Y(_071_)
  );
  \$_AND_  _224_ (
    .A(vld[9]),
    .B(_056_),
    .Y(_068_)
  );
  \$_OR_  _225_ (
    .A(_071_),
    .B(_068_),
    .Y(_072_)
  );
  \$_AND_  _226_ (
    .A(vld[10]),
    .B(_057_),
    .Y(_069_)
  );
  \$_OR_  _227_ (
    .A(_072_),
    .B(_069_),
    .Y(_073_)
  );
  \$_AND_  _228_ (
    .A(vld[11]),
    .B(_058_),
    .Y(_070_)
  );
  \$_OR_  _229_ (
    .A(_073_),
    .B(_070_),
    .Y(_000_)
  );
  \$_AND_  _230_ (
    .A(vld[0]),
    .B(_047_),
    .Y(_059_)
  );
  \$_AND_  _231_ (
    .A(vld[1]),
    .B(_048_),
    .Y(_060_)
  );
  \$_OR_  _232_ (
    .A(_059_),
    .B(_060_),
    .Y(_074_)
  );
  \$_AND_  _233_ (
    .A(vld[2]),
    .B(_049_),
    .Y(_061_)
  );
  \$_OR_  _234_ (
    .A(_074_),
    .B(_061_),
    .Y(_075_)
  );
  \$_AND_  _235_ (
    .A(vld[3]),
    .B(_050_),
    .Y(_062_)
  );
  \$_OR_  _236_ (
    .A(_075_),
    .B(_062_),
    .Y(_076_)
  );
  \$_AND_  _237_ (
    .A(vld[4]),
    .B(_051_),
    .Y(_063_)
  );
  \$_OR_  _238_ (
    .A(_076_),
    .B(_063_),
    .Y(_077_)
  );
  \$_AND_  _239_ (
    .A(vld[5]),
    .B(_052_),
    .Y(_064_)
  );
  \$_OR_  _240_ (
    .A(_077_),
    .B(_064_),
    .Y(_078_)
  );
  \$_AND_  _241_ (
    .A(vld[6]),
    .B(_053_),
    .Y(_065_)
  );
  \$_OR_  _242_ (
    .A(_078_),
    .B(_065_),
    .Y(_079_)
  );
  \$_MUX_  _243_ (
    .A(1'h0),
    .B(data_i[0]),
    .S(_038_),
    .Y(_001_[0])
  );
  \$_MUX_  _244_ (
    .A(1'h0),
    .B(data_i[1]),
    .S(_038_),
    .Y(_001_[1])
  );
  \$_MUX_  _245_ (
    .A(1'h0),
    .B(data_i[2]),
    .S(_038_),
    .Y(_001_[2])
  );
  \$_MUX_  _246_ (
    .A(_001_[0]),
    .B(1'h0),
    .S(_000_),
    .Y(temp_mem[0])
  );
  \$_MUX_  _247_ (
    .A(_001_[1]),
    .B(1'h0),
    .S(_000_),
    .Y(temp_mem[1])
  );
  \$_MUX_  _248_ (
    .A(_001_[2]),
    .B(1'h0),
    .S(_000_),
    .Y(temp_mem[2])
  );
  \$_NOT_  _249_ (
    .A(wr_ff2_d),
    .Y(_081_)
  );
  \$_NOT_  _250_ (
    .A(wr_dec),
    .Y(_006_)
  );
  \$_NOT_  _251_ (
    .A(_000_),
    .Y(_005_)
  );
  assign mem_0 = \mem[0] ;
  assign mem_1 = \mem[1] ;
  assign mem_10 = \mem[10] ;
  assign mem_11 = \mem[11] ;
  assign mem_2 = \mem[2] ;
  assign mem_3 = \mem[3] ;
  assign mem_4 = \mem[4] ;
  assign mem_5 = \mem[5] ;
  assign mem_6 = \mem[6] ;
  assign mem_7 = \mem[7] ;
  assign mem_8 = \mem[8] ;
  assign mem_9 = \mem[9] ;
  assign x_state = 1'hx;
endmodule

module \$paramod$54156aeb88216e1ed0a79a36b33881dba9f19205\rng_selector (clk_i, start_i, rst_i, seed_sel_o);
  input clk_i;
  wire clk_i;
  input start_i;
  wire start_i;
  input rst_i;
  wire rst_i;
  output [1:0] seed_sel_o;
  wire [1:0] seed_sel_o;
  wire [1:0] _0_;
  wire [1:0] _1_;
  wire [1:0] seed_s;
  \$_DFF_PN0_  \seed_s_reg[0]  /* _2_ */ (
    .C(clk_i),
    .D(_0_[0]),
    .Q(seed_s[0]),
    .R(rst_i)
  );
  \$_DFF_PN0_  \seed_s_reg[1]  /* _3_ */ (
    .C(clk_i),
    .D(_1_[1]),
    .Q(seed_s[1]),
    .R(rst_i)
  );
  \$_NOT_  _4_ (
    .A(seed_s[0]),
    .Y(_0_[0])
  );
  \$_XOR_  _5_ (
    .A(seed_s[1]),
    .B(seed_s[0]),
    .Y(_1_[1])
  );
  assign _0_[1] = seed_s[1];
  assign _1_[0] = _0_[0];
  assign seed_sel_o = seed_s;
endmodule

module rng_data_path_counter(clk_i, rst_i, req_num_i, next_num_o);
  input clk_i;
  wire clk_i;
  input rst_i;
  wire rst_i;
  input req_num_i;
  wire req_num_i;
  output [2:0] next_num_o;
  wire [2:0] next_num_o;
  wire [2:0] _00_;
  wire [2:0] _01_;
  wire [2:0] _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire [2:0] _07_;
  wire [2:0] num_counter;
  \$_DFFE_PN0P_  \num_counter_reg[0]  /* _08_ */ (
    .C(clk_i),
    .D(_07_[0]),
    .E(req_num_i),
    .Q(num_counter[0]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \num_counter_reg[1]  /* _09_ */ (
    .C(clk_i),
    .D(_07_[1]),
    .E(req_num_i),
    .Q(num_counter[1]),
    .R(rst_i)
  );
  \$_DFFE_PN0P_  \num_counter_reg[2]  /* _10_ */ (
    .C(clk_i),
    .D(_07_[2]),
    .E(req_num_i),
    .Q(num_counter[2]),
    .R(rst_i)
  );
  \$_NOT_  _11_ (
    .A(num_counter[0]),
    .Y(_01_[0])
  );
  \$_NOT_  _12_ (
    .A(num_counter[2]),
    .Y(_04_)
  );
  \$_XOR_  _13_ (
    .A(num_counter[1]),
    .B(num_counter[0]),
    .Y(_02_[1])
  );
  \$_XOR_  _14_ (
    .A(num_counter[2]),
    .B(_00_[1]),
    .Y(_02_[2])
  );
  \$_AND_  _15_ (
    .A(num_counter[1]),
    .B(num_counter[0]),
    .Y(_00_[1])
  );
  \$_OR_  _16_ (
    .A(_01_[0]),
    .B(_03_),
    .Y(_05_)
  );
  \$_OR_  _17_ (
    .A(_05_),
    .B(_04_),
    .Y(_06_)
  );
  \$_MUX_  _18_ (
    .A(1'h0),
    .B(_01_[0]),
    .S(_06_),
    .Y(_07_[0])
  );
  \$_MUX_  _19_ (
    .A(1'h0),
    .B(_02_[1]),
    .S(_06_),
    .Y(_07_[1])
  );
  \$_MUX_  _20_ (
    .A(1'h0),
    .B(_02_[2]),
    .S(_06_),
    .Y(_07_[2])
  );
  \$_NOT_  _21_ (
    .A(num_counter[1]),
    .Y(_03_)
  );
  assign _00_[0] = num_counter[0];
  assign _01_[2:1] = num_counter[2:1];
  assign _02_[0] = _01_[0];
  assign next_num_o = num_counter;
endmodule

module rng_top(clk_i, start_i, rst_i, req_num_i, wr_i, num_to_send_o);
  input clk_i;
  wire clk_i;
  input start_i;
  wire start_i;
  input rst_i;
  wire rst_i;
  input req_num_i;
  wire req_num_i;
  input wr_i;
  wire wr_i;
  output [2:0] num_to_send_o;
  wire [2:0] num_to_send_o;
  wire [2:0] num_i_bar;
  wire req_num;
  wire req_num_again;
  wire [1:0] seed_bar;
  \$_OR_  _0_ (
    .A(req_num_i),
    .B(req_num_again),
    .Y(req_num)
  );
  \$paramod$54156aeb88216e1ed0a79a36b33881dba9f19205\rng_data_path  rng_dp (
    .clk_i(clk_i),
    .num_to_send_o(num_i_bar),
    .req_num_i(req_num),
    .rst_i(rst_i),
    .seed_sel_i(seed_bar)
  );
  \$paramod$54156aeb88216e1ed0a79a36b33881dba9f19205\rng_hs_dup_detector  rng_rd (
    .clk_i(clk_i),
    .data_i(num_i_bar),
    .data_o(num_to_send_o),
    .req_new_num_o(req_num_again),
    .req_num_i(req_num),
    .rst_i(rst_i),
    .wr_i(wr_i)
  );
  \$paramod$54156aeb88216e1ed0a79a36b33881dba9f19205\rng_selector  rng_sel (
    .clk_i(clk_i),
    .rst_i(rst_i),
    .seed_sel_o(seed_bar),
    .start_i(start_i)
  );
endmodule
