/* Generated by Yosys 0.46 (git sha1 e97731b9dda91fa5fa53ed87df7c34163ba59a41, clang++ 17.0.6 -fPIC -O3) */

module rng_top(clk_i, rst_i, req_num_i, wr_i, num_to_send_o);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  input clk_i;
  wire clk_i;
  wire \num_i_bar[0] ;
  wire \num_i_bar[1] ;
  wire \num_i_bar[2] ;
  output [2:0] num_to_send_o;
  wire [2:0] num_to_send_o;
  wire req_num_again;
  input req_num_i;
  wire req_num_i;
  wire \rng_dp.inst.next_num_o[0] ;
  wire \rng_dp.inst.next_num_o[1] ;
  wire \rng_dp.inst.next_num_o[2] ;
  wire \rng_dp.seed_sel_i[0] ;
  wire \rng_dp.seed_sel_i[1] ;
  wire \rng_rd.mem[10][0] ;
  wire \rng_rd.mem[10][1] ;
  wire \rng_rd.mem[10][2] ;
  wire \rng_rd.mem[11][0] ;
  wire \rng_rd.mem[11][1] ;
  wire \rng_rd.mem[11][2] ;
  wire \rng_rd.mem[1][0] ;
  wire \rng_rd.mem[1][1] ;
  wire \rng_rd.mem[1][2] ;
  wire \rng_rd.mem[2][0] ;
  wire \rng_rd.mem[2][1] ;
  wire \rng_rd.mem[2][2] ;
  wire \rng_rd.mem[3][0] ;
  wire \rng_rd.mem[3][1] ;
  wire \rng_rd.mem[3][2] ;
  wire \rng_rd.mem[4][0] ;
  wire \rng_rd.mem[4][1] ;
  wire \rng_rd.mem[4][2] ;
  wire \rng_rd.mem[5][0] ;
  wire \rng_rd.mem[5][1] ;
  wire \rng_rd.mem[5][2] ;
  wire \rng_rd.mem[6][0] ;
  wire \rng_rd.mem[6][1] ;
  wire \rng_rd.mem[6][2] ;
  wire \rng_rd.mem[7][0] ;
  wire \rng_rd.mem[7][1] ;
  wire \rng_rd.mem[7][2] ;
  wire \rng_rd.mem[8][0] ;
  wire \rng_rd.mem[8][1] ;
  wire \rng_rd.mem[8][2] ;
  wire \rng_rd.mem[9][0] ;
  wire \rng_rd.mem[9][1] ;
  wire \rng_rd.mem[9][2] ;
  wire \rng_rd.vld[0] ;
  wire \rng_rd.vld[10] ;
  wire \rng_rd.vld[11] ;
  wire \rng_rd.vld[1] ;
  wire \rng_rd.vld[2] ;
  wire \rng_rd.vld[3] ;
  wire \rng_rd.vld[4] ;
  wire \rng_rd.vld[5] ;
  wire \rng_rd.vld[6] ;
  wire \rng_rd.vld[7] ;
  wire \rng_rd.vld[8] ;
  wire \rng_rd.vld[9] ;
  wire \rng_rd.wr_ff1 ;
  wire \rng_rd.wr_ff2 ;
  wire \rng_rd.wr_ff2_d ;
  wire \rng_rd.wr_pulse ;
  input rst_i;
  wire rst_i;
  input wr_i;
  wire wr_i;
  sky130_fd_sc_hd__inv_2 _166_ (
    .A(\num_i_bar[0] ),
    .Y(_057_)
  );
  sky130_fd_sc_hd__inv_2 _167_ (
    .A(\rng_rd.mem[7][1] ),
    .Y(_058_)
  );
  sky130_fd_sc_hd__inv_2 _168_ (
    .A(\num_i_bar[1] ),
    .Y(_059_)
  );
  sky130_fd_sc_hd__inv_2 _169_ (
    .A(\num_i_bar[2] ),
    .Y(_060_)
  );
  sky130_fd_sc_hd__inv_2 _170_ (
    .A(\rng_rd.mem[9][0] ),
    .Y(_061_)
  );
  sky130_fd_sc_hd__inv_2 _171_ (
    .A(\rng_rd.mem[10][1] ),
    .Y(_062_)
  );
  sky130_fd_sc_hd__inv_2 _172_ (
    .A(\rng_rd.vld[11] ),
    .Y(_063_)
  );
  sky130_fd_sc_hd__inv_2 _173_ (
    .A(\rng_dp.inst.next_num_o[0] ),
    .Y(_064_)
  );
  sky130_fd_sc_hd__inv_2 _174_ (
    .A(\rng_dp.inst.next_num_o[2] ),
    .Y(_065_)
  );
  sky130_fd_sc_hd__inv_2 _175_ (
    .A(\rng_dp.inst.next_num_o[1] ),
    .Y(_066_)
  );
  sky130_fd_sc_hd__inv_2 _176_ (
    .A(\rng_dp.seed_sel_i[0] ),
    .Y(_001_)
  );
  sky130_fd_sc_hd__inv_2 _177_ (
    .A(num_to_send_o[0]),
    .Y(_067_)
  );
  sky130_fd_sc_hd__inv_2 _178_ (
    .A(\rng_rd.mem[1][1] ),
    .Y(_068_)
  );
  sky130_fd_sc_hd__inv_2 _179_ (
    .A(\rng_rd.mem[3][0] ),
    .Y(_069_)
  );
  sky130_fd_sc_hd__inv_2 _180_ (
    .A(\rng_rd.mem[4][0] ),
    .Y(_070_)
  );
  sky130_fd_sc_hd__inv_2 _181_ (
    .A(\rng_rd.mem[5][0] ),
    .Y(_071_)
  );
  sky130_fd_sc_hd__inv_2 _182_ (
    .A(\rng_rd.mem[6][1] ),
    .Y(_072_)
  );
  sky130_fd_sc_hd__nand2_2 _183_ (
    .A(_059_),
    .B(\rng_rd.mem[4][1] ),
    .Y(_073_)
  );
  sky130_fd_sc_hd__o22a_2 _184_ (
    .A1(_057_),
    .A2(\rng_rd.mem[4][0] ),
    .B1(\rng_rd.mem[4][1] ),
    .B2(_059_),
    .X(_074_)
  );
  sky130_fd_sc_hd__and2_2 _185_ (
    .A(\num_i_bar[2] ),
    .B(\rng_rd.mem[4][2] ),
    .X(_075_)
  );
  sky130_fd_sc_hd__nor2_2 _186_ (
    .A(\num_i_bar[2] ),
    .B(\rng_rd.mem[4][2] ),
    .Y(_076_)
  );
  sky130_fd_sc_hd__o221a_2 _187_ (
    .A1(\num_i_bar[0] ),
    .A2(_070_),
    .B1(_075_),
    .B2(_076_),
    .C1(\rng_rd.vld[4] ),
    .X(_077_)
  );
  sky130_fd_sc_hd__and3_2 _188_ (
    .A(_073_),
    .B(_074_),
    .C(_077_),
    .X(_078_)
  );
  sky130_fd_sc_hd__nand2_2 _189_ (
    .A(\rng_rd.mem[7][0] ),
    .B(_057_),
    .Y(_079_)
  );
  sky130_fd_sc_hd__and2_2 _190_ (
    .A(\rng_rd.mem[7][2] ),
    .B(\num_i_bar[2] ),
    .X(_080_)
  );
  sky130_fd_sc_hd__nor2_2 _191_ (
    .A(\rng_rd.mem[7][2] ),
    .B(\num_i_bar[2] ),
    .Y(_081_)
  );
  sky130_fd_sc_hd__o22a_2 _192_ (
    .A1(\rng_rd.mem[7][0] ),
    .A2(_057_),
    .B1(\rng_rd.mem[7][1] ),
    .B2(_059_),
    .X(_082_)
  );
  sky130_fd_sc_hd__o221a_2 _193_ (
    .A1(_058_),
    .A2(\num_i_bar[1] ),
    .B1(_080_),
    .B2(_081_),
    .C1(\rng_rd.vld[7] ),
    .X(_083_)
  );
  sky130_fd_sc_hd__and3_2 _194_ (
    .A(_079_),
    .B(_082_),
    .C(_083_),
    .X(_084_)
  );
  sky130_fd_sc_hd__a22oi_2 _195_ (
    .A1(_057_),
    .A2(\rng_rd.mem[2][0] ),
    .B1(\rng_rd.mem[2][1] ),
    .B2(_059_),
    .Y(_085_)
  );
  sky130_fd_sc_hd__and2_2 _196_ (
    .A(\num_i_bar[2] ),
    .B(\rng_rd.mem[2][2] ),
    .X(_086_)
  );
  sky130_fd_sc_hd__nor2_2 _197_ (
    .A(\num_i_bar[2] ),
    .B(\rng_rd.mem[2][2] ),
    .Y(_087_)
  );
  sky130_fd_sc_hd__o221a_2 _198_ (
    .A1(_059_),
    .A2(\rng_rd.mem[2][1] ),
    .B1(_086_),
    .B2(_087_),
    .C1(\rng_rd.vld[2] ),
    .X(_088_)
  );
  sky130_fd_sc_hd__o211a_2 _199_ (
    .A1(_057_),
    .A2(\rng_rd.mem[2][0] ),
    .B1(_085_),
    .C1(_088_),
    .X(_089_)
  );
  sky130_fd_sc_hd__o2bb2a_2 _200_ (
    .A1_N(_057_),
    .A2_N(\rng_rd.mem[10][0] ),
    .B1(\rng_rd.mem[10][1] ),
    .B2(_059_),
    .X(_090_)
  );
  sky130_fd_sc_hd__and2_2 _201_ (
    .A(\num_i_bar[2] ),
    .B(\rng_rd.mem[10][2] ),
    .X(_091_)
  );
  sky130_fd_sc_hd__nor2_2 _202_ (
    .A(\num_i_bar[2] ),
    .B(\rng_rd.mem[10][2] ),
    .Y(_092_)
  );
  sky130_fd_sc_hd__o221a_2 _203_ (
    .A1(_057_),
    .A2(\rng_rd.mem[10][0] ),
    .B1(_091_),
    .B2(_092_),
    .C1(\rng_rd.vld[10] ),
    .X(_093_)
  );
  sky130_fd_sc_hd__o211a_2 _204_ (
    .A1(\num_i_bar[1] ),
    .A2(_062_),
    .B1(_090_),
    .C1(_093_),
    .X(_094_)
  );
  sky130_fd_sc_hd__nor4_2 _205_ (
    .A(_078_),
    .B(_084_),
    .C(_089_),
    .D(_094_),
    .Y(_095_)
  );
  sky130_fd_sc_hd__xor2_2 _206_ (
    .A(\num_i_bar[2] ),
    .B(num_to_send_o[2]),
    .X(_096_)
  );
  sky130_fd_sc_hd__a22o_2 _207_ (
    .A1(\num_i_bar[0] ),
    .A2(_067_),
    .B1(num_to_send_o[1]),
    .B2(_059_),
    .X(_097_)
  );
  sky130_fd_sc_hd__o221a_2 _208_ (
    .A1(\num_i_bar[0] ),
    .A2(_067_),
    .B1(num_to_send_o[1]),
    .B2(_059_),
    .C1(\rng_rd.vld[0] ),
    .X(_098_)
  );
  sky130_fd_sc_hd__or3b_2 _209_ (
    .A(_096_),
    .B(_097_),
    .C_N(_098_),
    .X(_099_)
  );
  sky130_fd_sc_hd__or2_2 _210_ (
    .A(\num_i_bar[1] ),
    .B(\rng_rd.mem[11][1] ),
    .X(_100_)
  );
  sky130_fd_sc_hd__nand2_2 _211_ (
    .A(\num_i_bar[1] ),
    .B(\rng_rd.mem[11][1] ),
    .Y(_101_)
  );
  sky130_fd_sc_hd__o22ai_2 _212_ (
    .A1(_057_),
    .A2(\rng_rd.mem[11][0] ),
    .B1(\rng_rd.mem[11][2] ),
    .B2(_060_),
    .Y(_102_)
  );
  sky130_fd_sc_hd__a221o_2 _213_ (
    .A1(_057_),
    .A2(\rng_rd.mem[11][0] ),
    .B1(_100_),
    .B2(_101_),
    .C1(_063_),
    .X(_103_)
  );
  sky130_fd_sc_hd__a211o_2 _214_ (
    .A1(_060_),
    .A2(\rng_rd.mem[11][2] ),
    .B1(_102_),
    .C1(_103_),
    .X(_104_)
  );
  sky130_fd_sc_hd__xor2_2 _215_ (
    .A(\num_i_bar[2] ),
    .B(\rng_rd.mem[6][2] ),
    .X(_105_)
  );
  sky130_fd_sc_hd__a22o_2 _216_ (
    .A1(_057_),
    .A2(\rng_rd.mem[6][0] ),
    .B1(_072_),
    .B2(\num_i_bar[1] ),
    .X(_106_)
  );
  sky130_fd_sc_hd__o221a_2 _217_ (
    .A1(_057_),
    .A2(\rng_rd.mem[6][0] ),
    .B1(_072_),
    .B2(\num_i_bar[1] ),
    .C1(\rng_rd.vld[6] ),
    .X(_107_)
  );
  sky130_fd_sc_hd__or3b_2 _218_ (
    .A(_105_),
    .B(_106_),
    .C_N(_107_),
    .X(_108_)
  );
  sky130_fd_sc_hd__xor2_2 _219_ (
    .A(\num_i_bar[2] ),
    .B(\rng_rd.mem[9][2] ),
    .X(_109_)
  );
  sky130_fd_sc_hd__a22o_2 _220_ (
    .A1(\num_i_bar[0] ),
    .A2(_061_),
    .B1(\rng_rd.mem[9][1] ),
    .B2(_059_),
    .X(_110_)
  );
  sky130_fd_sc_hd__o221a_2 _221_ (
    .A1(\num_i_bar[0] ),
    .A2(_061_),
    .B1(\rng_rd.mem[9][1] ),
    .B2(_059_),
    .C1(\rng_rd.vld[9] ),
    .X(_111_)
  );
  sky130_fd_sc_hd__or3b_2 _222_ (
    .A(_109_),
    .B(_110_),
    .C_N(_111_),
    .X(_112_)
  );
  sky130_fd_sc_hd__and4_2 _223_ (
    .A(_099_),
    .B(_104_),
    .C(_108_),
    .D(_112_),
    .X(_113_)
  );
  sky130_fd_sc_hd__xnor2_2 _224_ (
    .A(\num_i_bar[2] ),
    .B(\rng_rd.mem[1][2] ),
    .Y(_114_)
  );
  sky130_fd_sc_hd__a22o_2 _225_ (
    .A1(_057_),
    .A2(\rng_rd.mem[1][0] ),
    .B1(_068_),
    .B2(\num_i_bar[1] ),
    .X(_115_)
  );
  sky130_fd_sc_hd__o221a_2 _226_ (
    .A1(_057_),
    .A2(\rng_rd.mem[1][0] ),
    .B1(_068_),
    .B2(\num_i_bar[1] ),
    .C1(\rng_rd.vld[1] ),
    .X(_116_)
  );
  sky130_fd_sc_hd__and3b_2 _227_ (
    .A_N(_115_),
    .B(_116_),
    .C(_114_),
    .X(_117_)
  );
  sky130_fd_sc_hd__and2_2 _228_ (
    .A(\num_i_bar[1] ),
    .B(\rng_rd.mem[3][1] ),
    .X(_118_)
  );
  sky130_fd_sc_hd__nor2_2 _229_ (
    .A(\num_i_bar[1] ),
    .B(\rng_rd.mem[3][1] ),
    .Y(_119_)
  );
  sky130_fd_sc_hd__o2bb2a_2 _230_ (
    .A1_N(_060_),
    .A2_N(\rng_rd.mem[3][2] ),
    .B1(\rng_rd.mem[3][0] ),
    .B2(_057_),
    .X(_120_)
  );
  sky130_fd_sc_hd__o221a_2 _231_ (
    .A1(\num_i_bar[0] ),
    .A2(_069_),
    .B1(_118_),
    .B2(_119_),
    .C1(\rng_rd.vld[3] ),
    .X(_121_)
  );
  sky130_fd_sc_hd__o211a_2 _232_ (
    .A1(_060_),
    .A2(\rng_rd.mem[3][2] ),
    .B1(_120_),
    .C1(_121_),
    .X(_122_)
  );
  sky130_fd_sc_hd__or2_2 _233_ (
    .A(_057_),
    .B(\rng_rd.mem[8][0] ),
    .X(_123_)
  );
  sky130_fd_sc_hd__nor2_2 _234_ (
    .A(\num_i_bar[2] ),
    .B(\rng_rd.mem[8][2] ),
    .Y(_124_)
  );
  sky130_fd_sc_hd__and2_2 _235_ (
    .A(\num_i_bar[2] ),
    .B(\rng_rd.mem[8][2] ),
    .X(_125_)
  );
  sky130_fd_sc_hd__a22o_2 _236_ (
    .A1(_057_),
    .A2(\rng_rd.mem[8][0] ),
    .B1(\rng_rd.mem[8][1] ),
    .B2(_059_),
    .X(_126_)
  );
  sky130_fd_sc_hd__o221a_2 _237_ (
    .A1(_059_),
    .A2(\rng_rd.mem[8][1] ),
    .B1(_124_),
    .B2(_125_),
    .C1(\rng_rd.vld[8] ),
    .X(_127_)
  );
  sky130_fd_sc_hd__and3b_2 _238_ (
    .A_N(_126_),
    .B(_127_),
    .C(_123_),
    .X(_128_)
  );
  sky130_fd_sc_hd__o2bb2a_2 _239_ (
    .A1_N(_060_),
    .A2_N(\rng_rd.mem[5][2] ),
    .B1(\rng_rd.mem[5][0] ),
    .B2(_057_),
    .X(_129_)
  );
  sky130_fd_sc_hd__nor2_2 _240_ (
    .A(\num_i_bar[1] ),
    .B(\rng_rd.mem[5][1] ),
    .Y(_130_)
  );
  sky130_fd_sc_hd__and2_2 _241_ (
    .A(\num_i_bar[1] ),
    .B(\rng_rd.mem[5][1] ),
    .X(_131_)
  );
  sky130_fd_sc_hd__o221a_2 _242_ (
    .A1(\num_i_bar[0] ),
    .A2(_071_),
    .B1(_130_),
    .B2(_131_),
    .C1(\rng_rd.vld[5] ),
    .X(_132_)
  );
  sky130_fd_sc_hd__o211a_2 _243_ (
    .A1(_060_),
    .A2(\rng_rd.mem[5][2] ),
    .B1(_129_),
    .C1(_132_),
    .X(_133_)
  );
  sky130_fd_sc_hd__nor4_2 _244_ (
    .A(_117_),
    .B(_122_),
    .C(_128_),
    .D(_133_),
    .Y(_134_)
  );
  sky130_fd_sc_hd__and3_2 _245_ (
    .A(_095_),
    .B(_113_),
    .C(_134_),
    .X(_135_)
  );
  sky130_fd_sc_hd__or2_2 _246_ (
    .A(req_num_i),
    .B(req_num_again),
    .X(_136_)
  );
  sky130_fd_sc_hd__and2b_2 _247_ (
    .A_N(_135_),
    .B(_136_),
    .X(req_num_again)
  );
  sky130_fd_sc_hd__and2b_2 _248_ (
    .A_N(\rng_rd.wr_ff2_d ),
    .B(\rng_rd.wr_ff2 ),
    .X(_000_)
  );
  sky130_fd_sc_hd__or2_2 _249_ (
    .A(\rng_dp.seed_sel_i[1] ),
    .B(_001_),
    .X(_137_)
  );
  sky130_fd_sc_hd__nand2_2 _250_ (
    .A(\rng_dp.seed_sel_i[1] ),
    .B(_001_),
    .Y(_138_)
  );
  sky130_fd_sc_hd__nand2_2 _251_ (
    .A(_137_),
    .B(_138_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__and4_2 _252_ (
    .A(\rng_rd.wr_pulse ),
    .B(_095_),
    .C(_113_),
    .D(_134_),
    .X(_139_)
  );
  sky130_fd_sc_hd__mux2_1 _253_ (
    .A0(\rng_rd.mem[11][0] ),
    .A1(\rng_rd.mem[10][0] ),
    .S(_139_),
    .X(_003_)
  );
  sky130_fd_sc_hd__mux2_1 _254_ (
    .A0(\rng_rd.mem[11][1] ),
    .A1(\rng_rd.mem[10][1] ),
    .S(_139_),
    .X(_004_)
  );
  sky130_fd_sc_hd__mux2_1 _255_ (
    .A0(\rng_rd.mem[11][2] ),
    .A1(\rng_rd.mem[10][2] ),
    .S(_139_),
    .X(_005_)
  );
  sky130_fd_sc_hd__nor2_2 _256_ (
    .A(_065_),
    .B(\rng_dp.inst.next_num_o[1] ),
    .Y(_140_)
  );
  sky130_fd_sc_hd__nor2_2 _257_ (
    .A(\rng_dp.inst.next_num_o[0] ),
    .B(_066_),
    .Y(_141_)
  );
  sky130_fd_sc_hd__nor2_2 _258_ (
    .A(\rng_dp.inst.next_num_o[0] ),
    .B(\rng_dp.inst.next_num_o[2] ),
    .Y(_142_)
  );
  sky130_fd_sc_hd__or3_2 _259_ (
    .A(_138_),
    .B(_141_),
    .C(_142_),
    .X(_143_)
  );
  sky130_fd_sc_hd__a21oi_2 _260_ (
    .A1(\rng_dp.inst.next_num_o[0] ),
    .A2(_140_),
    .B1(_143_),
    .Y(_144_)
  );
  sky130_fd_sc_hd__nor2_2 _261_ (
    .A(_064_),
    .B(_065_),
    .Y(_145_)
  );
  sky130_fd_sc_hd__o21ai_2 _262_ (
    .A1(_142_),
    .A2(_145_),
    .B1(\rng_dp.seed_sel_i[0] ),
    .Y(_146_)
  );
  sky130_fd_sc_hd__o211a_2 _263_ (
    .A1(_142_),
    .A2(_145_),
    .B1(\rng_dp.seed_sel_i[1] ),
    .C1(\rng_dp.seed_sel_i[0] ),
    .X(_147_)
  );
  sky130_fd_sc_hd__a211o_2 _264_ (
    .A1(_064_),
    .A2(\rng_dp.inst.next_num_o[2] ),
    .B1(\rng_dp.seed_sel_i[1] ),
    .C1(\rng_dp.seed_sel_i[0] ),
    .X(_148_)
  );
  sky130_fd_sc_hd__a21o_2 _265_ (
    .A1(\rng_dp.inst.next_num_o[2] ),
    .A2(\rng_dp.inst.next_num_o[1] ),
    .B1(_137_),
    .X(_149_)
  );
  sky130_fd_sc_hd__a22o_2 _266_ (
    .A1(\rng_dp.inst.next_num_o[0] ),
    .A2(_066_),
    .B1(_148_),
    .B2(_149_),
    .X(_150_)
  );
  sky130_fd_sc_hd__nand2_2 _267_ (
    .A(_136_),
    .B(_150_),
    .Y(_151_)
  );
  sky130_fd_sc_hd__o32a_2 _268_ (
    .A1(_144_),
    .A2(_147_),
    .A3(_151_),
    .B1(_136_),
    .B2(\num_i_bar[0] ),
    .X(_006_)
  );
  sky130_fd_sc_hd__or2_2 _269_ (
    .A(_138_),
    .B(_140_),
    .X(_152_)
  );
  sky130_fd_sc_hd__a22o_2 _270_ (
    .A1(_065_),
    .A2(\rng_dp.inst.next_num_o[1] ),
    .B1(_148_),
    .B2(_152_),
    .X(_153_)
  );
  sky130_fd_sc_hd__nor2_2 _271_ (
    .A(\rng_dp.inst.next_num_o[2] ),
    .B(_141_),
    .Y(_154_)
  );
  sky130_fd_sc_hd__a211o_2 _272_ (
    .A1(\rng_dp.inst.next_num_o[0] ),
    .A2(_066_),
    .B1(_137_),
    .C1(_154_),
    .X(_155_)
  );
  sky130_fd_sc_hd__nand2_2 _273_ (
    .A(\rng_dp.seed_sel_i[1] ),
    .B(\rng_dp.seed_sel_i[0] ),
    .Y(_156_)
  );
  sky130_fd_sc_hd__o311a_2 _274_ (
    .A1(_140_),
    .A2(_141_),
    .A3(_156_),
    .B1(_155_),
    .C1(_136_),
    .X(_157_)
  );
  sky130_fd_sc_hd__o2bb2a_2 _275_ (
    .A1_N(_157_),
    .A2_N(_153_),
    .B1(_136_),
    .B2(\num_i_bar[1] ),
    .X(_007_)
  );
  sky130_fd_sc_hd__o21a_2 _276_ (
    .A1(_142_),
    .A2(_145_),
    .B1(\rng_dp.inst.next_num_o[1] ),
    .X(_158_)
  );
  sky130_fd_sc_hd__or4_2 _277_ (
    .A(\rng_dp.seed_sel_i[1] ),
    .B(\rng_dp.seed_sel_i[0] ),
    .C(_140_),
    .D(_158_),
    .X(_159_)
  );
  sky130_fd_sc_hd__nand2_2 _278_ (
    .A(\rng_dp.inst.next_num_o[2] ),
    .B(\rng_dp.seed_sel_i[1] ),
    .Y(_160_)
  );
  sky130_fd_sc_hd__a32o_2 _279_ (
    .A1(_146_),
    .A2(_159_),
    .A3(_160_),
    .B1(\rng_dp.seed_sel_i[0] ),
    .B2(\rng_dp.seed_sel_i[1] ),
    .X(_161_)
  );
  sky130_fd_sc_hd__nor2_2 _280_ (
    .A(\rng_dp.inst.next_num_o[1] ),
    .B(_145_),
    .Y(_162_)
  );
  sky130_fd_sc_hd__o31a_2 _281_ (
    .A1(_142_),
    .A2(_156_),
    .A3(_162_),
    .B1(_136_),
    .X(_163_)
  );
  sky130_fd_sc_hd__o2bb2a_2 _282_ (
    .A1_N(_163_),
    .A2_N(_161_),
    .B1(_136_),
    .B2(\num_i_bar[2] ),
    .X(_008_)
  );
  sky130_fd_sc_hd__mux2_1 _283_ (
    .A0(\rng_rd.mem[7][0] ),
    .A1(\rng_rd.mem[6][0] ),
    .S(_139_),
    .X(_009_)
  );
  sky130_fd_sc_hd__mux2_1 _284_ (
    .A0(\rng_rd.mem[7][1] ),
    .A1(\rng_rd.mem[6][1] ),
    .S(_139_),
    .X(_010_)
  );
  sky130_fd_sc_hd__mux2_1 _285_ (
    .A0(\rng_rd.mem[7][2] ),
    .A1(\rng_rd.mem[6][2] ),
    .S(_139_),
    .X(_011_)
  );
  sky130_fd_sc_hd__mux2_1 _286_ (
    .A0(\rng_rd.mem[10][0] ),
    .A1(\rng_rd.mem[9][0] ),
    .S(_139_),
    .X(_012_)
  );
  sky130_fd_sc_hd__mux2_1 _287_ (
    .A0(\rng_rd.mem[10][1] ),
    .A1(\rng_rd.mem[9][1] ),
    .S(_139_),
    .X(_013_)
  );
  sky130_fd_sc_hd__mux2_1 _288_ (
    .A0(\rng_rd.mem[10][2] ),
    .A1(\rng_rd.mem[9][2] ),
    .S(_139_),
    .X(_014_)
  );
  sky130_fd_sc_hd__mux2_1 _289_ (
    .A0(\rng_rd.mem[6][0] ),
    .A1(\rng_rd.mem[5][0] ),
    .S(_139_),
    .X(_015_)
  );
  sky130_fd_sc_hd__mux2_1 _290_ (
    .A0(\rng_rd.mem[6][1] ),
    .A1(\rng_rd.mem[5][1] ),
    .S(_139_),
    .X(_016_)
  );
  sky130_fd_sc_hd__mux2_1 _291_ (
    .A0(\rng_rd.mem[6][2] ),
    .A1(\rng_rd.mem[5][2] ),
    .S(_139_),
    .X(_017_)
  );
  sky130_fd_sc_hd__mux2_1 _292_ (
    .A0(\rng_rd.mem[5][0] ),
    .A1(\rng_rd.mem[4][0] ),
    .S(_139_),
    .X(_018_)
  );
  sky130_fd_sc_hd__mux2_1 _293_ (
    .A0(\rng_rd.mem[5][1] ),
    .A1(\rng_rd.mem[4][1] ),
    .S(_139_),
    .X(_019_)
  );
  sky130_fd_sc_hd__mux2_1 _294_ (
    .A0(\rng_rd.mem[5][2] ),
    .A1(\rng_rd.mem[4][2] ),
    .S(_139_),
    .X(_020_)
  );
  sky130_fd_sc_hd__mux2_1 _295_ (
    .A0(\rng_rd.mem[4][0] ),
    .A1(\rng_rd.mem[3][0] ),
    .S(_139_),
    .X(_021_)
  );
  sky130_fd_sc_hd__mux2_1 _296_ (
    .A0(\rng_rd.mem[4][1] ),
    .A1(\rng_rd.mem[3][1] ),
    .S(_139_),
    .X(_022_)
  );
  sky130_fd_sc_hd__mux2_1 _297_ (
    .A0(\rng_rd.mem[4][2] ),
    .A1(\rng_rd.mem[3][2] ),
    .S(_139_),
    .X(_023_)
  );
  sky130_fd_sc_hd__mux2_1 _298_ (
    .A0(\rng_rd.mem[3][0] ),
    .A1(\rng_rd.mem[2][0] ),
    .S(_139_),
    .X(_024_)
  );
  sky130_fd_sc_hd__mux2_1 _299_ (
    .A0(\rng_rd.mem[3][1] ),
    .A1(\rng_rd.mem[2][1] ),
    .S(_139_),
    .X(_025_)
  );
  sky130_fd_sc_hd__mux2_1 _300_ (
    .A0(\rng_rd.mem[3][2] ),
    .A1(\rng_rd.mem[2][2] ),
    .S(_139_),
    .X(_026_)
  );
  sky130_fd_sc_hd__mux2_1 _301_ (
    .A0(\rng_rd.mem[2][0] ),
    .A1(\rng_rd.mem[1][0] ),
    .S(_139_),
    .X(_027_)
  );
  sky130_fd_sc_hd__mux2_1 _302_ (
    .A0(\rng_rd.mem[2][1] ),
    .A1(\rng_rd.mem[1][1] ),
    .S(_139_),
    .X(_028_)
  );
  sky130_fd_sc_hd__mux2_1 _303_ (
    .A0(\rng_rd.mem[2][2] ),
    .A1(\rng_rd.mem[1][2] ),
    .S(_139_),
    .X(_029_)
  );
  sky130_fd_sc_hd__mux2_1 _304_ (
    .A0(\rng_rd.mem[1][0] ),
    .A1(num_to_send_o[0]),
    .S(_139_),
    .X(_030_)
  );
  sky130_fd_sc_hd__mux2_1 _305_ (
    .A0(\rng_rd.mem[1][1] ),
    .A1(num_to_send_o[1]),
    .S(_139_),
    .X(_031_)
  );
  sky130_fd_sc_hd__mux2_1 _306_ (
    .A0(\rng_rd.mem[1][2] ),
    .A1(num_to_send_o[2]),
    .S(_139_),
    .X(_032_)
  );
  sky130_fd_sc_hd__mux2_1 _307_ (
    .A0(num_to_send_o[0]),
    .A1(\num_i_bar[0] ),
    .S(_139_),
    .X(_033_)
  );
  sky130_fd_sc_hd__mux2_1 _308_ (
    .A0(num_to_send_o[1]),
    .A1(\num_i_bar[1] ),
    .S(_139_),
    .X(_034_)
  );
  sky130_fd_sc_hd__mux2_1 _309_ (
    .A0(num_to_send_o[2]),
    .A1(\num_i_bar[2] ),
    .S(_139_),
    .X(_035_)
  );
  sky130_fd_sc_hd__or2_2 _310_ (
    .A(\rng_rd.vld[0] ),
    .B(_139_),
    .X(_036_)
  );
  sky130_fd_sc_hd__mux2_1 _311_ (
    .A0(\rng_rd.vld[1] ),
    .A1(\rng_rd.vld[0] ),
    .S(_139_),
    .X(_037_)
  );
  sky130_fd_sc_hd__mux2_1 _312_ (
    .A0(\rng_rd.vld[2] ),
    .A1(\rng_rd.vld[1] ),
    .S(_139_),
    .X(_038_)
  );
  sky130_fd_sc_hd__mux2_1 _313_ (
    .A0(\rng_rd.vld[3] ),
    .A1(\rng_rd.vld[2] ),
    .S(_139_),
    .X(_039_)
  );
  sky130_fd_sc_hd__mux2_1 _314_ (
    .A0(\rng_rd.vld[4] ),
    .A1(\rng_rd.vld[3] ),
    .S(_139_),
    .X(_040_)
  );
  sky130_fd_sc_hd__mux2_1 _315_ (
    .A0(\rng_rd.vld[5] ),
    .A1(\rng_rd.vld[4] ),
    .S(_139_),
    .X(_041_)
  );
  sky130_fd_sc_hd__mux2_1 _316_ (
    .A0(\rng_rd.vld[6] ),
    .A1(\rng_rd.vld[5] ),
    .S(_139_),
    .X(_042_)
  );
  sky130_fd_sc_hd__mux2_1 _317_ (
    .A0(\rng_rd.vld[7] ),
    .A1(\rng_rd.vld[6] ),
    .S(_139_),
    .X(_043_)
  );
  sky130_fd_sc_hd__mux2_1 _318_ (
    .A0(\rng_rd.vld[8] ),
    .A1(\rng_rd.vld[7] ),
    .S(_139_),
    .X(_044_)
  );
  sky130_fd_sc_hd__mux2_1 _319_ (
    .A0(\rng_rd.vld[9] ),
    .A1(\rng_rd.vld[8] ),
    .S(_139_),
    .X(_045_)
  );
  sky130_fd_sc_hd__mux2_1 _320_ (
    .A0(\rng_rd.vld[10] ),
    .A1(\rng_rd.vld[9] ),
    .S(_139_),
    .X(_046_)
  );
  sky130_fd_sc_hd__mux2_1 _321_ (
    .A0(\rng_rd.vld[11] ),
    .A1(\rng_rd.vld[10] ),
    .S(_139_),
    .X(_047_)
  );
  sky130_fd_sc_hd__mux2_1 _322_ (
    .A0(\rng_rd.mem[8][0] ),
    .A1(\rng_rd.mem[7][0] ),
    .S(_139_),
    .X(_048_)
  );
  sky130_fd_sc_hd__mux2_1 _323_ (
    .A0(\rng_rd.mem[8][1] ),
    .A1(\rng_rd.mem[7][1] ),
    .S(_139_),
    .X(_049_)
  );
  sky130_fd_sc_hd__mux2_1 _324_ (
    .A0(\rng_rd.mem[8][2] ),
    .A1(\rng_rd.mem[7][2] ),
    .S(_139_),
    .X(_050_)
  );
  sky130_fd_sc_hd__xnor2_2 _325_ (
    .A(_064_),
    .B(_136_),
    .Y(_051_)
  );
  sky130_fd_sc_hd__and3_2 _326_ (
    .A(\rng_dp.inst.next_num_o[0] ),
    .B(\rng_dp.inst.next_num_o[1] ),
    .C(_136_),
    .X(_164_)
  );
  sky130_fd_sc_hd__a21oi_2 _327_ (
    .A1(\rng_dp.inst.next_num_o[0] ),
    .A2(_136_),
    .B1(\rng_dp.inst.next_num_o[1] ),
    .Y(_165_)
  );
  sky130_fd_sc_hd__nor2_2 _328_ (
    .A(_164_),
    .B(_165_),
    .Y(_052_)
  );
  sky130_fd_sc_hd__xnor2_2 _329_ (
    .A(_065_),
    .B(_164_),
    .Y(_053_)
  );
  sky130_fd_sc_hd__mux2_1 _330_ (
    .A0(\rng_rd.mem[9][0] ),
    .A1(\rng_rd.mem[8][0] ),
    .S(_139_),
    .X(_054_)
  );
  sky130_fd_sc_hd__mux2_1 _331_ (
    .A0(\rng_rd.mem[9][1] ),
    .A1(\rng_rd.mem[8][1] ),
    .S(_139_),
    .X(_055_)
  );
  sky130_fd_sc_hd__mux2_1 _332_ (
    .A0(\rng_rd.mem[9][2] ),
    .A1(\rng_rd.mem[8][2] ),
    .S(_139_),
    .X(_056_)
  );
  sky130_fd_sc_hd__dfrtp_2 _333_ (
    .CLK(clk_i),
    .D(_003_),
    .Q(\rng_rd.mem[11][0] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _334_ (
    .CLK(clk_i),
    .D(_004_),
    .Q(\rng_rd.mem[11][1] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _335_ (
    .CLK(clk_i),
    .D(_005_),
    .Q(\rng_rd.mem[11][2] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _336_ (
    .CLK(clk_i),
    .D(_006_),
    .Q(\num_i_bar[0] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _337_ (
    .CLK(clk_i),
    .D(_007_),
    .Q(\num_i_bar[1] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _338_ (
    .CLK(clk_i),
    .D(_008_),
    .Q(\num_i_bar[2] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _339_ (
    .CLK(clk_i),
    .D(_001_),
    .Q(\rng_dp.seed_sel_i[0] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _340_ (
    .CLK(clk_i),
    .D(_002_),
    .Q(\rng_dp.seed_sel_i[1] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _341_ (
    .CLK(clk_i),
    .D(_009_),
    .Q(\rng_rd.mem[7][0] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _342_ (
    .CLK(clk_i),
    .D(_010_),
    .Q(\rng_rd.mem[7][1] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _343_ (
    .CLK(clk_i),
    .D(_011_),
    .Q(\rng_rd.mem[7][2] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _344_ (
    .CLK(clk_i),
    .D(_012_),
    .Q(\rng_rd.mem[10][0] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _345_ (
    .CLK(clk_i),
    .D(_013_),
    .Q(\rng_rd.mem[10][1] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _346_ (
    .CLK(clk_i),
    .D(_014_),
    .Q(\rng_rd.mem[10][2] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _347_ (
    .CLK(clk_i),
    .D(_015_),
    .Q(\rng_rd.mem[6][0] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _348_ (
    .CLK(clk_i),
    .D(_016_),
    .Q(\rng_rd.mem[6][1] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _349_ (
    .CLK(clk_i),
    .D(_017_),
    .Q(\rng_rd.mem[6][2] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _350_ (
    .CLK(clk_i),
    .D(_018_),
    .Q(\rng_rd.mem[5][0] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _351_ (
    .CLK(clk_i),
    .D(_019_),
    .Q(\rng_rd.mem[5][1] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _352_ (
    .CLK(clk_i),
    .D(_020_),
    .Q(\rng_rd.mem[5][2] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _353_ (
    .CLK(clk_i),
    .D(_021_),
    .Q(\rng_rd.mem[4][0] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _354_ (
    .CLK(clk_i),
    .D(_022_),
    .Q(\rng_rd.mem[4][1] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _355_ (
    .CLK(clk_i),
    .D(_023_),
    .Q(\rng_rd.mem[4][2] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _356_ (
    .CLK(clk_i),
    .D(wr_i),
    .Q(\rng_rd.wr_ff1 ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _357_ (
    .CLK(clk_i),
    .D(_024_),
    .Q(\rng_rd.mem[3][0] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _358_ (
    .CLK(clk_i),
    .D(_025_),
    .Q(\rng_rd.mem[3][1] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _359_ (
    .CLK(clk_i),
    .D(_026_),
    .Q(\rng_rd.mem[3][2] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _360_ (
    .CLK(clk_i),
    .D(_027_),
    .Q(\rng_rd.mem[2][0] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _361_ (
    .CLK(clk_i),
    .D(_028_),
    .Q(\rng_rd.mem[2][1] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _362_ (
    .CLK(clk_i),
    .D(_029_),
    .Q(\rng_rd.mem[2][2] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _363_ (
    .CLK(clk_i),
    .D(_030_),
    .Q(\rng_rd.mem[1][0] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _364_ (
    .CLK(clk_i),
    .D(_031_),
    .Q(\rng_rd.mem[1][1] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _365_ (
    .CLK(clk_i),
    .D(_032_),
    .Q(\rng_rd.mem[1][2] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _366_ (
    .CLK(clk_i),
    .D(\rng_rd.wr_ff1 ),
    .Q(\rng_rd.wr_ff2 ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _367_ (
    .CLK(clk_i),
    .D(_033_),
    .Q(num_to_send_o[0]),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _368_ (
    .CLK(clk_i),
    .D(_034_),
    .Q(num_to_send_o[1]),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _369_ (
    .CLK(clk_i),
    .D(_035_),
    .Q(num_to_send_o[2]),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _370_ (
    .CLK(clk_i),
    .D(_036_),
    .Q(\rng_rd.vld[0] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _371_ (
    .CLK(clk_i),
    .D(_037_),
    .Q(\rng_rd.vld[1] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _372_ (
    .CLK(clk_i),
    .D(_038_),
    .Q(\rng_rd.vld[2] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _373_ (
    .CLK(clk_i),
    .D(_039_),
    .Q(\rng_rd.vld[3] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _374_ (
    .CLK(clk_i),
    .D(_040_),
    .Q(\rng_rd.vld[4] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _375_ (
    .CLK(clk_i),
    .D(_041_),
    .Q(\rng_rd.vld[5] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _376_ (
    .CLK(clk_i),
    .D(_042_),
    .Q(\rng_rd.vld[6] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _377_ (
    .CLK(clk_i),
    .D(_043_),
    .Q(\rng_rd.vld[7] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _378_ (
    .CLK(clk_i),
    .D(_044_),
    .Q(\rng_rd.vld[8] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _379_ (
    .CLK(clk_i),
    .D(_045_),
    .Q(\rng_rd.vld[9] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _380_ (
    .CLK(clk_i),
    .D(_046_),
    .Q(\rng_rd.vld[10] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _381_ (
    .CLK(clk_i),
    .D(_047_),
    .Q(\rng_rd.vld[11] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _382_ (
    .CLK(clk_i),
    .D(_048_),
    .Q(\rng_rd.mem[8][0] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _383_ (
    .CLK(clk_i),
    .D(_049_),
    .Q(\rng_rd.mem[8][1] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _384_ (
    .CLK(clk_i),
    .D(_050_),
    .Q(\rng_rd.mem[8][2] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _385_ (
    .CLK(clk_i),
    .D(\rng_rd.wr_ff2 ),
    .Q(\rng_rd.wr_ff2_d ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _386_ (
    .CLK(clk_i),
    .D(_051_),
    .Q(\rng_dp.inst.next_num_o[0] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _387_ (
    .CLK(clk_i),
    .D(_052_),
    .Q(\rng_dp.inst.next_num_o[1] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _388_ (
    .CLK(clk_i),
    .D(_053_),
    .Q(\rng_dp.inst.next_num_o[2] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _389_ (
    .CLK(clk_i),
    .D(_054_),
    .Q(\rng_rd.mem[9][0] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _390_ (
    .CLK(clk_i),
    .D(_055_),
    .Q(\rng_rd.mem[9][1] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _391_ (
    .CLK(clk_i),
    .D(_056_),
    .Q(\rng_rd.mem[9][2] ),
    .RESET_B(rst_i)
  );
  sky130_fd_sc_hd__dfrtp_2 _392_ (
    .CLK(clk_i),
    .D(_000_),
    .Q(\rng_rd.wr_pulse ),
    .RESET_B(rst_i)
  );
endmodule
